-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity layernorm_kernel_layernorm_kernel_Pipeline_norm is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    X_0_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_1_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_2_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_3_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_4_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_5_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_6_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_7_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_8_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_9_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_10_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_11_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_12_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_13_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_14_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_15_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_16_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_17_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_18_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_19_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_20_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_21_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_22_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_23_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_24_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_25_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_26_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_27_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_28_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_29_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_30_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_31_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_32_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_33_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_34_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_35_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_36_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_37_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_38_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_39_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_40_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_41_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_42_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_43_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_44_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_45_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_46_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_47_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_48_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_49_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_50_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_51_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_52_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_53_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_54_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_55_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_56_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_57_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_58_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_59_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_60_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_61_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_62_load : IN STD_LOGIC_VECTOR (7 downto 0);
    X_63_load : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln29 : IN STD_LOGIC_VECTOR (17 downto 0);
    sext_ln27 : IN STD_LOGIC_VECTOR (23 downto 0);
    Y_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    Y_ce0 : OUT STD_LOGIC;
    Y_we0 : OUT STD_LOGIC;
    Y_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of layernorm_kernel_layernorm_kernel_Pipeline_norm is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv32_2C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101100";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv16_FF80 : STD_LOGIC_VECTOR (15 downto 0) := "1111111110000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln27_fu_771_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal sext_ln27_cast_fu_755_p1 : STD_LOGIC_VECTOR (44 downto 0);
    signal sext_ln27_cast_reg_1191 : STD_LOGIC_VECTOR (44 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_1_reg_1196 : STD_LOGIC_VECTOR (6 downto 0);
    signal i_1_reg_1196_pp0_iter1_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal sub_ln29_fu_1063_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal sub_ln29_reg_1205 : STD_LOGIC_VECTOR (20 downto 0);
    signal mul_ln29_fu_751_p2 : STD_LOGIC_VECTOR (44 downto 0);
    signal mul_ln29_reg_1210 : STD_LOGIC_VECTOR (44 downto 0);
    signal tmp_13_cast_reg_1215 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln29_fu_1100_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln29_reg_1222 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln27_fu_1106_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal i_fu_338 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln27_fu_777_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (6 downto 0);
    signal Y_we0_local : STD_LOGIC;
    signal select_ln30_1_fu_1175_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal Y_ce0_local : STD_LOGIC;
    signal mul_ln29_fu_751_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_s_fu_787_p129 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_787_p130 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p131 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln2_fu_1051_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln29_1_fu_1059_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal sext_ln29_cast_fu_759_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln29_fu_1088_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_1_fu_1092_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln29_fu_1117_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_1110_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln29_fu_1122_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal q_fu_1128_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_fu_1141_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln15_fu_1135_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln16_fu_1151_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln30_fu_1169_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln30_fu_1161_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln30_fu_1157_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_s_fu_787_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p5 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p7 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p9 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p11 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p13 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p15 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p17 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p19 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p21 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p23 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p25 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p27 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p29 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p31 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p33 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p35 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p37 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p39 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p41 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p43 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p45 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p47 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p49 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p51 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p53 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p55 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p57 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p59 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p61 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p63 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p65 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p67 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p69 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p71 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p73 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p75 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p77 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p79 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p81 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p83 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p85 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p87 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p89 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p91 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p93 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p95 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p97 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p99 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p101 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p103 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p105 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p107 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p109 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p111 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p113 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p115 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p117 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p119 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p121 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p123 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p125 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_787_p127 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component layernorm_kernel_mul_21s_24s_45_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (20 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        dout : OUT STD_LOGIC_VECTOR (44 downto 0) );
    end component;


    component layernorm_kernel_sparsemux_129_6_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (5 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (5 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (5 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (5 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (5 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (5 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (5 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (5 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (5 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (5 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (5 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (5 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (5 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (5 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (5 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (5 downto 0);
        din15_WIDTH : INTEGER;
        CASE16 : STD_LOGIC_VECTOR (5 downto 0);
        din16_WIDTH : INTEGER;
        CASE17 : STD_LOGIC_VECTOR (5 downto 0);
        din17_WIDTH : INTEGER;
        CASE18 : STD_LOGIC_VECTOR (5 downto 0);
        din18_WIDTH : INTEGER;
        CASE19 : STD_LOGIC_VECTOR (5 downto 0);
        din19_WIDTH : INTEGER;
        CASE20 : STD_LOGIC_VECTOR (5 downto 0);
        din20_WIDTH : INTEGER;
        CASE21 : STD_LOGIC_VECTOR (5 downto 0);
        din21_WIDTH : INTEGER;
        CASE22 : STD_LOGIC_VECTOR (5 downto 0);
        din22_WIDTH : INTEGER;
        CASE23 : STD_LOGIC_VECTOR (5 downto 0);
        din23_WIDTH : INTEGER;
        CASE24 : STD_LOGIC_VECTOR (5 downto 0);
        din24_WIDTH : INTEGER;
        CASE25 : STD_LOGIC_VECTOR (5 downto 0);
        din25_WIDTH : INTEGER;
        CASE26 : STD_LOGIC_VECTOR (5 downto 0);
        din26_WIDTH : INTEGER;
        CASE27 : STD_LOGIC_VECTOR (5 downto 0);
        din27_WIDTH : INTEGER;
        CASE28 : STD_LOGIC_VECTOR (5 downto 0);
        din28_WIDTH : INTEGER;
        CASE29 : STD_LOGIC_VECTOR (5 downto 0);
        din29_WIDTH : INTEGER;
        CASE30 : STD_LOGIC_VECTOR (5 downto 0);
        din30_WIDTH : INTEGER;
        CASE31 : STD_LOGIC_VECTOR (5 downto 0);
        din31_WIDTH : INTEGER;
        CASE32 : STD_LOGIC_VECTOR (5 downto 0);
        din32_WIDTH : INTEGER;
        CASE33 : STD_LOGIC_VECTOR (5 downto 0);
        din33_WIDTH : INTEGER;
        CASE34 : STD_LOGIC_VECTOR (5 downto 0);
        din34_WIDTH : INTEGER;
        CASE35 : STD_LOGIC_VECTOR (5 downto 0);
        din35_WIDTH : INTEGER;
        CASE36 : STD_LOGIC_VECTOR (5 downto 0);
        din36_WIDTH : INTEGER;
        CASE37 : STD_LOGIC_VECTOR (5 downto 0);
        din37_WIDTH : INTEGER;
        CASE38 : STD_LOGIC_VECTOR (5 downto 0);
        din38_WIDTH : INTEGER;
        CASE39 : STD_LOGIC_VECTOR (5 downto 0);
        din39_WIDTH : INTEGER;
        CASE40 : STD_LOGIC_VECTOR (5 downto 0);
        din40_WIDTH : INTEGER;
        CASE41 : STD_LOGIC_VECTOR (5 downto 0);
        din41_WIDTH : INTEGER;
        CASE42 : STD_LOGIC_VECTOR (5 downto 0);
        din42_WIDTH : INTEGER;
        CASE43 : STD_LOGIC_VECTOR (5 downto 0);
        din43_WIDTH : INTEGER;
        CASE44 : STD_LOGIC_VECTOR (5 downto 0);
        din44_WIDTH : INTEGER;
        CASE45 : STD_LOGIC_VECTOR (5 downto 0);
        din45_WIDTH : INTEGER;
        CASE46 : STD_LOGIC_VECTOR (5 downto 0);
        din46_WIDTH : INTEGER;
        CASE47 : STD_LOGIC_VECTOR (5 downto 0);
        din47_WIDTH : INTEGER;
        CASE48 : STD_LOGIC_VECTOR (5 downto 0);
        din48_WIDTH : INTEGER;
        CASE49 : STD_LOGIC_VECTOR (5 downto 0);
        din49_WIDTH : INTEGER;
        CASE50 : STD_LOGIC_VECTOR (5 downto 0);
        din50_WIDTH : INTEGER;
        CASE51 : STD_LOGIC_VECTOR (5 downto 0);
        din51_WIDTH : INTEGER;
        CASE52 : STD_LOGIC_VECTOR (5 downto 0);
        din52_WIDTH : INTEGER;
        CASE53 : STD_LOGIC_VECTOR (5 downto 0);
        din53_WIDTH : INTEGER;
        CASE54 : STD_LOGIC_VECTOR (5 downto 0);
        din54_WIDTH : INTEGER;
        CASE55 : STD_LOGIC_VECTOR (5 downto 0);
        din55_WIDTH : INTEGER;
        CASE56 : STD_LOGIC_VECTOR (5 downto 0);
        din56_WIDTH : INTEGER;
        CASE57 : STD_LOGIC_VECTOR (5 downto 0);
        din57_WIDTH : INTEGER;
        CASE58 : STD_LOGIC_VECTOR (5 downto 0);
        din58_WIDTH : INTEGER;
        CASE59 : STD_LOGIC_VECTOR (5 downto 0);
        din59_WIDTH : INTEGER;
        CASE60 : STD_LOGIC_VECTOR (5 downto 0);
        din60_WIDTH : INTEGER;
        CASE61 : STD_LOGIC_VECTOR (5 downto 0);
        din61_WIDTH : INTEGER;
        CASE62 : STD_LOGIC_VECTOR (5 downto 0);
        din62_WIDTH : INTEGER;
        CASE63 : STD_LOGIC_VECTOR (5 downto 0);
        din63_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        din4 : IN STD_LOGIC_VECTOR (7 downto 0);
        din5 : IN STD_LOGIC_VECTOR (7 downto 0);
        din6 : IN STD_LOGIC_VECTOR (7 downto 0);
        din7 : IN STD_LOGIC_VECTOR (7 downto 0);
        din8 : IN STD_LOGIC_VECTOR (7 downto 0);
        din9 : IN STD_LOGIC_VECTOR (7 downto 0);
        din10 : IN STD_LOGIC_VECTOR (7 downto 0);
        din11 : IN STD_LOGIC_VECTOR (7 downto 0);
        din12 : IN STD_LOGIC_VECTOR (7 downto 0);
        din13 : IN STD_LOGIC_VECTOR (7 downto 0);
        din14 : IN STD_LOGIC_VECTOR (7 downto 0);
        din15 : IN STD_LOGIC_VECTOR (7 downto 0);
        din16 : IN STD_LOGIC_VECTOR (7 downto 0);
        din17 : IN STD_LOGIC_VECTOR (7 downto 0);
        din18 : IN STD_LOGIC_VECTOR (7 downto 0);
        din19 : IN STD_LOGIC_VECTOR (7 downto 0);
        din20 : IN STD_LOGIC_VECTOR (7 downto 0);
        din21 : IN STD_LOGIC_VECTOR (7 downto 0);
        din22 : IN STD_LOGIC_VECTOR (7 downto 0);
        din23 : IN STD_LOGIC_VECTOR (7 downto 0);
        din24 : IN STD_LOGIC_VECTOR (7 downto 0);
        din25 : IN STD_LOGIC_VECTOR (7 downto 0);
        din26 : IN STD_LOGIC_VECTOR (7 downto 0);
        din27 : IN STD_LOGIC_VECTOR (7 downto 0);
        din28 : IN STD_LOGIC_VECTOR (7 downto 0);
        din29 : IN STD_LOGIC_VECTOR (7 downto 0);
        din30 : IN STD_LOGIC_VECTOR (7 downto 0);
        din31 : IN STD_LOGIC_VECTOR (7 downto 0);
        din32 : IN STD_LOGIC_VECTOR (7 downto 0);
        din33 : IN STD_LOGIC_VECTOR (7 downto 0);
        din34 : IN STD_LOGIC_VECTOR (7 downto 0);
        din35 : IN STD_LOGIC_VECTOR (7 downto 0);
        din36 : IN STD_LOGIC_VECTOR (7 downto 0);
        din37 : IN STD_LOGIC_VECTOR (7 downto 0);
        din38 : IN STD_LOGIC_VECTOR (7 downto 0);
        din39 : IN STD_LOGIC_VECTOR (7 downto 0);
        din40 : IN STD_LOGIC_VECTOR (7 downto 0);
        din41 : IN STD_LOGIC_VECTOR (7 downto 0);
        din42 : IN STD_LOGIC_VECTOR (7 downto 0);
        din43 : IN STD_LOGIC_VECTOR (7 downto 0);
        din44 : IN STD_LOGIC_VECTOR (7 downto 0);
        din45 : IN STD_LOGIC_VECTOR (7 downto 0);
        din46 : IN STD_LOGIC_VECTOR (7 downto 0);
        din47 : IN STD_LOGIC_VECTOR (7 downto 0);
        din48 : IN STD_LOGIC_VECTOR (7 downto 0);
        din49 : IN STD_LOGIC_VECTOR (7 downto 0);
        din50 : IN STD_LOGIC_VECTOR (7 downto 0);
        din51 : IN STD_LOGIC_VECTOR (7 downto 0);
        din52 : IN STD_LOGIC_VECTOR (7 downto 0);
        din53 : IN STD_LOGIC_VECTOR (7 downto 0);
        din54 : IN STD_LOGIC_VECTOR (7 downto 0);
        din55 : IN STD_LOGIC_VECTOR (7 downto 0);
        din56 : IN STD_LOGIC_VECTOR (7 downto 0);
        din57 : IN STD_LOGIC_VECTOR (7 downto 0);
        din58 : IN STD_LOGIC_VECTOR (7 downto 0);
        din59 : IN STD_LOGIC_VECTOR (7 downto 0);
        din60 : IN STD_LOGIC_VECTOR (7 downto 0);
        din61 : IN STD_LOGIC_VECTOR (7 downto 0);
        din62 : IN STD_LOGIC_VECTOR (7 downto 0);
        din63 : IN STD_LOGIC_VECTOR (7 downto 0);
        def : IN STD_LOGIC_VECTOR (7 downto 0);
        sel : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component layernorm_kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_21s_24s_45_1_1_U71 : component layernorm_kernel_mul_21s_24s_45_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 21,
        din1_WIDTH => 24,
        dout_WIDTH => 45)
    port map (
        din0 => sub_ln29_reg_1205,
        din1 => mul_ln29_fu_751_p1,
        dout => mul_ln29_fu_751_p2);

    sparsemux_129_6_8_1_1_U72 : component layernorm_kernel_sparsemux_129_6_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000000",
        din0_WIDTH => 8,
        CASE1 => "000001",
        din1_WIDTH => 8,
        CASE2 => "000010",
        din2_WIDTH => 8,
        CASE3 => "000011",
        din3_WIDTH => 8,
        CASE4 => "000100",
        din4_WIDTH => 8,
        CASE5 => "000101",
        din5_WIDTH => 8,
        CASE6 => "000110",
        din6_WIDTH => 8,
        CASE7 => "000111",
        din7_WIDTH => 8,
        CASE8 => "001000",
        din8_WIDTH => 8,
        CASE9 => "001001",
        din9_WIDTH => 8,
        CASE10 => "001010",
        din10_WIDTH => 8,
        CASE11 => "001011",
        din11_WIDTH => 8,
        CASE12 => "001100",
        din12_WIDTH => 8,
        CASE13 => "001101",
        din13_WIDTH => 8,
        CASE14 => "001110",
        din14_WIDTH => 8,
        CASE15 => "001111",
        din15_WIDTH => 8,
        CASE16 => "010000",
        din16_WIDTH => 8,
        CASE17 => "010001",
        din17_WIDTH => 8,
        CASE18 => "010010",
        din18_WIDTH => 8,
        CASE19 => "010011",
        din19_WIDTH => 8,
        CASE20 => "010100",
        din20_WIDTH => 8,
        CASE21 => "010101",
        din21_WIDTH => 8,
        CASE22 => "010110",
        din22_WIDTH => 8,
        CASE23 => "010111",
        din23_WIDTH => 8,
        CASE24 => "011000",
        din24_WIDTH => 8,
        CASE25 => "011001",
        din25_WIDTH => 8,
        CASE26 => "011010",
        din26_WIDTH => 8,
        CASE27 => "011011",
        din27_WIDTH => 8,
        CASE28 => "011100",
        din28_WIDTH => 8,
        CASE29 => "011101",
        din29_WIDTH => 8,
        CASE30 => "011110",
        din30_WIDTH => 8,
        CASE31 => "011111",
        din31_WIDTH => 8,
        CASE32 => "100000",
        din32_WIDTH => 8,
        CASE33 => "100001",
        din33_WIDTH => 8,
        CASE34 => "100010",
        din34_WIDTH => 8,
        CASE35 => "100011",
        din35_WIDTH => 8,
        CASE36 => "100100",
        din36_WIDTH => 8,
        CASE37 => "100101",
        din37_WIDTH => 8,
        CASE38 => "100110",
        din38_WIDTH => 8,
        CASE39 => "100111",
        din39_WIDTH => 8,
        CASE40 => "101000",
        din40_WIDTH => 8,
        CASE41 => "101001",
        din41_WIDTH => 8,
        CASE42 => "101010",
        din42_WIDTH => 8,
        CASE43 => "101011",
        din43_WIDTH => 8,
        CASE44 => "101100",
        din44_WIDTH => 8,
        CASE45 => "101101",
        din45_WIDTH => 8,
        CASE46 => "101110",
        din46_WIDTH => 8,
        CASE47 => "101111",
        din47_WIDTH => 8,
        CASE48 => "110000",
        din48_WIDTH => 8,
        CASE49 => "110001",
        din49_WIDTH => 8,
        CASE50 => "110010",
        din50_WIDTH => 8,
        CASE51 => "110011",
        din51_WIDTH => 8,
        CASE52 => "110100",
        din52_WIDTH => 8,
        CASE53 => "110101",
        din53_WIDTH => 8,
        CASE54 => "110110",
        din54_WIDTH => 8,
        CASE55 => "110111",
        din55_WIDTH => 8,
        CASE56 => "111000",
        din56_WIDTH => 8,
        CASE57 => "111001",
        din57_WIDTH => 8,
        CASE58 => "111010",
        din58_WIDTH => 8,
        CASE59 => "111011",
        din59_WIDTH => 8,
        CASE60 => "111100",
        din60_WIDTH => 8,
        CASE61 => "111101",
        din61_WIDTH => 8,
        CASE62 => "111110",
        din62_WIDTH => 8,
        CASE63 => "111111",
        din63_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 6,
        dout_WIDTH => 8)
    port map (
        din0 => X_0_load,
        din1 => X_1_load,
        din2 => X_2_load,
        din3 => X_3_load,
        din4 => X_4_load,
        din5 => X_5_load,
        din6 => X_6_load,
        din7 => X_7_load,
        din8 => X_8_load,
        din9 => X_9_load,
        din10 => X_10_load,
        din11 => X_11_load,
        din12 => X_12_load,
        din13 => X_13_load,
        din14 => X_14_load,
        din15 => X_15_load,
        din16 => X_16_load,
        din17 => X_17_load,
        din18 => X_18_load,
        din19 => X_19_load,
        din20 => X_20_load,
        din21 => X_21_load,
        din22 => X_22_load,
        din23 => X_23_load,
        din24 => X_24_load,
        din25 => X_25_load,
        din26 => X_26_load,
        din27 => X_27_load,
        din28 => X_28_load,
        din29 => X_29_load,
        din30 => X_30_load,
        din31 => X_31_load,
        din32 => X_32_load,
        din33 => X_33_load,
        din34 => X_34_load,
        din35 => X_35_load,
        din36 => X_36_load,
        din37 => X_37_load,
        din38 => X_38_load,
        din39 => X_39_load,
        din40 => X_40_load,
        din41 => X_41_load,
        din42 => X_42_load,
        din43 => X_43_load,
        din44 => X_44_load,
        din45 => X_45_load,
        din46 => X_46_load,
        din47 => X_47_load,
        din48 => X_48_load,
        din49 => X_49_load,
        din50 => X_50_load,
        din51 => X_51_load,
        din52 => X_52_load,
        din53 => X_53_load,
        din54 => X_54_load,
        din55 => X_55_load,
        din56 => X_56_load,
        din57 => X_57_load,
        din58 => X_58_load,
        din59 => X_59_load,
        din60 => X_60_load,
        din61 => X_61_load,
        din62 => X_62_load,
        din63 => X_63_load,
        def => tmp_s_fu_787_p129,
        sel => tmp_s_fu_787_p130,
        dout => tmp_s_fu_787_p131);

    flow_control_loop_pipe_sequential_init_U : component layernorm_kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_338_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln27_fu_771_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_338 <= add_ln27_fu_777_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_338 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                i_1_reg_1196 <= ap_sig_allocacmp_i_1;
                i_1_reg_1196_pp0_iter1_reg <= i_1_reg_1196;
                icmp_ln29_reg_1222 <= icmp_ln29_fu_1100_p2;
                mul_ln29_reg_1210 <= mul_ln29_fu_751_p2;
                sext_ln27_cast_reg_1191 <= sext_ln27_cast_fu_755_p1;
                sub_ln29_reg_1205 <= sub_ln29_fu_1063_p2;
                tmp_13_cast_reg_1215 <= mul_ln29_fu_751_p2(35 downto 20);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    Y_address0 <= zext_ln27_fu_1106_p1(6 - 1 downto 0);
    Y_ce0 <= Y_ce0_local;

    Y_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            Y_ce0_local <= ap_const_logic_1;
        else 
            Y_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    Y_d0 <= select_ln30_1_fu_1175_p3;
    Y_we0 <= Y_we0_local;

    Y_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            Y_we0_local <= ap_const_logic_1;
        else 
            Y_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln27_fu_777_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv7_1));
    add_ln29_fu_1117_p2 <= std_logic_vector(unsigned(tmp_13_cast_reg_1215) + unsigned(ap_const_lv16_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln27_fu_771_p2)
    begin
        if (((icmp_ln27_fu_771_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_338, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_338;
        end if; 
    end process;

    icmp_ln15_fu_1135_p2 <= "1" when (signed(q_fu_1128_p3) < signed(ap_const_lv16_FF80)) else "0";
    icmp_ln16_fu_1151_p2 <= "1" when (signed(tmp_2_fu_1141_p4) > signed(ap_const_lv9_0)) else "0";
    icmp_ln27_fu_771_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv7_40) else "0";
    icmp_ln29_fu_1100_p2 <= "0" when (tmp_1_fu_1092_p3 = ap_const_lv24_0) else "1";
    mul_ln29_fu_751_p1 <= sext_ln27_cast_reg_1191(24 - 1 downto 0);
    or_ln30_fu_1169_p2 <= (icmp_ln16_fu_1151_p2 or icmp_ln15_fu_1135_p2);
    q_fu_1128_p3 <= 
        select_ln29_fu_1122_p3 when (tmp_fu_1110_p3(0) = '1') else 
        tmp_13_cast_reg_1215;
    select_ln29_fu_1122_p3 <= 
        add_ln29_fu_1117_p2 when (icmp_ln29_reg_1222(0) = '1') else 
        tmp_13_cast_reg_1215;
    select_ln30_1_fu_1175_p3 <= 
        select_ln30_fu_1161_p3 when (or_ln30_fu_1169_p2(0) = '1') else 
        trunc_ln30_fu_1157_p1;
    select_ln30_fu_1161_p3 <= 
        ap_const_lv8_80 when (icmp_ln15_fu_1135_p2(0) = '1') else 
        ap_const_lv8_7F;
        sext_ln27_cast_fu_755_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln27),45));

        sext_ln29_1_fu_1059_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln2_fu_1051_p3),21));

        sext_ln29_cast_fu_759_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln29),21));

    shl_ln2_fu_1051_p3 <= (tmp_s_fu_787_p131 & ap_const_lv12_0);
    sub_ln29_fu_1063_p2 <= std_logic_vector(signed(sext_ln29_1_fu_1059_p1) - signed(sext_ln29_cast_fu_759_p1));
    tmp_1_fu_1092_p3 <= (trunc_ln29_fu_1088_p1 & ap_const_lv4_0);
    tmp_2_fu_1141_p4 <= q_fu_1128_p3(15 downto 7);
    tmp_fu_1110_p3 <= mul_ln29_reg_1210(44 downto 44);
    tmp_s_fu_787_p129 <= "XXXXXXXX";
    tmp_s_fu_787_p130 <= ap_sig_allocacmp_i_1(6 - 1 downto 0);
    trunc_ln29_fu_1088_p1 <= mul_ln29_fu_751_p2(20 - 1 downto 0);
    trunc_ln30_fu_1157_p1 <= q_fu_1128_p3(8 - 1 downto 0);
    zext_ln27_fu_1106_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_1_reg_1196_pp0_iter1_reg),64));
end behav;
