// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module tiled_matmul_kernel_tiled_matmul_kernel_Pipeline_store (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        C_0_address0,
        C_0_ce0,
        C_0_we0,
        C_0_d0,
        C_1_address0,
        C_1_ce0,
        C_1_we0,
        C_1_d0,
        C_2_address0,
        C_2_ce0,
        C_2_we0,
        C_2_d0,
        C_3_address0,
        C_3_ce0,
        C_3_we0,
        C_3_d0,
        C_15_address0,
        C_15_ce0,
        C_15_we0,
        C_15_d0,
        C_14_address0,
        C_14_ce0,
        C_14_we0,
        C_14_d0,
        C_13_address0,
        C_13_ce0,
        C_13_we0,
        C_13_d0,
        C_12_address0,
        C_12_ce0,
        C_12_we0,
        C_12_d0,
        C_11_address0,
        C_11_ce0,
        C_11_we0,
        C_11_d0,
        C_10_address0,
        C_10_ce0,
        C_10_we0,
        C_10_d0,
        C_9_address0,
        C_9_ce0,
        C_9_we0,
        C_9_d0,
        C_8_address0,
        C_8_ce0,
        C_8_we0,
        C_8_d0,
        C_7_address0,
        C_7_ce0,
        C_7_we0,
        C_7_d0,
        C_6_address0,
        C_6_ce0,
        C_6_we0,
        C_6_d0,
        C_5_address0,
        C_5_ce0,
        C_5_we0,
        C_5_d0,
        C_4_address0,
        C_4_ce0,
        C_4_we0,
        C_4_d0,
        empty_6,
        add_i59_reload,
        add_i_163_reload,
        add_i_267_reload,
        add_i_371_reload,
        add_i_14160_reload,
        add_i_1_164_reload,
        add_i_2_168_reload,
        add_i_3_172_reload,
        add_i_24961_reload,
        add_i_1_265_reload,
        add_i_2_269_reload,
        add_i_3_273_reload,
        add_i_35762_reload,
        add_i_1_366_reload,
        add_i_2_370_reload,
        add_i_3_374_reload,
        empty
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] C_0_address0;
output   C_0_ce0;
output   C_0_we0;
output  [31:0] C_0_d0;
output  [3:0] C_1_address0;
output   C_1_ce0;
output   C_1_we0;
output  [31:0] C_1_d0;
output  [3:0] C_2_address0;
output   C_2_ce0;
output   C_2_we0;
output  [31:0] C_2_d0;
output  [3:0] C_3_address0;
output   C_3_ce0;
output   C_3_we0;
output  [31:0] C_3_d0;
output  [3:0] C_15_address0;
output   C_15_ce0;
output   C_15_we0;
output  [31:0] C_15_d0;
output  [3:0] C_14_address0;
output   C_14_ce0;
output   C_14_we0;
output  [31:0] C_14_d0;
output  [3:0] C_13_address0;
output   C_13_ce0;
output   C_13_we0;
output  [31:0] C_13_d0;
output  [3:0] C_12_address0;
output   C_12_ce0;
output   C_12_we0;
output  [31:0] C_12_d0;
output  [3:0] C_11_address0;
output   C_11_ce0;
output   C_11_we0;
output  [31:0] C_11_d0;
output  [3:0] C_10_address0;
output   C_10_ce0;
output   C_10_we0;
output  [31:0] C_10_d0;
output  [3:0] C_9_address0;
output   C_9_ce0;
output   C_9_we0;
output  [31:0] C_9_d0;
output  [3:0] C_8_address0;
output   C_8_ce0;
output   C_8_we0;
output  [31:0] C_8_d0;
output  [3:0] C_7_address0;
output   C_7_ce0;
output   C_7_we0;
output  [31:0] C_7_d0;
output  [3:0] C_6_address0;
output   C_6_ce0;
output   C_6_we0;
output  [31:0] C_6_d0;
output  [3:0] C_5_address0;
output   C_5_ce0;
output   C_5_we0;
output  [31:0] C_5_d0;
output  [3:0] C_4_address0;
output   C_4_ce0;
output   C_4_we0;
output  [31:0] C_4_d0;
input  [3:0] empty_6;
input  [19:0] add_i59_reload;
input  [19:0] add_i_163_reload;
input  [19:0] add_i_267_reload;
input  [19:0] add_i_371_reload;
input  [19:0] add_i_14160_reload;
input  [19:0] add_i_1_164_reload;
input  [19:0] add_i_2_168_reload;
input  [19:0] add_i_3_172_reload;
input  [19:0] add_i_24961_reload;
input  [19:0] add_i_1_265_reload;
input  [19:0] add_i_2_269_reload;
input  [19:0] add_i_3_273_reload;
input  [19:0] add_i_35762_reload;
input  [19:0] add_i_1_366_reload;
input  [19:0] add_i_2_370_reload;
input  [19:0] add_i_3_374_reload;
input  [3:0] empty;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln31_fu_448_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln34_fu_474_p1;
wire   [3:0] tmp_read_fu_124_p2;
reg   [2:0] i_fu_120;
wire   [2:0] add_ln31_fu_454_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_i_1;
reg    C_8_we0_local;
wire  signed [31:0] sext_ln34_fu_518_p1;
reg    C_8_ce0_local;
reg    C_9_we0_local;
wire  signed [31:0] sext_ln34_1_fu_550_p1;
reg    C_9_ce0_local;
reg    C_10_we0_local;
wire  signed [31:0] sext_ln34_2_fu_582_p1;
reg    C_10_ce0_local;
reg    C_11_we0_local;
wire  signed [31:0] sext_ln34_3_fu_614_p1;
reg    C_11_ce0_local;
reg    C_4_we0_local;
reg    C_4_ce0_local;
reg    C_5_we0_local;
reg    C_5_ce0_local;
reg    C_6_we0_local;
reg    C_6_ce0_local;
reg    C_7_we0_local;
reg    C_7_ce0_local;
reg    C_0_we0_local;
reg    C_0_ce0_local;
reg    C_1_we0_local;
reg    C_1_ce0_local;
reg    C_2_we0_local;
reg    C_2_ce0_local;
reg    C_3_we0_local;
reg    C_3_ce0_local;
reg    C_12_we0_local;
reg    C_12_ce0_local;
reg    C_13_we0_local;
reg    C_13_ce0_local;
reg    C_14_we0_local;
reg    C_14_ce0_local;
reg    C_15_we0_local;
reg    C_15_ce0_local;
wire   [3:0] zext_ln31_fu_460_p1;
wire   [3:0] add_ln34_fu_468_p2;
wire   [19:0] tmp_8_fu_494_p9;
wire   [1:0] trunc_ln31_fu_464_p1;
wire   [19:0] tmp_8_fu_494_p11;
wire   [19:0] tmp_9_fu_526_p9;
wire   [19:0] tmp_9_fu_526_p11;
wire   [19:0] tmp_s_fu_558_p9;
wire   [19:0] tmp_s_fu_558_p11;
wire   [19:0] tmp_2_fu_590_p9;
wire   [19:0] tmp_2_fu_590_p11;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [1:0] tmp_8_fu_494_p1;
wire   [1:0] tmp_8_fu_494_p3;
wire  signed [1:0] tmp_8_fu_494_p5;
wire  signed [1:0] tmp_8_fu_494_p7;
wire   [1:0] tmp_9_fu_526_p1;
wire   [1:0] tmp_9_fu_526_p3;
wire  signed [1:0] tmp_9_fu_526_p5;
wire  signed [1:0] tmp_9_fu_526_p7;
wire   [1:0] tmp_s_fu_558_p1;
wire   [1:0] tmp_s_fu_558_p3;
wire  signed [1:0] tmp_s_fu_558_p5;
wire  signed [1:0] tmp_s_fu_558_p7;
wire   [1:0] tmp_2_fu_590_p1;
wire   [1:0] tmp_2_fu_590_p3;
wire  signed [1:0] tmp_2_fu_590_p5;
wire  signed [1:0] tmp_2_fu_590_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 i_fu_120 = 3'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) tiled_matmul_kernel_sparsemux_9_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 20 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_9_2_20_1_1_U171(
    .din0(add_i59_reload),
    .din1(add_i_163_reload),
    .din2(add_i_267_reload),
    .din3(add_i_371_reload),
    .def(tmp_8_fu_494_p9),
    .sel(trunc_ln31_fu_464_p1),
    .dout(tmp_8_fu_494_p11)
);

(* dissolve_hierarchy = "yes" *) tiled_matmul_kernel_sparsemux_9_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 20 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_9_2_20_1_1_U172(
    .din0(add_i_14160_reload),
    .din1(add_i_1_164_reload),
    .din2(add_i_2_168_reload),
    .din3(add_i_3_172_reload),
    .def(tmp_9_fu_526_p9),
    .sel(trunc_ln31_fu_464_p1),
    .dout(tmp_9_fu_526_p11)
);

(* dissolve_hierarchy = "yes" *) tiled_matmul_kernel_sparsemux_9_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 20 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_9_2_20_1_1_U173(
    .din0(add_i_24961_reload),
    .din1(add_i_1_265_reload),
    .din2(add_i_2_269_reload),
    .din3(add_i_3_273_reload),
    .def(tmp_s_fu_558_p9),
    .sel(trunc_ln31_fu_464_p1),
    .dout(tmp_s_fu_558_p11)
);

(* dissolve_hierarchy = "yes" *) tiled_matmul_kernel_sparsemux_9_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 20 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_9_2_20_1_1_U174(
    .din0(add_i_35762_reload),
    .din1(add_i_1_366_reload),
    .din2(add_i_2_370_reload),
    .din3(add_i_3_374_reload),
    .def(tmp_2_fu_590_p9),
    .sel(trunc_ln31_fu_464_p1),
    .dout(tmp_2_fu_590_p11)
);

tiled_matmul_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln31_fu_448_p2 == 1'd0)) begin
            i_fu_120 <= add_ln31_fu_454_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_120 <= 3'd0;
        end
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        C_0_ce0_local = 1'b1;
    end else begin
        C_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_448_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (tmp_read_fu_124_p2 == 4'd0))) begin
        C_0_we0_local = 1'b1;
    end else begin
        C_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        C_10_ce0_local = 1'b1;
    end else begin
        C_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_448_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (tmp_read_fu_124_p2 == 4'd8))) begin
        C_10_we0_local = 1'b1;
    end else begin
        C_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        C_11_ce0_local = 1'b1;
    end else begin
        C_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_448_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (tmp_read_fu_124_p2 == 4'd8))) begin
        C_11_we0_local = 1'b1;
    end else begin
        C_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        C_12_ce0_local = 1'b1;
    end else begin
        C_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(tmp_read_fu_124_p2 == 4'd0) & ~(tmp_read_fu_124_p2 == 4'd4) & ~(tmp_read_fu_124_p2 == 4'd8) & (icmp_ln31_fu_448_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        C_12_we0_local = 1'b1;
    end else begin
        C_12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        C_13_ce0_local = 1'b1;
    end else begin
        C_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(tmp_read_fu_124_p2 == 4'd0) & ~(tmp_read_fu_124_p2 == 4'd4) & ~(tmp_read_fu_124_p2 == 4'd8) & (icmp_ln31_fu_448_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        C_13_we0_local = 1'b1;
    end else begin
        C_13_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        C_14_ce0_local = 1'b1;
    end else begin
        C_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(tmp_read_fu_124_p2 == 4'd0) & ~(tmp_read_fu_124_p2 == 4'd4) & ~(tmp_read_fu_124_p2 == 4'd8) & (icmp_ln31_fu_448_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        C_14_we0_local = 1'b1;
    end else begin
        C_14_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        C_15_ce0_local = 1'b1;
    end else begin
        C_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(tmp_read_fu_124_p2 == 4'd0) & ~(tmp_read_fu_124_p2 == 4'd4) & ~(tmp_read_fu_124_p2 == 4'd8) & (icmp_ln31_fu_448_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        C_15_we0_local = 1'b1;
    end else begin
        C_15_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        C_1_ce0_local = 1'b1;
    end else begin
        C_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_448_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (tmp_read_fu_124_p2 == 4'd0))) begin
        C_1_we0_local = 1'b1;
    end else begin
        C_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        C_2_ce0_local = 1'b1;
    end else begin
        C_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_448_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (tmp_read_fu_124_p2 == 4'd0))) begin
        C_2_we0_local = 1'b1;
    end else begin
        C_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        C_3_ce0_local = 1'b1;
    end else begin
        C_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_448_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (tmp_read_fu_124_p2 == 4'd0))) begin
        C_3_we0_local = 1'b1;
    end else begin
        C_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        C_4_ce0_local = 1'b1;
    end else begin
        C_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_448_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (tmp_read_fu_124_p2 == 4'd4))) begin
        C_4_we0_local = 1'b1;
    end else begin
        C_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        C_5_ce0_local = 1'b1;
    end else begin
        C_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_448_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (tmp_read_fu_124_p2 == 4'd4))) begin
        C_5_we0_local = 1'b1;
    end else begin
        C_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        C_6_ce0_local = 1'b1;
    end else begin
        C_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_448_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (tmp_read_fu_124_p2 == 4'd4))) begin
        C_6_we0_local = 1'b1;
    end else begin
        C_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        C_7_ce0_local = 1'b1;
    end else begin
        C_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_448_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (tmp_read_fu_124_p2 == 4'd4))) begin
        C_7_we0_local = 1'b1;
    end else begin
        C_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        C_8_ce0_local = 1'b1;
    end else begin
        C_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_448_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (tmp_read_fu_124_p2 == 4'd8))) begin
        C_8_we0_local = 1'b1;
    end else begin
        C_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        C_9_ce0_local = 1'b1;
    end else begin
        C_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_448_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (tmp_read_fu_124_p2 == 4'd8))) begin
        C_9_we0_local = 1'b1;
    end else begin
        C_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_448_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_1 = 3'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_120;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C_0_address0 = zext_ln34_fu_474_p1;

assign C_0_ce0 = C_0_ce0_local;

assign C_0_d0 = sext_ln34_fu_518_p1;

assign C_0_we0 = C_0_we0_local;

assign C_10_address0 = zext_ln34_fu_474_p1;

assign C_10_ce0 = C_10_ce0_local;

assign C_10_d0 = sext_ln34_2_fu_582_p1;

assign C_10_we0 = C_10_we0_local;

assign C_11_address0 = zext_ln34_fu_474_p1;

assign C_11_ce0 = C_11_ce0_local;

assign C_11_d0 = sext_ln34_3_fu_614_p1;

assign C_11_we0 = C_11_we0_local;

assign C_12_address0 = zext_ln34_fu_474_p1;

assign C_12_ce0 = C_12_ce0_local;

assign C_12_d0 = sext_ln34_fu_518_p1;

assign C_12_we0 = C_12_we0_local;

assign C_13_address0 = zext_ln34_fu_474_p1;

assign C_13_ce0 = C_13_ce0_local;

assign C_13_d0 = sext_ln34_1_fu_550_p1;

assign C_13_we0 = C_13_we0_local;

assign C_14_address0 = zext_ln34_fu_474_p1;

assign C_14_ce0 = C_14_ce0_local;

assign C_14_d0 = sext_ln34_2_fu_582_p1;

assign C_14_we0 = C_14_we0_local;

assign C_15_address0 = zext_ln34_fu_474_p1;

assign C_15_ce0 = C_15_ce0_local;

assign C_15_d0 = sext_ln34_3_fu_614_p1;

assign C_15_we0 = C_15_we0_local;

assign C_1_address0 = zext_ln34_fu_474_p1;

assign C_1_ce0 = C_1_ce0_local;

assign C_1_d0 = sext_ln34_1_fu_550_p1;

assign C_1_we0 = C_1_we0_local;

assign C_2_address0 = zext_ln34_fu_474_p1;

assign C_2_ce0 = C_2_ce0_local;

assign C_2_d0 = sext_ln34_2_fu_582_p1;

assign C_2_we0 = C_2_we0_local;

assign C_3_address0 = zext_ln34_fu_474_p1;

assign C_3_ce0 = C_3_ce0_local;

assign C_3_d0 = sext_ln34_3_fu_614_p1;

assign C_3_we0 = C_3_we0_local;

assign C_4_address0 = zext_ln34_fu_474_p1;

assign C_4_ce0 = C_4_ce0_local;

assign C_4_d0 = sext_ln34_fu_518_p1;

assign C_4_we0 = C_4_we0_local;

assign C_5_address0 = zext_ln34_fu_474_p1;

assign C_5_ce0 = C_5_ce0_local;

assign C_5_d0 = sext_ln34_1_fu_550_p1;

assign C_5_we0 = C_5_we0_local;

assign C_6_address0 = zext_ln34_fu_474_p1;

assign C_6_ce0 = C_6_ce0_local;

assign C_6_d0 = sext_ln34_2_fu_582_p1;

assign C_6_we0 = C_6_we0_local;

assign C_7_address0 = zext_ln34_fu_474_p1;

assign C_7_ce0 = C_7_ce0_local;

assign C_7_d0 = sext_ln34_3_fu_614_p1;

assign C_7_we0 = C_7_we0_local;

assign C_8_address0 = zext_ln34_fu_474_p1;

assign C_8_ce0 = C_8_ce0_local;

assign C_8_d0 = sext_ln34_fu_518_p1;

assign C_8_we0 = C_8_we0_local;

assign C_9_address0 = zext_ln34_fu_474_p1;

assign C_9_ce0 = C_9_ce0_local;

assign C_9_d0 = sext_ln34_1_fu_550_p1;

assign C_9_we0 = C_9_we0_local;

assign add_ln31_fu_454_p2 = (ap_sig_allocacmp_i_1 + 3'd1);

assign add_ln34_fu_468_p2 = (zext_ln31_fu_460_p1 + empty_6);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln31_fu_448_p2 = ((ap_sig_allocacmp_i_1 == 3'd4) ? 1'b1 : 1'b0);

assign sext_ln34_1_fu_550_p1 = $signed(tmp_9_fu_526_p11);

assign sext_ln34_2_fu_582_p1 = $signed(tmp_s_fu_558_p11);

assign sext_ln34_3_fu_614_p1 = $signed(tmp_2_fu_590_p11);

assign sext_ln34_fu_518_p1 = $signed(tmp_8_fu_494_p11);

assign tmp_2_fu_590_p9 = 'bx;

assign tmp_8_fu_494_p9 = 'bx;

assign tmp_9_fu_526_p9 = 'bx;

assign tmp_read_fu_124_p2 = empty;

assign tmp_s_fu_558_p9 = 'bx;

assign trunc_ln31_fu_464_p1 = ap_sig_allocacmp_i_1[1:0];

assign zext_ln31_fu_460_p1 = ap_sig_allocacmp_i_1;

assign zext_ln34_fu_474_p1 = add_ln34_fu_468_p2;

endmodule //tiled_matmul_kernel_tiled_matmul_kernel_Pipeline_store
