// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module gelu_embed_kernel_gelu_embed_kernel_Pipeline_embed (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        token_ids_address0,
        token_ids_ce0,
        token_ids_q0,
        embed_lut_0_address0,
        embed_lut_0_ce0,
        embed_lut_0_q0,
        embed_lut_1_address0,
        embed_lut_1_ce0,
        embed_lut_1_q0,
        embed_lut_2_address0,
        embed_lut_2_ce0,
        embed_lut_2_q0,
        embed_lut_3_address0,
        embed_lut_3_ce0,
        embed_lut_3_q0,
        embed_lut_4_address0,
        embed_lut_4_ce0,
        embed_lut_4_q0,
        embed_lut_5_address0,
        embed_lut_5_ce0,
        embed_lut_5_q0,
        embed_lut_6_address0,
        embed_lut_6_ce0,
        embed_lut_6_q0,
        embed_lut_7_address0,
        embed_lut_7_ce0,
        embed_lut_7_q0,
        embed_out_address0,
        embed_out_ce0,
        embed_out_we0,
        embed_out_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] token_ids_address0;
output   token_ids_ce0;
input  [7:0] token_ids_q0;
output  [4:0] embed_lut_0_address0;
output   embed_lut_0_ce0;
input  [7:0] embed_lut_0_q0;
output  [4:0] embed_lut_1_address0;
output   embed_lut_1_ce0;
input  [7:0] embed_lut_1_q0;
output  [4:0] embed_lut_2_address0;
output   embed_lut_2_ce0;
input  [7:0] embed_lut_2_q0;
output  [4:0] embed_lut_3_address0;
output   embed_lut_3_ce0;
input  [7:0] embed_lut_3_q0;
output  [4:0] embed_lut_4_address0;
output   embed_lut_4_ce0;
input  [7:0] embed_lut_4_q0;
output  [4:0] embed_lut_5_address0;
output   embed_lut_5_ce0;
input  [7:0] embed_lut_5_q0;
output  [4:0] embed_lut_6_address0;
output   embed_lut_6_ce0;
input  [7:0] embed_lut_6_q0;
output  [4:0] embed_lut_7_address0;
output   embed_lut_7_ce0;
input  [7:0] embed_lut_7_q0;
output  [2:0] embed_out_address0;
output   embed_out_ce0;
output   embed_out_we0;
output  [7:0] embed_out_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln13_fu_212_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln13_fu_224_p1;
reg   [63:0] zext_ln13_reg_305;
reg   [63:0] zext_ln13_reg_305_pp0_iter1_reg;
wire   [2:0] trunc_ln13_fu_229_p1;
reg   [2:0] trunc_ln13_reg_310;
reg   [2:0] trunc_ln13_reg_310_pp0_iter1_reg;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln15_fu_242_p1;
reg   [3:0] i_1_fu_70;
wire   [3:0] add_ln13_fu_218_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_i;
reg    token_ids_ce0_local;
reg    embed_lut_0_ce0_local;
reg    embed_lut_1_ce0_local;
reg    embed_lut_2_ce0_local;
reg    embed_lut_3_ce0_local;
reg    embed_lut_4_ce0_local;
reg    embed_lut_5_ce0_local;
reg    embed_lut_6_ce0_local;
reg    embed_lut_7_ce0_local;
reg    embed_out_we0_local;
wire   [7:0] tmp_1_fu_254_p19;
reg    embed_out_ce0_local;
wire   [4:0] trunc_ln15_fu_238_p1;
wire   [7:0] tmp_1_fu_254_p17;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [2:0] tmp_1_fu_254_p1;
wire   [2:0] tmp_1_fu_254_p3;
wire   [2:0] tmp_1_fu_254_p5;
wire   [2:0] tmp_1_fu_254_p7;
wire  signed [2:0] tmp_1_fu_254_p9;
wire  signed [2:0] tmp_1_fu_254_p11;
wire  signed [2:0] tmp_1_fu_254_p13;
wire  signed [2:0] tmp_1_fu_254_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 i_1_fu_70 = 4'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) gelu_embed_kernel_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U261(
    .din0(embed_lut_0_q0),
    .din1(embed_lut_1_q0),
    .din2(embed_lut_2_q0),
    .din3(embed_lut_3_q0),
    .din4(embed_lut_4_q0),
    .din5(embed_lut_5_q0),
    .din6(embed_lut_6_q0),
    .din7(embed_lut_7_q0),
    .def(tmp_1_fu_254_p17),
    .sel(trunc_ln13_reg_310_pp0_iter1_reg),
    .dout(tmp_1_fu_254_p19)
);

gelu_embed_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln13_fu_212_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_1_fu_70 <= add_ln13_fu_218_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_1_fu_70 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        trunc_ln13_reg_310 <= trunc_ln13_fu_229_p1;
        trunc_ln13_reg_310_pp0_iter1_reg <= trunc_ln13_reg_310;
        zext_ln13_reg_305[3 : 0] <= zext_ln13_fu_224_p1[3 : 0];
        zext_ln13_reg_305_pp0_iter1_reg[3 : 0] <= zext_ln13_reg_305[3 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln13_fu_212_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i = 4'd0;
    end else begin
        ap_sig_allocacmp_i = i_1_fu_70;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        embed_lut_0_ce0_local = 1'b1;
    end else begin
        embed_lut_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        embed_lut_1_ce0_local = 1'b1;
    end else begin
        embed_lut_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        embed_lut_2_ce0_local = 1'b1;
    end else begin
        embed_lut_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        embed_lut_3_ce0_local = 1'b1;
    end else begin
        embed_lut_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        embed_lut_4_ce0_local = 1'b1;
    end else begin
        embed_lut_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        embed_lut_5_ce0_local = 1'b1;
    end else begin
        embed_lut_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        embed_lut_6_ce0_local = 1'b1;
    end else begin
        embed_lut_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        embed_lut_7_ce0_local = 1'b1;
    end else begin
        embed_lut_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        embed_out_ce0_local = 1'b1;
    end else begin
        embed_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        embed_out_we0_local = 1'b1;
    end else begin
        embed_out_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        token_ids_ce0_local = 1'b1;
    end else begin
        token_ids_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln13_fu_218_p2 = (ap_sig_allocacmp_i + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign embed_lut_0_address0 = zext_ln15_fu_242_p1;

assign embed_lut_0_ce0 = embed_lut_0_ce0_local;

assign embed_lut_1_address0 = zext_ln15_fu_242_p1;

assign embed_lut_1_ce0 = embed_lut_1_ce0_local;

assign embed_lut_2_address0 = zext_ln15_fu_242_p1;

assign embed_lut_2_ce0 = embed_lut_2_ce0_local;

assign embed_lut_3_address0 = zext_ln15_fu_242_p1;

assign embed_lut_3_ce0 = embed_lut_3_ce0_local;

assign embed_lut_4_address0 = zext_ln15_fu_242_p1;

assign embed_lut_4_ce0 = embed_lut_4_ce0_local;

assign embed_lut_5_address0 = zext_ln15_fu_242_p1;

assign embed_lut_5_ce0 = embed_lut_5_ce0_local;

assign embed_lut_6_address0 = zext_ln15_fu_242_p1;

assign embed_lut_6_ce0 = embed_lut_6_ce0_local;

assign embed_lut_7_address0 = zext_ln15_fu_242_p1;

assign embed_lut_7_ce0 = embed_lut_7_ce0_local;

assign embed_out_address0 = zext_ln13_reg_305_pp0_iter1_reg;

assign embed_out_ce0 = embed_out_ce0_local;

assign embed_out_d0 = tmp_1_fu_254_p19;

assign embed_out_we0 = embed_out_we0_local;

assign icmp_ln13_fu_212_p2 = ((ap_sig_allocacmp_i == 4'd8) ? 1'b1 : 1'b0);

assign tmp_1_fu_254_p17 = 'bx;

assign token_ids_address0 = zext_ln13_fu_224_p1;

assign token_ids_ce0 = token_ids_ce0_local;

assign trunc_ln13_fu_229_p1 = ap_sig_allocacmp_i[2:0];

assign trunc_ln15_fu_238_p1 = token_ids_q0[4:0];

assign zext_ln13_fu_224_p1 = ap_sig_allocacmp_i;

assign zext_ln15_fu_242_p1 = trunc_ln15_fu_238_p1;

always @ (posedge ap_clk) begin
    zext_ln13_reg_305[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln13_reg_305_pp0_iter1_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //gelu_embed_kernel_gelu_embed_kernel_Pipeline_embed
