-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity tiled_matmul_kernel_tiled_matmul_kernel_Pipeline_dot is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    A_0_load : IN STD_LOGIC_VECTOR (7 downto 0);
    A_1_load : IN STD_LOGIC_VECTOR (7 downto 0);
    A_2_load : IN STD_LOGIC_VECTOR (7 downto 0);
    A_3_load : IN STD_LOGIC_VECTOR (7 downto 0);
    A_4_load : IN STD_LOGIC_VECTOR (7 downto 0);
    A_5_load : IN STD_LOGIC_VECTOR (7 downto 0);
    A_6_load : IN STD_LOGIC_VECTOR (7 downto 0);
    A_7_load : IN STD_LOGIC_VECTOR (7 downto 0);
    A_8_load : IN STD_LOGIC_VECTOR (7 downto 0);
    A_9_load : IN STD_LOGIC_VECTOR (7 downto 0);
    A_10_load : IN STD_LOGIC_VECTOR (7 downto 0);
    A_11_load : IN STD_LOGIC_VECTOR (7 downto 0);
    A_12_load : IN STD_LOGIC_VECTOR (7 downto 0);
    A_13_load : IN STD_LOGIC_VECTOR (7 downto 0);
    A_14_load : IN STD_LOGIC_VECTOR (7 downto 0);
    A_15_load : IN STD_LOGIC_VECTOR (7 downto 0);
    B_0_load : IN STD_LOGIC_VECTOR (7 downto 0);
    B_1_load : IN STD_LOGIC_VECTOR (7 downto 0);
    B_2_load : IN STD_LOGIC_VECTOR (7 downto 0);
    B_3_load : IN STD_LOGIC_VECTOR (7 downto 0);
    B_4_load : IN STD_LOGIC_VECTOR (7 downto 0);
    B_5_load : IN STD_LOGIC_VECTOR (7 downto 0);
    B_6_load : IN STD_LOGIC_VECTOR (7 downto 0);
    B_7_load : IN STD_LOGIC_VECTOR (7 downto 0);
    B_8_load : IN STD_LOGIC_VECTOR (7 downto 0);
    B_9_load : IN STD_LOGIC_VECTOR (7 downto 0);
    B_10_load : IN STD_LOGIC_VECTOR (7 downto 0);
    B_11_load : IN STD_LOGIC_VECTOR (7 downto 0);
    B_12_load : IN STD_LOGIC_VECTOR (7 downto 0);
    B_13_load : IN STD_LOGIC_VECTOR (7 downto 0);
    B_14_load : IN STD_LOGIC_VECTOR (7 downto 0);
    B_15_load : IN STD_LOGIC_VECTOR (7 downto 0);
    B_0_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_1_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_2_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_3_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_4_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_5_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_6_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_7_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_8_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_9_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_10_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_11_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_12_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_13_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_14_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_15_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_0_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_1_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_2_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_3_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_4_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_5_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_6_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_7_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_8_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_9_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_10_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_11_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_12_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_13_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_14_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_15_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_0_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_1_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_2_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_3_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_4_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_5_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_6_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_7_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_8_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_9_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_10_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_11_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_12_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_13_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_14_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_15_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_0_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_1_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_2_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_3_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_4_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_5_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_6_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_7_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_8_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_9_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_10_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_11_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_12_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_13_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_14_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_15_load_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_0_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_1_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_2_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_3_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_4_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_5_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_6_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_7_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_8_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_9_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_10_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_11_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_12_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_13_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_14_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_15_load_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_0_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_1_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_2_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_3_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_4_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_5_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_6_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_7_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_8_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_9_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_10_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_11_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_12_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_13_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_14_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    A_15_load_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    add_i_3_374_out : OUT STD_LOGIC_VECTOR (19 downto 0);
    add_i_3_374_out_ap_vld : OUT STD_LOGIC;
    add_i_3_273_out : OUT STD_LOGIC_VECTOR (19 downto 0);
    add_i_3_273_out_ap_vld : OUT STD_LOGIC;
    add_i_3_172_out : OUT STD_LOGIC_VECTOR (19 downto 0);
    add_i_3_172_out_ap_vld : OUT STD_LOGIC;
    add_i_371_out : OUT STD_LOGIC_VECTOR (19 downto 0);
    add_i_371_out_ap_vld : OUT STD_LOGIC;
    add_i_2_370_out : OUT STD_LOGIC_VECTOR (19 downto 0);
    add_i_2_370_out_ap_vld : OUT STD_LOGIC;
    add_i_2_269_out : OUT STD_LOGIC_VECTOR (19 downto 0);
    add_i_2_269_out_ap_vld : OUT STD_LOGIC;
    add_i_2_168_out : OUT STD_LOGIC_VECTOR (19 downto 0);
    add_i_2_168_out_ap_vld : OUT STD_LOGIC;
    add_i_267_out : OUT STD_LOGIC_VECTOR (19 downto 0);
    add_i_267_out_ap_vld : OUT STD_LOGIC;
    add_i_1_366_out : OUT STD_LOGIC_VECTOR (19 downto 0);
    add_i_1_366_out_ap_vld : OUT STD_LOGIC;
    add_i_1_265_out : OUT STD_LOGIC_VECTOR (19 downto 0);
    add_i_1_265_out_ap_vld : OUT STD_LOGIC;
    add_i_1_164_out : OUT STD_LOGIC_VECTOR (19 downto 0);
    add_i_1_164_out_ap_vld : OUT STD_LOGIC;
    add_i_163_out : OUT STD_LOGIC_VECTOR (19 downto 0);
    add_i_163_out_ap_vld : OUT STD_LOGIC;
    add_i_35762_out : OUT STD_LOGIC_VECTOR (19 downto 0);
    add_i_35762_out_ap_vld : OUT STD_LOGIC;
    add_i_24961_out : OUT STD_LOGIC_VECTOR (19 downto 0);
    add_i_24961_out_ap_vld : OUT STD_LOGIC;
    add_i_14160_out : OUT STD_LOGIC_VECTOR (19 downto 0);
    add_i_14160_out_ap_vld : OUT STD_LOGIC;
    add_i59_out : OUT STD_LOGIC_VECTOR (19 downto 0);
    add_i59_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of tiled_matmul_kernel_tiled_matmul_kernel_Pipeline_dot is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln22_fu_1390_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln22_reg_2474 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln22_reg_2474_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln27_fu_1478_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln27_1_fu_1554_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln27_3_fu_1630_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln27_5_fu_1706_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln27_7_fu_1782_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln27_9_fu_1858_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln27_14_fu_1934_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln27_19_fu_2010_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_i59_fu_354 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    signal grp_fu_2195_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_sig_allocacmp_add_i59_load : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_loop_init : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal add_i_14160_fu_358 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    signal grp_fu_2204_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_sig_allocacmp_add_i_14160_load : STD_LOGIC_VECTOR (19 downto 0);
    signal add_i_24961_fu_362 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    signal grp_fu_2213_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_sig_allocacmp_add_i_24961_load : STD_LOGIC_VECTOR (19 downto 0);
    signal add_i_35762_fu_366 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    signal grp_fu_2222_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_sig_allocacmp_add_i_35762_load : STD_LOGIC_VECTOR (19 downto 0);
    signal add_i_163_fu_370 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    signal grp_fu_2231_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_sig_allocacmp_add_i_163_load : STD_LOGIC_VECTOR (19 downto 0);
    signal add_i_1_164_fu_374 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    signal grp_fu_2240_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_sig_allocacmp_add_i_1_164_load : STD_LOGIC_VECTOR (19 downto 0);
    signal add_i_1_265_fu_378 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    signal grp_fu_2249_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_sig_allocacmp_add_i_1_265_load : STD_LOGIC_VECTOR (19 downto 0);
    signal add_i_1_366_fu_382 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    signal grp_fu_2258_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_sig_allocacmp_add_i_1_366_load : STD_LOGIC_VECTOR (19 downto 0);
    signal add_i_267_fu_386 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    signal grp_fu_2267_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_sig_allocacmp_add_i_267_load : STD_LOGIC_VECTOR (19 downto 0);
    signal add_i_2_168_fu_390 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    signal grp_fu_2276_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_sig_allocacmp_add_i_2_168_load : STD_LOGIC_VECTOR (19 downto 0);
    signal add_i_2_269_fu_394 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    signal grp_fu_2285_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_sig_allocacmp_add_i_2_269_load : STD_LOGIC_VECTOR (19 downto 0);
    signal add_i_2_370_fu_398 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    signal grp_fu_2294_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_sig_allocacmp_add_i_2_370_load : STD_LOGIC_VECTOR (19 downto 0);
    signal add_i_371_fu_402 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    signal grp_fu_2303_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_sig_allocacmp_add_i_371_load : STD_LOGIC_VECTOR (19 downto 0);
    signal add_i_3_172_fu_406 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    signal grp_fu_2312_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_sig_allocacmp_add_i_3_172_load : STD_LOGIC_VECTOR (19 downto 0);
    signal add_i_3_273_fu_410 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    signal grp_fu_2321_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_sig_allocacmp_add_i_3_273_load : STD_LOGIC_VECTOR (19 downto 0);
    signal add_i_3_374_fu_414 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    signal grp_fu_2330_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_sig_allocacmp_add_i_3_374_load : STD_LOGIC_VECTOR (19 downto 0);
    signal k_fu_418 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln22_fu_1396_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_k_1 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_fu_1406_p33 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln22_fu_1402_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_1406_p35 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_fu_1482_p33 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_fu_1482_p35 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_1558_p33 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_1558_p35 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_1634_p33 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_1634_p35 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_fu_1710_p33 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_fu_1710_p35 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_fu_1786_p33 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_fu_1786_p35 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_fu_1862_p33 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_fu_1862_p35 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_7_fu_1938_p33 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_7_fu_1938_p35 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2195_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2195_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2204_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2204_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2213_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2213_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2222_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2222_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2231_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2231_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2240_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2240_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2249_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2249_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2258_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2258_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2267_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2267_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2276_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2276_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2285_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2285_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2294_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2294_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2303_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2303_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2312_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2312_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2321_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2321_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2330_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2330_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_fu_1406_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_1406_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_1406_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_1406_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_1406_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_1406_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_1406_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_1406_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_1406_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_1406_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_1406_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_1406_p23 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_1406_p25 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_1406_p27 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_1406_p29 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_1406_p31 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1482_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1482_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1482_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1482_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1482_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1482_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1482_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1482_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1482_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1482_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1482_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1482_p23 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1482_p25 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1482_p27 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1482_p29 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1482_p31 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_1558_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_1558_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_1558_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_1558_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_1558_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_1558_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_1558_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_1558_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_1558_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_1558_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_1558_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_1558_p23 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_1558_p25 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_1558_p27 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_1558_p29 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_1558_p31 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_fu_1634_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_fu_1634_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_fu_1634_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_fu_1634_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_fu_1634_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_fu_1634_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_fu_1634_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_fu_1634_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_fu_1634_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_fu_1634_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_fu_1634_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_fu_1634_p23 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_fu_1634_p25 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_fu_1634_p27 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_fu_1634_p29 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_fu_1634_p31 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_1710_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_1710_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_1710_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_1710_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_1710_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_1710_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_1710_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_1710_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_1710_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_1710_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_1710_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_1710_p23 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_1710_p25 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_1710_p27 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_1710_p29 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_1710_p31 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_1786_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_1786_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_1786_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_1786_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_1786_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_1786_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_1786_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_1786_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_1786_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_1786_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_1786_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_1786_p23 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_1786_p25 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_1786_p27 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_1786_p29 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_1786_p31 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_6_fu_1862_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_6_fu_1862_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_6_fu_1862_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_6_fu_1862_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_6_fu_1862_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_6_fu_1862_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_6_fu_1862_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_6_fu_1862_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_6_fu_1862_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_6_fu_1862_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_6_fu_1862_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_6_fu_1862_p23 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_6_fu_1862_p25 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_6_fu_1862_p27 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_6_fu_1862_p29 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_6_fu_1862_p31 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_7_fu_1938_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_7_fu_1938_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_7_fu_1938_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_7_fu_1938_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_7_fu_1938_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_7_fu_1938_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_7_fu_1938_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_7_fu_1938_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_7_fu_1938_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_7_fu_1938_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_7_fu_1938_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_7_fu_1938_p23 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_7_fu_1938_p25 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_7_fu_1938_p27 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_7_fu_1938_p29 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_7_fu_1938_p31 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component tiled_matmul_kernel_sparsemux_33_4_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (3 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (3 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (3 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (3 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (3 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (3 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (3 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (3 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (3 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (3 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (3 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (3 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (3 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (3 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (3 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (3 downto 0);
        din15_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        din4 : IN STD_LOGIC_VECTOR (7 downto 0);
        din5 : IN STD_LOGIC_VECTOR (7 downto 0);
        din6 : IN STD_LOGIC_VECTOR (7 downto 0);
        din7 : IN STD_LOGIC_VECTOR (7 downto 0);
        din8 : IN STD_LOGIC_VECTOR (7 downto 0);
        din9 : IN STD_LOGIC_VECTOR (7 downto 0);
        din10 : IN STD_LOGIC_VECTOR (7 downto 0);
        din11 : IN STD_LOGIC_VECTOR (7 downto 0);
        din12 : IN STD_LOGIC_VECTOR (7 downto 0);
        din13 : IN STD_LOGIC_VECTOR (7 downto 0);
        din14 : IN STD_LOGIC_VECTOR (7 downto 0);
        din15 : IN STD_LOGIC_VECTOR (7 downto 0);
        def : IN STD_LOGIC_VECTOR (7 downto 0);
        sel : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component tiled_matmul_kernel_mac_muladd_8s_8s_20s_20_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (19 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (19 downto 0) );
    end component;


    component tiled_matmul_kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_33_4_8_1_1_U1 : component tiled_matmul_kernel_sparsemux_33_4_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 8,
        CASE1 => "0001",
        din1_WIDTH => 8,
        CASE2 => "0010",
        din2_WIDTH => 8,
        CASE3 => "0011",
        din3_WIDTH => 8,
        CASE4 => "0100",
        din4_WIDTH => 8,
        CASE5 => "0101",
        din5_WIDTH => 8,
        CASE6 => "0110",
        din6_WIDTH => 8,
        CASE7 => "0111",
        din7_WIDTH => 8,
        CASE8 => "1000",
        din8_WIDTH => 8,
        CASE9 => "1001",
        din9_WIDTH => 8,
        CASE10 => "1010",
        din10_WIDTH => 8,
        CASE11 => "1011",
        din11_WIDTH => 8,
        CASE12 => "1100",
        din12_WIDTH => 8,
        CASE13 => "1101",
        din13_WIDTH => 8,
        CASE14 => "1110",
        din14_WIDTH => 8,
        CASE15 => "1111",
        din15_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        din0 => A_0_load,
        din1 => A_1_load,
        din2 => A_2_load,
        din3 => A_3_load,
        din4 => A_4_load,
        din5 => A_5_load,
        din6 => A_6_load,
        din7 => A_7_load,
        din8 => A_8_load,
        din9 => A_9_load,
        din10 => A_10_load,
        din11 => A_11_load,
        din12 => A_12_load,
        din13 => A_13_load,
        din14 => A_14_load,
        din15 => A_15_load,
        def => tmp_fu_1406_p33,
        sel => trunc_ln22_fu_1402_p1,
        dout => tmp_fu_1406_p35);

    sparsemux_33_4_8_1_1_U2 : component tiled_matmul_kernel_sparsemux_33_4_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 8,
        CASE1 => "0001",
        din1_WIDTH => 8,
        CASE2 => "0010",
        din2_WIDTH => 8,
        CASE3 => "0011",
        din3_WIDTH => 8,
        CASE4 => "0100",
        din4_WIDTH => 8,
        CASE5 => "0101",
        din5_WIDTH => 8,
        CASE6 => "0110",
        din6_WIDTH => 8,
        CASE7 => "0111",
        din7_WIDTH => 8,
        CASE8 => "1000",
        din8_WIDTH => 8,
        CASE9 => "1001",
        din9_WIDTH => 8,
        CASE10 => "1010",
        din10_WIDTH => 8,
        CASE11 => "1011",
        din11_WIDTH => 8,
        CASE12 => "1100",
        din12_WIDTH => 8,
        CASE13 => "1101",
        din13_WIDTH => 8,
        CASE14 => "1110",
        din14_WIDTH => 8,
        CASE15 => "1111",
        din15_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        din0 => B_0_load,
        din1 => B_1_load,
        din2 => B_2_load,
        din3 => B_3_load,
        din4 => B_4_load,
        din5 => B_5_load,
        din6 => B_6_load,
        din7 => B_7_load,
        din8 => B_8_load,
        din9 => B_9_load,
        din10 => B_10_load,
        din11 => B_11_load,
        din12 => B_12_load,
        din13 => B_13_load,
        din14 => B_14_load,
        din15 => B_15_load,
        def => tmp_1_fu_1482_p33,
        sel => trunc_ln22_fu_1402_p1,
        dout => tmp_1_fu_1482_p35);

    sparsemux_33_4_8_1_1_U3 : component tiled_matmul_kernel_sparsemux_33_4_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 8,
        CASE1 => "0001",
        din1_WIDTH => 8,
        CASE2 => "0010",
        din2_WIDTH => 8,
        CASE3 => "0011",
        din3_WIDTH => 8,
        CASE4 => "0100",
        din4_WIDTH => 8,
        CASE5 => "0101",
        din5_WIDTH => 8,
        CASE6 => "0110",
        din6_WIDTH => 8,
        CASE7 => "0111",
        din7_WIDTH => 8,
        CASE8 => "1000",
        din8_WIDTH => 8,
        CASE9 => "1001",
        din9_WIDTH => 8,
        CASE10 => "1010",
        din10_WIDTH => 8,
        CASE11 => "1011",
        din11_WIDTH => 8,
        CASE12 => "1100",
        din12_WIDTH => 8,
        CASE13 => "1101",
        din13_WIDTH => 8,
        CASE14 => "1110",
        din14_WIDTH => 8,
        CASE15 => "1111",
        din15_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        din0 => B_0_load_1,
        din1 => B_1_load_1,
        din2 => B_2_load_1,
        din3 => B_3_load_1,
        din4 => B_4_load_1,
        din5 => B_5_load_1,
        din6 => B_6_load_1,
        din7 => B_7_load_1,
        din8 => B_8_load_1,
        din9 => B_9_load_1,
        din10 => B_10_load_1,
        din11 => B_11_load_1,
        din12 => B_12_load_1,
        din13 => B_13_load_1,
        din14 => B_14_load_1,
        din15 => B_15_load_1,
        def => tmp_2_fu_1558_p33,
        sel => trunc_ln22_fu_1402_p1,
        dout => tmp_2_fu_1558_p35);

    sparsemux_33_4_8_1_1_U4 : component tiled_matmul_kernel_sparsemux_33_4_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 8,
        CASE1 => "0001",
        din1_WIDTH => 8,
        CASE2 => "0010",
        din2_WIDTH => 8,
        CASE3 => "0011",
        din3_WIDTH => 8,
        CASE4 => "0100",
        din4_WIDTH => 8,
        CASE5 => "0101",
        din5_WIDTH => 8,
        CASE6 => "0110",
        din6_WIDTH => 8,
        CASE7 => "0111",
        din7_WIDTH => 8,
        CASE8 => "1000",
        din8_WIDTH => 8,
        CASE9 => "1001",
        din9_WIDTH => 8,
        CASE10 => "1010",
        din10_WIDTH => 8,
        CASE11 => "1011",
        din11_WIDTH => 8,
        CASE12 => "1100",
        din12_WIDTH => 8,
        CASE13 => "1101",
        din13_WIDTH => 8,
        CASE14 => "1110",
        din14_WIDTH => 8,
        CASE15 => "1111",
        din15_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        din0 => B_0_load_2,
        din1 => B_1_load_2,
        din2 => B_2_load_2,
        din3 => B_3_load_2,
        din4 => B_4_load_2,
        din5 => B_5_load_2,
        din6 => B_6_load_2,
        din7 => B_7_load_2,
        din8 => B_8_load_2,
        din9 => B_9_load_2,
        din10 => B_10_load_2,
        din11 => B_11_load_2,
        din12 => B_12_load_2,
        din13 => B_13_load_2,
        din14 => B_14_load_2,
        din15 => B_15_load_2,
        def => tmp_3_fu_1634_p33,
        sel => trunc_ln22_fu_1402_p1,
        dout => tmp_3_fu_1634_p35);

    sparsemux_33_4_8_1_1_U5 : component tiled_matmul_kernel_sparsemux_33_4_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 8,
        CASE1 => "0001",
        din1_WIDTH => 8,
        CASE2 => "0010",
        din2_WIDTH => 8,
        CASE3 => "0011",
        din3_WIDTH => 8,
        CASE4 => "0100",
        din4_WIDTH => 8,
        CASE5 => "0101",
        din5_WIDTH => 8,
        CASE6 => "0110",
        din6_WIDTH => 8,
        CASE7 => "0111",
        din7_WIDTH => 8,
        CASE8 => "1000",
        din8_WIDTH => 8,
        CASE9 => "1001",
        din9_WIDTH => 8,
        CASE10 => "1010",
        din10_WIDTH => 8,
        CASE11 => "1011",
        din11_WIDTH => 8,
        CASE12 => "1100",
        din12_WIDTH => 8,
        CASE13 => "1101",
        din13_WIDTH => 8,
        CASE14 => "1110",
        din14_WIDTH => 8,
        CASE15 => "1111",
        din15_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        din0 => B_0_load_3,
        din1 => B_1_load_3,
        din2 => B_2_load_3,
        din3 => B_3_load_3,
        din4 => B_4_load_3,
        din5 => B_5_load_3,
        din6 => B_6_load_3,
        din7 => B_7_load_3,
        din8 => B_8_load_3,
        din9 => B_9_load_3,
        din10 => B_10_load_3,
        din11 => B_11_load_3,
        din12 => B_12_load_3,
        din13 => B_13_load_3,
        din14 => B_14_load_3,
        din15 => B_15_load_3,
        def => tmp_4_fu_1710_p33,
        sel => trunc_ln22_fu_1402_p1,
        dout => tmp_4_fu_1710_p35);

    sparsemux_33_4_8_1_1_U6 : component tiled_matmul_kernel_sparsemux_33_4_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 8,
        CASE1 => "0001",
        din1_WIDTH => 8,
        CASE2 => "0010",
        din2_WIDTH => 8,
        CASE3 => "0011",
        din3_WIDTH => 8,
        CASE4 => "0100",
        din4_WIDTH => 8,
        CASE5 => "0101",
        din5_WIDTH => 8,
        CASE6 => "0110",
        din6_WIDTH => 8,
        CASE7 => "0111",
        din7_WIDTH => 8,
        CASE8 => "1000",
        din8_WIDTH => 8,
        CASE9 => "1001",
        din9_WIDTH => 8,
        CASE10 => "1010",
        din10_WIDTH => 8,
        CASE11 => "1011",
        din11_WIDTH => 8,
        CASE12 => "1100",
        din12_WIDTH => 8,
        CASE13 => "1101",
        din13_WIDTH => 8,
        CASE14 => "1110",
        din14_WIDTH => 8,
        CASE15 => "1111",
        din15_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        din0 => A_0_load_1,
        din1 => A_1_load_1,
        din2 => A_2_load_1,
        din3 => A_3_load_1,
        din4 => A_4_load_1,
        din5 => A_5_load_1,
        din6 => A_6_load_1,
        din7 => A_7_load_1,
        din8 => A_8_load_1,
        din9 => A_9_load_1,
        din10 => A_10_load_1,
        din11 => A_11_load_1,
        din12 => A_12_load_1,
        din13 => A_13_load_1,
        din14 => A_14_load_1,
        din15 => A_15_load_1,
        def => tmp_5_fu_1786_p33,
        sel => trunc_ln22_fu_1402_p1,
        dout => tmp_5_fu_1786_p35);

    sparsemux_33_4_8_1_1_U7 : component tiled_matmul_kernel_sparsemux_33_4_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 8,
        CASE1 => "0001",
        din1_WIDTH => 8,
        CASE2 => "0010",
        din2_WIDTH => 8,
        CASE3 => "0011",
        din3_WIDTH => 8,
        CASE4 => "0100",
        din4_WIDTH => 8,
        CASE5 => "0101",
        din5_WIDTH => 8,
        CASE6 => "0110",
        din6_WIDTH => 8,
        CASE7 => "0111",
        din7_WIDTH => 8,
        CASE8 => "1000",
        din8_WIDTH => 8,
        CASE9 => "1001",
        din9_WIDTH => 8,
        CASE10 => "1010",
        din10_WIDTH => 8,
        CASE11 => "1011",
        din11_WIDTH => 8,
        CASE12 => "1100",
        din12_WIDTH => 8,
        CASE13 => "1101",
        din13_WIDTH => 8,
        CASE14 => "1110",
        din14_WIDTH => 8,
        CASE15 => "1111",
        din15_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        din0 => A_0_load_2,
        din1 => A_1_load_2,
        din2 => A_2_load_2,
        din3 => A_3_load_2,
        din4 => A_4_load_2,
        din5 => A_5_load_2,
        din6 => A_6_load_2,
        din7 => A_7_load_2,
        din8 => A_8_load_2,
        din9 => A_9_load_2,
        din10 => A_10_load_2,
        din11 => A_11_load_2,
        din12 => A_12_load_2,
        din13 => A_13_load_2,
        din14 => A_14_load_2,
        din15 => A_15_load_2,
        def => tmp_6_fu_1862_p33,
        sel => trunc_ln22_fu_1402_p1,
        dout => tmp_6_fu_1862_p35);

    sparsemux_33_4_8_1_1_U8 : component tiled_matmul_kernel_sparsemux_33_4_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 8,
        CASE1 => "0001",
        din1_WIDTH => 8,
        CASE2 => "0010",
        din2_WIDTH => 8,
        CASE3 => "0011",
        din3_WIDTH => 8,
        CASE4 => "0100",
        din4_WIDTH => 8,
        CASE5 => "0101",
        din5_WIDTH => 8,
        CASE6 => "0110",
        din6_WIDTH => 8,
        CASE7 => "0111",
        din7_WIDTH => 8,
        CASE8 => "1000",
        din8_WIDTH => 8,
        CASE9 => "1001",
        din9_WIDTH => 8,
        CASE10 => "1010",
        din10_WIDTH => 8,
        CASE11 => "1011",
        din11_WIDTH => 8,
        CASE12 => "1100",
        din12_WIDTH => 8,
        CASE13 => "1101",
        din13_WIDTH => 8,
        CASE14 => "1110",
        din14_WIDTH => 8,
        CASE15 => "1111",
        din15_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        din0 => A_0_load_3,
        din1 => A_1_load_3,
        din2 => A_2_load_3,
        din3 => A_3_load_3,
        din4 => A_4_load_3,
        din5 => A_5_load_3,
        din6 => A_6_load_3,
        din7 => A_7_load_3,
        din8 => A_8_load_3,
        din9 => A_9_load_3,
        din10 => A_10_load_3,
        din11 => A_11_load_3,
        din12 => A_12_load_3,
        din13 => A_13_load_3,
        din14 => A_14_load_3,
        din15 => A_15_load_3,
        def => tmp_7_fu_1938_p33,
        sel => trunc_ln22_fu_1402_p1,
        dout => tmp_7_fu_1938_p35);

    mac_muladd_8s_8s_20s_20_4_1_U9 : component tiled_matmul_kernel_mac_muladd_8s_8s_20s_20_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 20,
        dout_WIDTH => 20)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_2195_p0,
        din1 => grp_fu_2195_p1,
        din2 => ap_sig_allocacmp_add_i59_load,
        ce => ap_const_logic_1,
        dout => grp_fu_2195_p3);

    mac_muladd_8s_8s_20s_20_4_1_U10 : component tiled_matmul_kernel_mac_muladd_8s_8s_20s_20_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 20,
        dout_WIDTH => 20)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_2204_p0,
        din1 => grp_fu_2204_p1,
        din2 => ap_sig_allocacmp_add_i_14160_load,
        ce => ap_const_logic_1,
        dout => grp_fu_2204_p3);

    mac_muladd_8s_8s_20s_20_4_1_U11 : component tiled_matmul_kernel_mac_muladd_8s_8s_20s_20_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 20,
        dout_WIDTH => 20)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_2213_p0,
        din1 => grp_fu_2213_p1,
        din2 => ap_sig_allocacmp_add_i_24961_load,
        ce => ap_const_logic_1,
        dout => grp_fu_2213_p3);

    mac_muladd_8s_8s_20s_20_4_1_U12 : component tiled_matmul_kernel_mac_muladd_8s_8s_20s_20_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 20,
        dout_WIDTH => 20)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_2222_p0,
        din1 => grp_fu_2222_p1,
        din2 => ap_sig_allocacmp_add_i_35762_load,
        ce => ap_const_logic_1,
        dout => grp_fu_2222_p3);

    mac_muladd_8s_8s_20s_20_4_1_U13 : component tiled_matmul_kernel_mac_muladd_8s_8s_20s_20_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 20,
        dout_WIDTH => 20)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_2231_p0,
        din1 => grp_fu_2231_p1,
        din2 => ap_sig_allocacmp_add_i_163_load,
        ce => ap_const_logic_1,
        dout => grp_fu_2231_p3);

    mac_muladd_8s_8s_20s_20_4_1_U14 : component tiled_matmul_kernel_mac_muladd_8s_8s_20s_20_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 20,
        dout_WIDTH => 20)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_2240_p0,
        din1 => grp_fu_2240_p1,
        din2 => ap_sig_allocacmp_add_i_1_164_load,
        ce => ap_const_logic_1,
        dout => grp_fu_2240_p3);

    mac_muladd_8s_8s_20s_20_4_1_U15 : component tiled_matmul_kernel_mac_muladd_8s_8s_20s_20_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 20,
        dout_WIDTH => 20)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_2249_p0,
        din1 => grp_fu_2249_p1,
        din2 => ap_sig_allocacmp_add_i_1_265_load,
        ce => ap_const_logic_1,
        dout => grp_fu_2249_p3);

    mac_muladd_8s_8s_20s_20_4_1_U16 : component tiled_matmul_kernel_mac_muladd_8s_8s_20s_20_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 20,
        dout_WIDTH => 20)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_2258_p0,
        din1 => grp_fu_2258_p1,
        din2 => ap_sig_allocacmp_add_i_1_366_load,
        ce => ap_const_logic_1,
        dout => grp_fu_2258_p3);

    mac_muladd_8s_8s_20s_20_4_1_U17 : component tiled_matmul_kernel_mac_muladd_8s_8s_20s_20_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 20,
        dout_WIDTH => 20)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_2267_p0,
        din1 => grp_fu_2267_p1,
        din2 => ap_sig_allocacmp_add_i_267_load,
        ce => ap_const_logic_1,
        dout => grp_fu_2267_p3);

    mac_muladd_8s_8s_20s_20_4_1_U18 : component tiled_matmul_kernel_mac_muladd_8s_8s_20s_20_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 20,
        dout_WIDTH => 20)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_2276_p0,
        din1 => grp_fu_2276_p1,
        din2 => ap_sig_allocacmp_add_i_2_168_load,
        ce => ap_const_logic_1,
        dout => grp_fu_2276_p3);

    mac_muladd_8s_8s_20s_20_4_1_U19 : component tiled_matmul_kernel_mac_muladd_8s_8s_20s_20_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 20,
        dout_WIDTH => 20)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_2285_p0,
        din1 => grp_fu_2285_p1,
        din2 => ap_sig_allocacmp_add_i_2_269_load,
        ce => ap_const_logic_1,
        dout => grp_fu_2285_p3);

    mac_muladd_8s_8s_20s_20_4_1_U20 : component tiled_matmul_kernel_mac_muladd_8s_8s_20s_20_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 20,
        dout_WIDTH => 20)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_2294_p0,
        din1 => grp_fu_2294_p1,
        din2 => ap_sig_allocacmp_add_i_2_370_load,
        ce => ap_const_logic_1,
        dout => grp_fu_2294_p3);

    mac_muladd_8s_8s_20s_20_4_1_U21 : component tiled_matmul_kernel_mac_muladd_8s_8s_20s_20_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 20,
        dout_WIDTH => 20)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_2303_p0,
        din1 => grp_fu_2303_p1,
        din2 => ap_sig_allocacmp_add_i_371_load,
        ce => ap_const_logic_1,
        dout => grp_fu_2303_p3);

    mac_muladd_8s_8s_20s_20_4_1_U22 : component tiled_matmul_kernel_mac_muladd_8s_8s_20s_20_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 20,
        dout_WIDTH => 20)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_2312_p0,
        din1 => grp_fu_2312_p1,
        din2 => ap_sig_allocacmp_add_i_3_172_load,
        ce => ap_const_logic_1,
        dout => grp_fu_2312_p3);

    mac_muladd_8s_8s_20s_20_4_1_U23 : component tiled_matmul_kernel_mac_muladd_8s_8s_20s_20_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 20,
        dout_WIDTH => 20)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_2321_p0,
        din1 => grp_fu_2321_p1,
        din2 => ap_sig_allocacmp_add_i_3_273_load,
        ce => ap_const_logic_1,
        dout => grp_fu_2321_p3);

    mac_muladd_8s_8s_20s_20_4_1_U24 : component tiled_matmul_kernel_mac_muladd_8s_8s_20s_20_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 20,
        dout_WIDTH => 20)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_2330_p0,
        din1 => grp_fu_2330_p1,
        din2 => ap_sig_allocacmp_add_i_3_374_load,
        ce => ap_const_logic_1,
        dout => grp_fu_2330_p3);

    flow_control_loop_pipe_sequential_init_U : component tiled_matmul_kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    add_i59_fu_354_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    add_i59_fu_354 <= ap_const_lv20_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    add_i59_fu_354 <= grp_fu_2195_p3;
                end if;
            end if; 
        end if;
    end process;

    add_i_14160_fu_358_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    add_i_14160_fu_358 <= ap_const_lv20_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    add_i_14160_fu_358 <= grp_fu_2204_p3;
                end if;
            end if; 
        end if;
    end process;

    add_i_163_fu_370_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    add_i_163_fu_370 <= ap_const_lv20_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    add_i_163_fu_370 <= grp_fu_2231_p3;
                end if;
            end if; 
        end if;
    end process;

    add_i_1_164_fu_374_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    add_i_1_164_fu_374 <= ap_const_lv20_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    add_i_1_164_fu_374 <= grp_fu_2240_p3;
                end if;
            end if; 
        end if;
    end process;

    add_i_1_265_fu_378_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    add_i_1_265_fu_378 <= ap_const_lv20_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    add_i_1_265_fu_378 <= grp_fu_2249_p3;
                end if;
            end if; 
        end if;
    end process;

    add_i_1_366_fu_382_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    add_i_1_366_fu_382 <= ap_const_lv20_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    add_i_1_366_fu_382 <= grp_fu_2258_p3;
                end if;
            end if; 
        end if;
    end process;

    add_i_24961_fu_362_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    add_i_24961_fu_362 <= ap_const_lv20_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    add_i_24961_fu_362 <= grp_fu_2213_p3;
                end if;
            end if; 
        end if;
    end process;

    add_i_267_fu_386_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    add_i_267_fu_386 <= ap_const_lv20_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    add_i_267_fu_386 <= grp_fu_2267_p3;
                end if;
            end if; 
        end if;
    end process;

    add_i_2_168_fu_390_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    add_i_2_168_fu_390 <= ap_const_lv20_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    add_i_2_168_fu_390 <= grp_fu_2276_p3;
                end if;
            end if; 
        end if;
    end process;

    add_i_2_269_fu_394_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    add_i_2_269_fu_394 <= ap_const_lv20_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    add_i_2_269_fu_394 <= grp_fu_2285_p3;
                end if;
            end if; 
        end if;
    end process;

    add_i_2_370_fu_398_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    add_i_2_370_fu_398 <= ap_const_lv20_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    add_i_2_370_fu_398 <= grp_fu_2294_p3;
                end if;
            end if; 
        end if;
    end process;

    add_i_35762_fu_366_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    add_i_35762_fu_366 <= ap_const_lv20_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    add_i_35762_fu_366 <= grp_fu_2222_p3;
                end if;
            end if; 
        end if;
    end process;

    add_i_371_fu_402_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    add_i_371_fu_402 <= ap_const_lv20_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    add_i_371_fu_402 <= grp_fu_2303_p3;
                end if;
            end if; 
        end if;
    end process;

    add_i_3_172_fu_406_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    add_i_3_172_fu_406 <= ap_const_lv20_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    add_i_3_172_fu_406 <= grp_fu_2312_p3;
                end if;
            end if; 
        end if;
    end process;

    add_i_3_273_fu_410_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    add_i_3_273_fu_410 <= ap_const_lv20_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    add_i_3_273_fu_410 <= grp_fu_2321_p3;
                end if;
            end if; 
        end if;
    end process;

    add_i_3_374_fu_414_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    add_i_3_374_fu_414 <= ap_const_lv20_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    add_i_3_374_fu_414 <= grp_fu_2330_p3;
                end if;
            end if; 
        end if;
    end process;

    k_fu_418_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln22_fu_1390_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    k_fu_418 <= add_ln22_fu_1396_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    k_fu_418 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln22_reg_2474 <= icmp_ln22_fu_1390_p2;
                icmp_ln22_reg_2474_pp0_iter1_reg <= icmp_ln22_reg_2474;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_i59_out <= add_i59_fu_354;

    add_i59_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln22_reg_2474_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln22_reg_2474_pp0_iter1_reg = ap_const_lv1_1))) then 
            add_i59_out_ap_vld <= ap_const_logic_1;
        else 
            add_i59_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_i_14160_out <= add_i_14160_fu_358;

    add_i_14160_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln22_reg_2474_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln22_reg_2474_pp0_iter1_reg = ap_const_lv1_1))) then 
            add_i_14160_out_ap_vld <= ap_const_logic_1;
        else 
            add_i_14160_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_i_163_out <= add_i_163_fu_370;

    add_i_163_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln22_reg_2474_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln22_reg_2474_pp0_iter1_reg = ap_const_lv1_1))) then 
            add_i_163_out_ap_vld <= ap_const_logic_1;
        else 
            add_i_163_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_i_1_164_out <= add_i_1_164_fu_374;

    add_i_1_164_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln22_reg_2474_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln22_reg_2474_pp0_iter1_reg = ap_const_lv1_1))) then 
            add_i_1_164_out_ap_vld <= ap_const_logic_1;
        else 
            add_i_1_164_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_i_1_265_out <= add_i_1_265_fu_378;

    add_i_1_265_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln22_reg_2474_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln22_reg_2474_pp0_iter1_reg = ap_const_lv1_1))) then 
            add_i_1_265_out_ap_vld <= ap_const_logic_1;
        else 
            add_i_1_265_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_i_1_366_out <= add_i_1_366_fu_382;

    add_i_1_366_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln22_reg_2474_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln22_reg_2474_pp0_iter1_reg = ap_const_lv1_1))) then 
            add_i_1_366_out_ap_vld <= ap_const_logic_1;
        else 
            add_i_1_366_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_i_24961_out <= add_i_24961_fu_362;

    add_i_24961_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln22_reg_2474_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln22_reg_2474_pp0_iter1_reg = ap_const_lv1_1))) then 
            add_i_24961_out_ap_vld <= ap_const_logic_1;
        else 
            add_i_24961_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_i_267_out <= add_i_267_fu_386;

    add_i_267_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln22_reg_2474_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln22_reg_2474_pp0_iter1_reg = ap_const_lv1_1))) then 
            add_i_267_out_ap_vld <= ap_const_logic_1;
        else 
            add_i_267_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_i_2_168_out <= add_i_2_168_fu_390;

    add_i_2_168_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln22_reg_2474_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln22_reg_2474_pp0_iter1_reg = ap_const_lv1_1))) then 
            add_i_2_168_out_ap_vld <= ap_const_logic_1;
        else 
            add_i_2_168_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_i_2_269_out <= add_i_2_269_fu_394;

    add_i_2_269_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln22_reg_2474_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln22_reg_2474_pp0_iter1_reg = ap_const_lv1_1))) then 
            add_i_2_269_out_ap_vld <= ap_const_logic_1;
        else 
            add_i_2_269_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_i_2_370_out <= add_i_2_370_fu_398;

    add_i_2_370_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln22_reg_2474_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln22_reg_2474_pp0_iter1_reg = ap_const_lv1_1))) then 
            add_i_2_370_out_ap_vld <= ap_const_logic_1;
        else 
            add_i_2_370_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_i_35762_out <= add_i_35762_fu_366;

    add_i_35762_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln22_reg_2474_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln22_reg_2474_pp0_iter1_reg = ap_const_lv1_1))) then 
            add_i_35762_out_ap_vld <= ap_const_logic_1;
        else 
            add_i_35762_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_i_371_out <= add_i_371_fu_402;

    add_i_371_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln22_reg_2474_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln22_reg_2474_pp0_iter1_reg = ap_const_lv1_1))) then 
            add_i_371_out_ap_vld <= ap_const_logic_1;
        else 
            add_i_371_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_i_3_172_out <= add_i_3_172_fu_406;

    add_i_3_172_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln22_reg_2474_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln22_reg_2474_pp0_iter1_reg = ap_const_lv1_1))) then 
            add_i_3_172_out_ap_vld <= ap_const_logic_1;
        else 
            add_i_3_172_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_i_3_273_out <= add_i_3_273_fu_410;

    add_i_3_273_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln22_reg_2474_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln22_reg_2474_pp0_iter1_reg = ap_const_lv1_1))) then 
            add_i_3_273_out_ap_vld <= ap_const_logic_1;
        else 
            add_i_3_273_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_i_3_374_out <= add_i_3_374_fu_414;

    add_i_3_374_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln22_reg_2474_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln22_reg_2474_pp0_iter1_reg = ap_const_lv1_1))) then 
            add_i_3_374_out_ap_vld <= ap_const_logic_1;
        else 
            add_i_3_374_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln22_fu_1396_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_k_1) + unsigned(ap_const_lv5_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln22_fu_1390_p2)
    begin
        if (((icmp_ln22_fu_1390_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter2_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_add_i59_load_assign_proc : process(ap_enable_reg_pp0_iter3, add_i59_fu_354, grp_fu_2195_p3, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_sig_allocacmp_add_i59_load <= grp_fu_2195_p3;
        else 
            ap_sig_allocacmp_add_i59_load <= add_i59_fu_354;
        end if; 
    end process;


    ap_sig_allocacmp_add_i_14160_load_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, add_i_14160_fu_358, grp_fu_2204_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_sig_allocacmp_add_i_14160_load <= grp_fu_2204_p3;
        else 
            ap_sig_allocacmp_add_i_14160_load <= add_i_14160_fu_358;
        end if; 
    end process;


    ap_sig_allocacmp_add_i_163_load_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, add_i_163_fu_370, grp_fu_2231_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_sig_allocacmp_add_i_163_load <= grp_fu_2231_p3;
        else 
            ap_sig_allocacmp_add_i_163_load <= add_i_163_fu_370;
        end if; 
    end process;


    ap_sig_allocacmp_add_i_1_164_load_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, add_i_1_164_fu_374, grp_fu_2240_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_sig_allocacmp_add_i_1_164_load <= grp_fu_2240_p3;
        else 
            ap_sig_allocacmp_add_i_1_164_load <= add_i_1_164_fu_374;
        end if; 
    end process;


    ap_sig_allocacmp_add_i_1_265_load_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, add_i_1_265_fu_378, grp_fu_2249_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_sig_allocacmp_add_i_1_265_load <= grp_fu_2249_p3;
        else 
            ap_sig_allocacmp_add_i_1_265_load <= add_i_1_265_fu_378;
        end if; 
    end process;


    ap_sig_allocacmp_add_i_1_366_load_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, add_i_1_366_fu_382, grp_fu_2258_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_sig_allocacmp_add_i_1_366_load <= grp_fu_2258_p3;
        else 
            ap_sig_allocacmp_add_i_1_366_load <= add_i_1_366_fu_382;
        end if; 
    end process;


    ap_sig_allocacmp_add_i_24961_load_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, add_i_24961_fu_362, grp_fu_2213_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_sig_allocacmp_add_i_24961_load <= grp_fu_2213_p3;
        else 
            ap_sig_allocacmp_add_i_24961_load <= add_i_24961_fu_362;
        end if; 
    end process;


    ap_sig_allocacmp_add_i_267_load_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, add_i_267_fu_386, grp_fu_2267_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_sig_allocacmp_add_i_267_load <= grp_fu_2267_p3;
        else 
            ap_sig_allocacmp_add_i_267_load <= add_i_267_fu_386;
        end if; 
    end process;


    ap_sig_allocacmp_add_i_2_168_load_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, add_i_2_168_fu_390, grp_fu_2276_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_sig_allocacmp_add_i_2_168_load <= grp_fu_2276_p3;
        else 
            ap_sig_allocacmp_add_i_2_168_load <= add_i_2_168_fu_390;
        end if; 
    end process;


    ap_sig_allocacmp_add_i_2_269_load_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, add_i_2_269_fu_394, grp_fu_2285_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_sig_allocacmp_add_i_2_269_load <= grp_fu_2285_p3;
        else 
            ap_sig_allocacmp_add_i_2_269_load <= add_i_2_269_fu_394;
        end if; 
    end process;


    ap_sig_allocacmp_add_i_2_370_load_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, add_i_2_370_fu_398, grp_fu_2294_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_sig_allocacmp_add_i_2_370_load <= grp_fu_2294_p3;
        else 
            ap_sig_allocacmp_add_i_2_370_load <= add_i_2_370_fu_398;
        end if; 
    end process;


    ap_sig_allocacmp_add_i_35762_load_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, add_i_35762_fu_366, grp_fu_2222_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_sig_allocacmp_add_i_35762_load <= grp_fu_2222_p3;
        else 
            ap_sig_allocacmp_add_i_35762_load <= add_i_35762_fu_366;
        end if; 
    end process;


    ap_sig_allocacmp_add_i_371_load_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, add_i_371_fu_402, grp_fu_2303_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_sig_allocacmp_add_i_371_load <= grp_fu_2303_p3;
        else 
            ap_sig_allocacmp_add_i_371_load <= add_i_371_fu_402;
        end if; 
    end process;


    ap_sig_allocacmp_add_i_3_172_load_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, add_i_3_172_fu_406, grp_fu_2312_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_sig_allocacmp_add_i_3_172_load <= grp_fu_2312_p3;
        else 
            ap_sig_allocacmp_add_i_3_172_load <= add_i_3_172_fu_406;
        end if; 
    end process;


    ap_sig_allocacmp_add_i_3_273_load_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, add_i_3_273_fu_410, grp_fu_2321_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_sig_allocacmp_add_i_3_273_load <= grp_fu_2321_p3;
        else 
            ap_sig_allocacmp_add_i_3_273_load <= add_i_3_273_fu_410;
        end if; 
    end process;


    ap_sig_allocacmp_add_i_3_374_load_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, add_i_3_374_fu_414, grp_fu_2330_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_sig_allocacmp_add_i_3_374_load <= grp_fu_2330_p3;
        else 
            ap_sig_allocacmp_add_i_3_374_load <= add_i_3_374_fu_414;
        end if; 
    end process;


    ap_sig_allocacmp_k_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, k_fu_418)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_k_1 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_k_1 <= k_fu_418;
        end if; 
    end process;

    grp_fu_2195_p0 <= sext_ln27_1_fu_1554_p1(8 - 1 downto 0);
    grp_fu_2195_p1 <= sext_ln27_fu_1478_p1(8 - 1 downto 0);
    grp_fu_2204_p0 <= sext_ln27_3_fu_1630_p1(8 - 1 downto 0);
    grp_fu_2204_p1 <= sext_ln27_fu_1478_p1(8 - 1 downto 0);
    grp_fu_2213_p0 <= sext_ln27_5_fu_1706_p1(8 - 1 downto 0);
    grp_fu_2213_p1 <= sext_ln27_fu_1478_p1(8 - 1 downto 0);
    grp_fu_2222_p0 <= sext_ln27_7_fu_1782_p1(8 - 1 downto 0);
    grp_fu_2222_p1 <= sext_ln27_fu_1478_p1(8 - 1 downto 0);
    grp_fu_2231_p0 <= sext_ln27_9_fu_1858_p1(8 - 1 downto 0);
    grp_fu_2231_p1 <= sext_ln27_1_fu_1554_p1(8 - 1 downto 0);
    grp_fu_2240_p0 <= sext_ln27_9_fu_1858_p1(8 - 1 downto 0);
    grp_fu_2240_p1 <= sext_ln27_3_fu_1630_p1(8 - 1 downto 0);
    grp_fu_2249_p0 <= sext_ln27_9_fu_1858_p1(8 - 1 downto 0);
    grp_fu_2249_p1 <= sext_ln27_5_fu_1706_p1(8 - 1 downto 0);
    grp_fu_2258_p0 <= sext_ln27_9_fu_1858_p1(8 - 1 downto 0);
    grp_fu_2258_p1 <= sext_ln27_7_fu_1782_p1(8 - 1 downto 0);
    grp_fu_2267_p0 <= sext_ln27_14_fu_1934_p1(8 - 1 downto 0);
    grp_fu_2267_p1 <= sext_ln27_1_fu_1554_p1(8 - 1 downto 0);
    grp_fu_2276_p0 <= sext_ln27_14_fu_1934_p1(8 - 1 downto 0);
    grp_fu_2276_p1 <= sext_ln27_3_fu_1630_p1(8 - 1 downto 0);
    grp_fu_2285_p0 <= sext_ln27_14_fu_1934_p1(8 - 1 downto 0);
    grp_fu_2285_p1 <= sext_ln27_5_fu_1706_p1(8 - 1 downto 0);
    grp_fu_2294_p0 <= sext_ln27_14_fu_1934_p1(8 - 1 downto 0);
    grp_fu_2294_p1 <= sext_ln27_7_fu_1782_p1(8 - 1 downto 0);
    grp_fu_2303_p0 <= sext_ln27_19_fu_2010_p1(8 - 1 downto 0);
    grp_fu_2303_p1 <= sext_ln27_1_fu_1554_p1(8 - 1 downto 0);
    grp_fu_2312_p0 <= sext_ln27_19_fu_2010_p1(8 - 1 downto 0);
    grp_fu_2312_p1 <= sext_ln27_3_fu_1630_p1(8 - 1 downto 0);
    grp_fu_2321_p0 <= sext_ln27_19_fu_2010_p1(8 - 1 downto 0);
    grp_fu_2321_p1 <= sext_ln27_5_fu_1706_p1(8 - 1 downto 0);
    grp_fu_2330_p0 <= sext_ln27_19_fu_2010_p1(8 - 1 downto 0);
    grp_fu_2330_p1 <= sext_ln27_7_fu_1782_p1(8 - 1 downto 0);
    icmp_ln22_fu_1390_p2 <= "1" when (ap_sig_allocacmp_k_1 = ap_const_lv5_10) else "0";
        sext_ln27_14_fu_1934_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_6_fu_1862_p35),16));

        sext_ln27_19_fu_2010_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_7_fu_1938_p35),16));

        sext_ln27_1_fu_1554_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_1_fu_1482_p35),16));

        sext_ln27_3_fu_1630_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_2_fu_1558_p35),16));

        sext_ln27_5_fu_1706_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_3_fu_1634_p35),16));

        sext_ln27_7_fu_1782_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_4_fu_1710_p35),16));

        sext_ln27_9_fu_1858_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_5_fu_1786_p35),16));

        sext_ln27_fu_1478_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_fu_1406_p35),16));

    tmp_1_fu_1482_p33 <= "XXXXXXXX";
    tmp_2_fu_1558_p33 <= "XXXXXXXX";
    tmp_3_fu_1634_p33 <= "XXXXXXXX";
    tmp_4_fu_1710_p33 <= "XXXXXXXX";
    tmp_5_fu_1786_p33 <= "XXXXXXXX";
    tmp_6_fu_1862_p33 <= "XXXXXXXX";
    tmp_7_fu_1938_p33 <= "XXXXXXXX";
    tmp_fu_1406_p33 <= "XXXXXXXX";
    trunc_ln22_fu_1402_p1 <= ap_sig_allocacmp_k_1(4 - 1 downto 0);
end behav;
