// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="layernorm_kernel_layernorm_kernel,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.299533,HLS_SYN_LAT=168,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2605,HLS_SYN_LUT=3759,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module layernorm_kernel (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        X_0,
        X_1,
        X_2,
        X_3,
        X_4,
        X_5,
        X_6,
        X_7,
        X_8,
        X_9,
        X_10,
        X_11,
        X_12,
        X_13,
        X_14,
        X_15,
        X_16,
        X_17,
        X_18,
        X_19,
        X_20,
        X_21,
        X_22,
        X_23,
        X_24,
        X_25,
        X_26,
        X_27,
        X_28,
        X_29,
        X_30,
        X_31,
        X_32,
        X_33,
        X_34,
        X_35,
        X_36,
        X_37,
        X_38,
        X_39,
        X_40,
        X_41,
        X_42,
        X_43,
        X_44,
        X_45,
        X_46,
        X_47,
        X_48,
        X_49,
        X_50,
        X_51,
        X_52,
        X_53,
        X_54,
        X_55,
        X_56,
        X_57,
        X_58,
        X_59,
        X_60,
        X_61,
        X_62,
        X_63,
        Y_address0,
        Y_ce0,
        Y_we0,
        Y_d0
);

parameter    ap_ST_fsm_state1 = 35'd1;
parameter    ap_ST_fsm_state2 = 35'd2;
parameter    ap_ST_fsm_state3 = 35'd4;
parameter    ap_ST_fsm_state4 = 35'd8;
parameter    ap_ST_fsm_state5 = 35'd16;
parameter    ap_ST_fsm_state6 = 35'd32;
parameter    ap_ST_fsm_state7 = 35'd64;
parameter    ap_ST_fsm_state8 = 35'd128;
parameter    ap_ST_fsm_state9 = 35'd256;
parameter    ap_ST_fsm_state10 = 35'd512;
parameter    ap_ST_fsm_state11 = 35'd1024;
parameter    ap_ST_fsm_state12 = 35'd2048;
parameter    ap_ST_fsm_state13 = 35'd4096;
parameter    ap_ST_fsm_state14 = 35'd8192;
parameter    ap_ST_fsm_state15 = 35'd16384;
parameter    ap_ST_fsm_state16 = 35'd32768;
parameter    ap_ST_fsm_state17 = 35'd65536;
parameter    ap_ST_fsm_state18 = 35'd131072;
parameter    ap_ST_fsm_state19 = 35'd262144;
parameter    ap_ST_fsm_state20 = 35'd524288;
parameter    ap_ST_fsm_state21 = 35'd1048576;
parameter    ap_ST_fsm_state22 = 35'd2097152;
parameter    ap_ST_fsm_state23 = 35'd4194304;
parameter    ap_ST_fsm_state24 = 35'd8388608;
parameter    ap_ST_fsm_state25 = 35'd16777216;
parameter    ap_ST_fsm_state26 = 35'd33554432;
parameter    ap_ST_fsm_state27 = 35'd67108864;
parameter    ap_ST_fsm_state28 = 35'd134217728;
parameter    ap_ST_fsm_state29 = 35'd268435456;
parameter    ap_ST_fsm_state30 = 35'd536870912;
parameter    ap_ST_fsm_state31 = 35'd1073741824;
parameter    ap_ST_fsm_state32 = 35'd2147483648;
parameter    ap_ST_fsm_state33 = 35'd4294967296;
parameter    ap_ST_fsm_state34 = 35'd8589934592;
parameter    ap_ST_fsm_state35 = 35'd17179869184;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] X_0;
input  [7:0] X_1;
input  [7:0] X_2;
input  [7:0] X_3;
input  [7:0] X_4;
input  [7:0] X_5;
input  [7:0] X_6;
input  [7:0] X_7;
input  [7:0] X_8;
input  [7:0] X_9;
input  [7:0] X_10;
input  [7:0] X_11;
input  [7:0] X_12;
input  [7:0] X_13;
input  [7:0] X_14;
input  [7:0] X_15;
input  [7:0] X_16;
input  [7:0] X_17;
input  [7:0] X_18;
input  [7:0] X_19;
input  [7:0] X_20;
input  [7:0] X_21;
input  [7:0] X_22;
input  [7:0] X_23;
input  [7:0] X_24;
input  [7:0] X_25;
input  [7:0] X_26;
input  [7:0] X_27;
input  [7:0] X_28;
input  [7:0] X_29;
input  [7:0] X_30;
input  [7:0] X_31;
input  [7:0] X_32;
input  [7:0] X_33;
input  [7:0] X_34;
input  [7:0] X_35;
input  [7:0] X_36;
input  [7:0] X_37;
input  [7:0] X_38;
input  [7:0] X_39;
input  [7:0] X_40;
input  [7:0] X_41;
input  [7:0] X_42;
input  [7:0] X_43;
input  [7:0] X_44;
input  [7:0] X_45;
input  [7:0] X_46;
input  [7:0] X_47;
input  [7:0] X_48;
input  [7:0] X_49;
input  [7:0] X_50;
input  [7:0] X_51;
input  [7:0] X_52;
input  [7:0] X_53;
input  [7:0] X_54;
input  [7:0] X_55;
input  [7:0] X_56;
input  [7:0] X_57;
input  [7:0] X_58;
input  [7:0] X_59;
input  [7:0] X_60;
input  [7:0] X_61;
input  [7:0] X_62;
input  [7:0] X_63;
output  [5:0] Y_address0;
output   Y_ce0;
output   Y_we0;
output  [7:0] Y_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [34:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [7:0] X_0_read_reg_1824;
reg   [7:0] X_1_read_reg_1830;
reg   [7:0] X_2_read_reg_1836;
reg   [7:0] X_3_read_reg_1842;
reg   [7:0] X_4_read_reg_1848;
reg   [7:0] X_5_read_reg_1854;
reg   [7:0] X_6_read_reg_1860;
reg   [7:0] X_7_read_reg_1866;
reg   [7:0] X_8_read_reg_1872;
reg   [7:0] X_9_read_reg_1878;
reg   [7:0] X_10_read_reg_1884;
reg   [7:0] X_11_read_reg_1890;
reg   [7:0] X_12_read_reg_1896;
reg   [7:0] X_13_read_reg_1902;
reg   [7:0] X_14_read_reg_1908;
reg   [7:0] X_15_read_reg_1914;
reg   [7:0] X_16_read_reg_1920;
reg   [7:0] X_17_read_reg_1926;
reg   [7:0] X_18_read_reg_1932;
reg   [7:0] X_19_read_reg_1938;
reg   [7:0] X_20_read_reg_1944;
reg   [7:0] X_21_read_reg_1950;
reg   [7:0] X_22_read_reg_1956;
reg   [7:0] X_23_read_reg_1962;
reg   [7:0] X_24_read_reg_1968;
reg   [7:0] X_25_read_reg_1974;
reg   [7:0] X_26_read_reg_1980;
reg   [7:0] X_27_read_reg_1986;
reg   [7:0] X_28_read_reg_1992;
reg   [7:0] X_29_read_reg_1998;
reg   [7:0] X_30_read_reg_2004;
reg   [7:0] X_31_read_reg_2010;
reg   [7:0] X_32_read_reg_2016;
reg   [7:0] X_33_read_reg_2022;
reg   [7:0] X_34_read_reg_2028;
reg   [7:0] X_35_read_reg_2034;
reg   [7:0] X_36_read_reg_2040;
reg   [7:0] X_37_read_reg_2046;
reg   [7:0] X_38_read_reg_2052;
reg   [7:0] X_39_read_reg_2058;
reg   [7:0] X_40_read_reg_2064;
reg   [7:0] X_41_read_reg_2070;
reg   [7:0] X_42_read_reg_2076;
reg   [7:0] X_43_read_reg_2082;
reg   [7:0] X_44_read_reg_2088;
reg   [7:0] X_45_read_reg_2094;
reg   [7:0] X_46_read_reg_2100;
reg   [7:0] X_47_read_reg_2106;
reg   [7:0] X_48_read_reg_2112;
reg   [7:0] X_49_read_reg_2118;
reg   [7:0] X_50_read_reg_2124;
reg   [7:0] X_51_read_reg_2130;
reg   [7:0] X_52_read_reg_2136;
reg   [7:0] X_53_read_reg_2142;
reg   [7:0] X_54_read_reg_2148;
reg   [7:0] X_55_read_reg_2154;
reg   [7:0] X_56_read_reg_2160;
reg   [7:0] X_57_read_reg_2166;
reg   [7:0] X_58_read_reg_2172;
reg   [7:0] X_59_read_reg_2178;
reg   [7:0] X_60_read_reg_2184;
reg   [7:0] X_61_read_reg_2190;
reg   [7:0] X_62_read_reg_2196;
reg   [7:0] X_63_read_reg_2202;
wire  signed [17:0] mean_fu_962_p3;
reg   [17:0] mean_reg_2208;
wire    ap_CS_fsm_state3;
wire  signed [35:0] sext_ln23_1_fu_970_p1;
wire    ap_CS_fsm_state5;
reg   [23:0] var_reg_2224;
wire    ap_CS_fsm_state6;
wire   [0:0] tmp_6_fu_1066_p3;
reg   [0:0] tmp_6_reg_2230;
wire   [22:0] select_ln24_fu_1080_p3;
reg   [22:0] select_ln24_reg_2235;
wire   [63:0] LD_fu_1179_p5;
reg   [63:0] LD_reg_2241;
wire    ap_CS_fsm_state7;
wire   [63:0] bitcast_ln758_fu_1191_p1;
wire    ap_CS_fsm_state8;
wire   [23:0] var_1_fu_1206_p3;
reg   [23:0] var_1_reg_2251;
wire    ap_CS_fsm_state9;
reg   [0:0] tmp_10_reg_2258;
wire   [23:0] select_ln24_2_fu_1226_p3;
reg   [23:0] select_ln24_2_reg_2264;
wire    ap_CS_fsm_state10;
wire   [63:0] LD_1_fu_1319_p5;
reg   [63:0] LD_1_reg_2270;
wire    ap_CS_fsm_state11;
wire   [63:0] bitcast_ln758_1_fu_1331_p1;
wire    ap_CS_fsm_state12;
wire   [0:0] grp_fu_896_p2;
reg   [0:0] tmp_13_reg_2280;
wire    ap_CS_fsm_state13;
wire   [23:0] var_3_fu_1335_p3;
reg   [23:0] var_3_reg_2285;
wire    ap_CS_fsm_state14;
wire   [0:0] tmp_14_fu_1341_p3;
reg   [0:0] tmp_14_reg_2296;
wire   [23:0] select_ln6_fu_1355_p3;
reg   [23:0] select_ln6_reg_2301;
wire   [63:0] LD_2_fu_1450_p5;
reg   [63:0] LD_2_reg_2307;
wire    ap_CS_fsm_state15;
wire   [63:0] bitcast_ln758_2_fu_1462_p1;
wire    ap_CS_fsm_state16;
wire   [47:0] sub_ln9_3_fu_1501_p2;
reg   [47:0] sub_ln9_3_reg_2317;
reg   [0:0] tmp_16_reg_2322;
wire    ap_CS_fsm_state17;
wire   [47:0] add_ln9_1_fu_1534_p2;
reg   [47:0] add_ln9_1_reg_2329;
wire   [47:0] select_ln9_fu_1551_p3;
reg   [47:0] select_ln9_reg_2334;
wire    ap_CS_fsm_state18;
wire   [59:0] sub_ln9_5_fu_1599_p2;
reg   [59:0] sub_ln9_5_reg_2341;
wire   [59:0] add_ln9_3_fu_1632_p2;
reg   [59:0] add_ln9_3_reg_2346;
wire    ap_CS_fsm_state19;
wire   [60:0] sub_ln9_fu_1655_p2;
reg   [60:0] sub_ln9_reg_2351;
wire    ap_CS_fsm_state20;
wire   [71:0] sub_ln9_7_fu_1699_p2;
reg   [71:0] sub_ln9_7_reg_2357;
reg   [23:0] tmp_22_reg_2362;
wire  signed [23:0] select_ln9_2_fu_1758_p3;
reg  signed [23:0] select_ln9_2_reg_2367;
wire    ap_CS_fsm_state21;
wire   [58:0] mul_ln9_fu_903_p2;
reg  signed [58:0] mul_ln9_reg_2373;
wire    ap_CS_fsm_state22;
wire    ap_CS_fsm_state23;
wire  signed [71:0] sext_ln9_8_fu_1784_p1;
reg  signed [71:0] sext_ln9_8_reg_2383;
wire   [71:0] grp_fu_907_p2;
reg   [71:0] mul_ln9_1_reg_2389;
wire    ap_CS_fsm_state27;
wire  signed [71:0] sub_ln9_1_fu_1788_p2;
reg  signed [71:0] sub_ln9_1_reg_2394;
wire    ap_CS_fsm_state28;
reg   [23:0] inv_reg_2399;
wire    ap_CS_fsm_state33;
wire    grp_layernorm_kernel_Pipeline_accum_fu_690_ap_start;
wire    grp_layernorm_kernel_Pipeline_accum_fu_690_ap_done;
wire    grp_layernorm_kernel_Pipeline_accum_fu_690_ap_idle;
wire    grp_layernorm_kernel_Pipeline_accum_fu_690_ap_ready;
wire   [23:0] grp_layernorm_kernel_Pipeline_accum_fu_690_sq_sum_out;
wire    grp_layernorm_kernel_Pipeline_accum_fu_690_sq_sum_out_ap_vld;
wire   [23:0] grp_layernorm_kernel_Pipeline_accum_fu_690_sum_out;
wire    grp_layernorm_kernel_Pipeline_accum_fu_690_sum_out_ap_vld;
wire    grp_layernorm_kernel_Pipeline_norm_fu_824_ap_start;
wire    grp_layernorm_kernel_Pipeline_norm_fu_824_ap_done;
wire    grp_layernorm_kernel_Pipeline_norm_fu_824_ap_idle;
wire    grp_layernorm_kernel_Pipeline_norm_fu_824_ap_ready;
wire   [5:0] grp_layernorm_kernel_Pipeline_norm_fu_824_Y_address0;
wire    grp_layernorm_kernel_Pipeline_norm_fu_824_Y_ce0;
wire    grp_layernorm_kernel_Pipeline_norm_fu_824_Y_we0;
wire   [7:0] grp_layernorm_kernel_Pipeline_norm_fu_824_Y_d0;
reg    grp_layernorm_kernel_Pipeline_accum_fu_690_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_layernorm_kernel_Pipeline_norm_fu_824_ap_start_reg;
wire    ap_CS_fsm_state34;
wire    ap_CS_fsm_state35;
reg   [63:0] grp_fu_896_p0;
reg   [63:0] grp_fu_896_p1;
wire  signed [23:0] grp_fu_911_p1;
wire    ap_CS_fsm_state29;
wire  signed [23:0] sext_ln22_fu_918_p0;
wire  signed [23:0] tmp_fu_922_p1;
wire  signed [24:0] sext_ln22_fu_918_p1;
wire   [24:0] sub_ln22_fu_930_p2;
wire  signed [23:0] zext_ln_fu_946_p1;
wire   [17:0] tmp_19_cast_fu_936_p4;
wire   [0:0] tmp_fu_922_p3;
wire   [17:0] sub_ln22_1_fu_956_p2;
wire   [17:0] zext_ln_fu_946_p4;
wire  signed [23:0] sext_ln23_fu_977_p0;
wire  signed [23:0] tmp_5_fu_981_p1;
wire  signed [24:0] sext_ln23_fu_977_p1;
wire   [24:0] sub_ln23_1_fu_989_p2;
wire   [17:0] tmp_20_cast_fu_995_p4;
wire  signed [23:0] zext_ln1_fu_1011_p1;
wire   [0:0] tmp_5_fu_981_p3;
wire   [17:0] sub_ln23_2_fu_1005_p2;
wire   [17:0] zext_ln1_fu_1011_p4;
wire   [17:0] select_ln23_fu_1021_p3;
wire  signed [29:0] shl_ln_fu_1029_p3;
wire  signed [35:0] grp_fu_1803_p3;
(* use_dsp = "no" *) wire   [35:0] add_ln23_fu_1041_p2;
wire   [22:0] var_cast_fu_1056_p4;
wire   [22:0] sub_ln24_fu_1074_p2;
wire   [23:0] tmp_2_fu_1091_p1;
wire   [23:0] tmp_2_fu_1091_p3;
wire   [5:0] trunc_ln24_fu_1099_p1;
wire   [5:0] add_ln24_fu_1110_p2;
wire   [63:0] zext_ln24_fu_1107_p1;
wire   [63:0] zext_ln24_1_fu_1116_p1;
wire   [63:0] shl_ln24_fu_1120_p2;
wire   [62:0] lshr_ln_fu_1126_p4;
wire   [0:0] tmp_8_fu_1140_p3;
wire   [4:0] trunc_ln24_1_fu_1103_p1;
wire   [4:0] sub_ln24_1_fu_1156_p2;
wire  signed [10:0] sext_ln24_fu_1162_p1;
wire   [10:0] select_ln24_1_fu_1148_p3;
wire   [10:0] add_ln24_1_fu_1166_p2;
wire   [63:0] zext_ln24_4_fu_1136_p1;
wire   [11:0] tmp_3_fu_1172_p3;
wire   [0:0] icmp_ln24_fu_1195_p2;
wire   [0:0] empty_fu_1200_p2;
wire   [23:0] sub_ln24_2_fu_1221_p2;
wire   [23:0] tmp_9_fu_1232_p3;
wire   [5:0] trunc_ln24_2_fu_1239_p1;
wire   [5:0] add_ln24_2_fu_1250_p2;
wire   [63:0] zext_ln24_2_fu_1247_p1;
wire   [63:0] zext_ln24_3_fu_1256_p1;
wire   [63:0] shl_ln24_1_fu_1260_p2;
wire   [62:0] lshr_ln24_1_fu_1266_p4;
wire   [0:0] tmp_12_fu_1280_p3;
wire   [4:0] trunc_ln24_3_fu_1243_p1;
wire   [4:0] sub_ln24_3_fu_1296_p2;
wire  signed [10:0] sext_ln24_1_fu_1302_p1;
wire   [10:0] select_ln24_3_fu_1288_p3;
wire   [10:0] add_ln24_3_fu_1306_p2;
wire   [63:0] zext_ln24_5_fu_1276_p1;
wire   [11:0] tmp_4_fu_1312_p3;
wire   [23:0] sub_ln6_fu_1349_p2;
wire   [23:0] tmp_7_fu_1363_p3;
wire   [5:0] trunc_ln6_fu_1370_p1;
wire   [5:0] add_ln6_fu_1381_p2;
wire   [63:0] zext_ln6_fu_1378_p1;
wire   [63:0] zext_ln6_1_fu_1387_p1;
wire   [63:0] shl_ln6_fu_1391_p2;
wire   [62:0] lshr_ln6_fu_1397_p4;
wire   [0:0] tmp_15_fu_1411_p3;
wire   [4:0] trunc_ln6_1_fu_1374_p1;
wire   [4:0] sub_ln6_1_fu_1427_p2;
wire  signed [10:0] sext_ln6_fu_1433_p1;
wire   [10:0] select_ln6_1_fu_1419_p3;
wire   [10:0] add_ln6_1_fu_1437_p2;
wire   [63:0] zext_ln6_2_fu_1407_p1;
wire   [11:0] tmp_11_fu_1443_p3;
wire   [45:0] tmp_17_fu_1473_p3;
wire   [47:0] p_shl1_fu_1466_p3;
wire  signed [47:0] sext_ln9_1_fu_1480_p1;
wire   [43:0] tmp_18_fu_1490_p3;
wire   [47:0] sub_ln9_2_fu_1484_p2;
wire  signed [47:0] sext_ln9_3_fu_1497_p1;
wire   [41:0] tmp_19_fu_1507_p3;
wire  signed [47:0] sext_ln9_5_fu_1514_p1;
wire   [39:0] tmp_20_fu_1523_p3;
wire   [47:0] add_ln9_fu_1518_p2;
wire  signed [47:0] sext_ln9_9_fu_1530_p1;
wire   [46:0] shl_ln9_1_fu_1540_p3;
wire  signed [47:0] sext_ln9_2_fu_1547_p1;
wire   [46:0] trunc_ln9_fu_1557_p1;
wire   [58:0] tmp_23_fu_1569_p3;
wire   [59:0] p_shl2_fu_1561_p3;
wire  signed [59:0] sext_ln9_10_fu_1577_p1;
wire   [56:0] tmp_24_fu_1587_p3;
wire   [59:0] sub_ln9_4_fu_1581_p2;
wire  signed [59:0] sext_ln9_11_fu_1595_p1;
wire   [54:0] tmp_25_fu_1605_p3;
wire  signed [59:0] sext_ln9_12_fu_1612_p1;
wire   [52:0] tmp_26_fu_1621_p3;
wire   [59:0] add_ln9_2_fu_1616_p2;
wire  signed [59:0] sext_ln9_13_fu_1628_p1;
wire   [59:0] shl_ln9_2_fu_1638_p3;
wire   [59:0] select_ln9_1_fu_1645_p3;
wire  signed [60:0] sext_ln9_4_fu_1651_p1;
wire   [58:0] trunc_ln9_1_fu_1661_p1;
wire   [71:0] p_shl_fu_1665_p3;
wire   [71:0] p_shl3_fu_1673_p3;
wire   [69:0] tmp_27_fu_1687_p3;
wire   [71:0] sub_ln9_6_fu_1681_p2;
wire  signed [71:0] sext_ln9_14_fu_1695_p1;
wire   [67:0] tmp_28_fu_1715_p3;
wire  signed [71:0] sext_ln9_15_fu_1722_p1;
wire   [65:0] tmp_29_fu_1731_p3;
wire   [71:0] add_ln9_4_fu_1726_p2;
wire  signed [71:0] sext_ln9_16_fu_1738_p1;
wire   [71:0] add_ln9_5_fu_1742_p2;
wire   [23:0] tmp_21_fu_1748_p4;
wire  signed [34:0] shl_ln9_fu_1764_p3;
wire   [71:0] grp_fu_911_p2;
wire  signed [17:0] grp_fu_1803_p0;
wire  signed [17:0] grp_fu_1803_p1;
reg   [4:0] grp_fu_896_opcode;
reg   [34:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
reg    ap_ST_fsm_state35_blk;
wire   [23:0] tmp_2_fu_1091_p0;
wire   [0:0] tmp_2_fu_1091_p2;
wire   [23:0] tmp_9_fu_1232_p0;
wire   [0:0] tmp_9_fu_1232_p2;
wire   [23:0] tmp_7_fu_1363_p0;
wire   [0:0] tmp_7_fu_1363_p2;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 35'd1;
#0 grp_layernorm_kernel_Pipeline_accum_fu_690_ap_start_reg = 1'b0;
#0 grp_layernorm_kernel_Pipeline_norm_fu_824_ap_start_reg = 1'b0;
end

layernorm_kernel_layernorm_kernel_Pipeline_accum grp_layernorm_kernel_Pipeline_accum_fu_690(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_layernorm_kernel_Pipeline_accum_fu_690_ap_start),
    .ap_done(grp_layernorm_kernel_Pipeline_accum_fu_690_ap_done),
    .ap_idle(grp_layernorm_kernel_Pipeline_accum_fu_690_ap_idle),
    .ap_ready(grp_layernorm_kernel_Pipeline_accum_fu_690_ap_ready),
    .X_0_load(X_0_read_reg_1824),
    .X_1_load(X_1_read_reg_1830),
    .X_2_load(X_2_read_reg_1836),
    .X_3_load(X_3_read_reg_1842),
    .X_4_load(X_4_read_reg_1848),
    .X_5_load(X_5_read_reg_1854),
    .X_6_load(X_6_read_reg_1860),
    .X_7_load(X_7_read_reg_1866),
    .X_8_load(X_8_read_reg_1872),
    .X_9_load(X_9_read_reg_1878),
    .X_10_load(X_10_read_reg_1884),
    .X_11_load(X_11_read_reg_1890),
    .X_12_load(X_12_read_reg_1896),
    .X_13_load(X_13_read_reg_1902),
    .X_14_load(X_14_read_reg_1908),
    .X_15_load(X_15_read_reg_1914),
    .X_16_load(X_16_read_reg_1920),
    .X_17_load(X_17_read_reg_1926),
    .X_18_load(X_18_read_reg_1932),
    .X_19_load(X_19_read_reg_1938),
    .X_20_load(X_20_read_reg_1944),
    .X_21_load(X_21_read_reg_1950),
    .X_22_load(X_22_read_reg_1956),
    .X_23_load(X_23_read_reg_1962),
    .X_24_load(X_24_read_reg_1968),
    .X_25_load(X_25_read_reg_1974),
    .X_26_load(X_26_read_reg_1980),
    .X_27_load(X_27_read_reg_1986),
    .X_28_load(X_28_read_reg_1992),
    .X_29_load(X_29_read_reg_1998),
    .X_30_load(X_30_read_reg_2004),
    .X_31_load(X_31_read_reg_2010),
    .X_32_load(X_32_read_reg_2016),
    .X_33_load(X_33_read_reg_2022),
    .X_34_load(X_34_read_reg_2028),
    .X_35_load(X_35_read_reg_2034),
    .X_36_load(X_36_read_reg_2040),
    .X_37_load(X_37_read_reg_2046),
    .X_38_load(X_38_read_reg_2052),
    .X_39_load(X_39_read_reg_2058),
    .X_40_load(X_40_read_reg_2064),
    .X_41_load(X_41_read_reg_2070),
    .X_42_load(X_42_read_reg_2076),
    .X_43_load(X_43_read_reg_2082),
    .X_44_load(X_44_read_reg_2088),
    .X_45_load(X_45_read_reg_2094),
    .X_46_load(X_46_read_reg_2100),
    .X_47_load(X_47_read_reg_2106),
    .X_48_load(X_48_read_reg_2112),
    .X_49_load(X_49_read_reg_2118),
    .X_50_load(X_50_read_reg_2124),
    .X_51_load(X_51_read_reg_2130),
    .X_52_load(X_52_read_reg_2136),
    .X_53_load(X_53_read_reg_2142),
    .X_54_load(X_54_read_reg_2148),
    .X_55_load(X_55_read_reg_2154),
    .X_56_load(X_56_read_reg_2160),
    .X_57_load(X_57_read_reg_2166),
    .X_58_load(X_58_read_reg_2172),
    .X_59_load(X_59_read_reg_2178),
    .X_60_load(X_60_read_reg_2184),
    .X_61_load(X_61_read_reg_2190),
    .X_62_load(X_62_read_reg_2196),
    .X_63_load(X_63_read_reg_2202),
    .sq_sum_out(grp_layernorm_kernel_Pipeline_accum_fu_690_sq_sum_out),
    .sq_sum_out_ap_vld(grp_layernorm_kernel_Pipeline_accum_fu_690_sq_sum_out_ap_vld),
    .sum_out(grp_layernorm_kernel_Pipeline_accum_fu_690_sum_out),
    .sum_out_ap_vld(grp_layernorm_kernel_Pipeline_accum_fu_690_sum_out_ap_vld)
);

layernorm_kernel_layernorm_kernel_Pipeline_norm grp_layernorm_kernel_Pipeline_norm_fu_824(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_layernorm_kernel_Pipeline_norm_fu_824_ap_start),
    .ap_done(grp_layernorm_kernel_Pipeline_norm_fu_824_ap_done),
    .ap_idle(grp_layernorm_kernel_Pipeline_norm_fu_824_ap_idle),
    .ap_ready(grp_layernorm_kernel_Pipeline_norm_fu_824_ap_ready),
    .X_0_load(X_0_read_reg_1824),
    .X_1_load(X_1_read_reg_1830),
    .X_2_load(X_2_read_reg_1836),
    .X_3_load(X_3_read_reg_1842),
    .X_4_load(X_4_read_reg_1848),
    .X_5_load(X_5_read_reg_1854),
    .X_6_load(X_6_read_reg_1860),
    .X_7_load(X_7_read_reg_1866),
    .X_8_load(X_8_read_reg_1872),
    .X_9_load(X_9_read_reg_1878),
    .X_10_load(X_10_read_reg_1884),
    .X_11_load(X_11_read_reg_1890),
    .X_12_load(X_12_read_reg_1896),
    .X_13_load(X_13_read_reg_1902),
    .X_14_load(X_14_read_reg_1908),
    .X_15_load(X_15_read_reg_1914),
    .X_16_load(X_16_read_reg_1920),
    .X_17_load(X_17_read_reg_1926),
    .X_18_load(X_18_read_reg_1932),
    .X_19_load(X_19_read_reg_1938),
    .X_20_load(X_20_read_reg_1944),
    .X_21_load(X_21_read_reg_1950),
    .X_22_load(X_22_read_reg_1956),
    .X_23_load(X_23_read_reg_1962),
    .X_24_load(X_24_read_reg_1968),
    .X_25_load(X_25_read_reg_1974),
    .X_26_load(X_26_read_reg_1980),
    .X_27_load(X_27_read_reg_1986),
    .X_28_load(X_28_read_reg_1992),
    .X_29_load(X_29_read_reg_1998),
    .X_30_load(X_30_read_reg_2004),
    .X_31_load(X_31_read_reg_2010),
    .X_32_load(X_32_read_reg_2016),
    .X_33_load(X_33_read_reg_2022),
    .X_34_load(X_34_read_reg_2028),
    .X_35_load(X_35_read_reg_2034),
    .X_36_load(X_36_read_reg_2040),
    .X_37_load(X_37_read_reg_2046),
    .X_38_load(X_38_read_reg_2052),
    .X_39_load(X_39_read_reg_2058),
    .X_40_load(X_40_read_reg_2064),
    .X_41_load(X_41_read_reg_2070),
    .X_42_load(X_42_read_reg_2076),
    .X_43_load(X_43_read_reg_2082),
    .X_44_load(X_44_read_reg_2088),
    .X_45_load(X_45_read_reg_2094),
    .X_46_load(X_46_read_reg_2100),
    .X_47_load(X_47_read_reg_2106),
    .X_48_load(X_48_read_reg_2112),
    .X_49_load(X_49_read_reg_2118),
    .X_50_load(X_50_read_reg_2124),
    .X_51_load(X_51_read_reg_2130),
    .X_52_load(X_52_read_reg_2136),
    .X_53_load(X_53_read_reg_2142),
    .X_54_load(X_54_read_reg_2148),
    .X_55_load(X_55_read_reg_2154),
    .X_56_load(X_56_read_reg_2160),
    .X_57_load(X_57_read_reg_2166),
    .X_58_load(X_58_read_reg_2172),
    .X_59_load(X_59_read_reg_2178),
    .X_60_load(X_60_read_reg_2184),
    .X_61_load(X_61_read_reg_2190),
    .X_62_load(X_62_read_reg_2196),
    .X_63_load(X_63_read_reg_2202),
    .sext_ln29(mean_reg_2208),
    .sext_ln27(inv_reg_2399),
    .Y_address0(grp_layernorm_kernel_Pipeline_norm_fu_824_Y_address0),
    .Y_ce0(grp_layernorm_kernel_Pipeline_norm_fu_824_Y_ce0),
    .Y_we0(grp_layernorm_kernel_Pipeline_norm_fu_824_Y_we0),
    .Y_d0(grp_layernorm_kernel_Pipeline_norm_fu_824_Y_d0)
);

layernorm_kernel_dcmp_64ns_64ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
dcmp_64ns_64ns_1_2_no_dsp_1_U141(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_896_p0),
    .din1(grp_fu_896_p1),
    .ce(1'b1),
    .opcode(grp_fu_896_opcode),
    .dout(grp_fu_896_p2)
);

layernorm_kernel_mul_35s_24s_59_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 35 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 59 ))
mul_35s_24s_59_1_1_U142(
    .din0(shl_ln9_fu_1764_p3),
    .din1(select_ln9_2_reg_2367),
    .dout(mul_ln9_fu_903_p2)
);

layernorm_kernel_mul_59s_24s_72_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 59 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 72 ))
mul_59s_24s_72_5_1_U143(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mul_ln9_reg_2373),
    .din1(select_ln9_2_reg_2367),
    .ce(1'b1),
    .dout(grp_fu_907_p2)
);

layernorm_kernel_mul_72s_24s_72_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 72 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 72 ))
mul_72s_24s_72_5_1_U144(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sub_ln9_1_reg_2394),
    .din1(grp_fu_911_p1),
    .ce(1'b1),
    .dout(grp_fu_911_p2)
);

layernorm_kernel_ctlz_24_24_1_1 #(
    .din_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
ctlz_24_24_1_1_U145(
    .din(tmp_2_fu_1091_p1),
    .dout(tmp_2_fu_1091_p3)
);

layernorm_kernel_ctlz_24_24_1_1 #(
    .din_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
ctlz_24_24_1_1_U146(
    .din(select_ln24_2_reg_2264),
    .dout(tmp_9_fu_1232_p3)
);

layernorm_kernel_ctlz_24_24_1_1 #(
    .din_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
ctlz_24_24_1_1_U147(
    .din(select_ln6_reg_2301),
    .dout(tmp_7_fu_1363_p3)
);

layernorm_kernel_mac_mulsub_18s_18s_30s_36_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 36 ))
mac_mulsub_18s_18s_30s_36_4_1_U148(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1803_p0),
    .din1(grp_fu_1803_p1),
    .din2(shl_ln_fu_1029_p3),
    .ce(1'b1),
    .dout(grp_fu_1803_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_layernorm_kernel_Pipeline_accum_fu_690_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_layernorm_kernel_Pipeline_accum_fu_690_ap_start_reg <= 1'b1;
        end else if ((grp_layernorm_kernel_Pipeline_accum_fu_690_ap_ready == 1'b1)) begin
            grp_layernorm_kernel_Pipeline_accum_fu_690_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_layernorm_kernel_Pipeline_norm_fu_824_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state34)) begin
            grp_layernorm_kernel_Pipeline_norm_fu_824_ap_start_reg <= 1'b1;
        end else if ((grp_layernorm_kernel_Pipeline_norm_fu_824_ap_ready == 1'b1)) begin
            grp_layernorm_kernel_Pipeline_norm_fu_824_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        LD_1_reg_2270 <= LD_1_fu_1319_p5;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        LD_2_reg_2307 <= LD_2_fu_1450_p5;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        LD_reg_2241 <= LD_fu_1179_p5;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        X_0_read_reg_1824 <= X_0;
        X_10_read_reg_1884 <= X_10;
        X_11_read_reg_1890 <= X_11;
        X_12_read_reg_1896 <= X_12;
        X_13_read_reg_1902 <= X_13;
        X_14_read_reg_1908 <= X_14;
        X_15_read_reg_1914 <= X_15;
        X_16_read_reg_1920 <= X_16;
        X_17_read_reg_1926 <= X_17;
        X_18_read_reg_1932 <= X_18;
        X_19_read_reg_1938 <= X_19;
        X_1_read_reg_1830 <= X_1;
        X_20_read_reg_1944 <= X_20;
        X_21_read_reg_1950 <= X_21;
        X_22_read_reg_1956 <= X_22;
        X_23_read_reg_1962 <= X_23;
        X_24_read_reg_1968 <= X_24;
        X_25_read_reg_1974 <= X_25;
        X_26_read_reg_1980 <= X_26;
        X_27_read_reg_1986 <= X_27;
        X_28_read_reg_1992 <= X_28;
        X_29_read_reg_1998 <= X_29;
        X_2_read_reg_1836 <= X_2;
        X_30_read_reg_2004 <= X_30;
        X_31_read_reg_2010 <= X_31;
        X_32_read_reg_2016 <= X_32;
        X_33_read_reg_2022 <= X_33;
        X_34_read_reg_2028 <= X_34;
        X_35_read_reg_2034 <= X_35;
        X_36_read_reg_2040 <= X_36;
        X_37_read_reg_2046 <= X_37;
        X_38_read_reg_2052 <= X_38;
        X_39_read_reg_2058 <= X_39;
        X_3_read_reg_1842 <= X_3;
        X_40_read_reg_2064 <= X_40;
        X_41_read_reg_2070 <= X_41;
        X_42_read_reg_2076 <= X_42;
        X_43_read_reg_2082 <= X_43;
        X_44_read_reg_2088 <= X_44;
        X_45_read_reg_2094 <= X_45;
        X_46_read_reg_2100 <= X_46;
        X_47_read_reg_2106 <= X_47;
        X_48_read_reg_2112 <= X_48;
        X_49_read_reg_2118 <= X_49;
        X_4_read_reg_1848 <= X_4;
        X_50_read_reg_2124 <= X_50;
        X_51_read_reg_2130 <= X_51;
        X_52_read_reg_2136 <= X_52;
        X_53_read_reg_2142 <= X_53;
        X_54_read_reg_2148 <= X_54;
        X_55_read_reg_2154 <= X_55;
        X_56_read_reg_2160 <= X_56;
        X_57_read_reg_2166 <= X_57;
        X_58_read_reg_2172 <= X_58;
        X_59_read_reg_2178 <= X_59;
        X_5_read_reg_1854 <= X_5;
        X_60_read_reg_2184 <= X_60;
        X_61_read_reg_2190 <= X_61;
        X_62_read_reg_2196 <= X_62;
        X_63_read_reg_2202 <= X_63;
        X_6_read_reg_1860 <= X_6;
        X_7_read_reg_1866 <= X_7;
        X_8_read_reg_1872 <= X_8;
        X_9_read_reg_1878 <= X_9;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        add_ln9_1_reg_2329[47 : 16] <= add_ln9_1_fu_1534_p2[47 : 16];
        tmp_16_reg_2322 <= grp_fu_896_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        add_ln9_3_reg_2346[59 : 21] <= add_ln9_3_fu_1632_p2[59 : 21];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        inv_reg_2399 <= {{grp_fu_911_p2[71:48]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mean_reg_2208 <= mean_fu_962_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        mul_ln9_1_reg_2389 <= grp_fu_907_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        mul_ln9_reg_2373 <= mul_ln9_fu_903_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        select_ln24_2_reg_2264 <= select_ln24_2_fu_1226_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        select_ln24_reg_2235 <= select_ln24_fu_1080_p3;
        tmp_6_reg_2230 <= add_ln23_fu_1041_p2[32'd35];
        var_reg_2224 <= {{add_ln23_fu_1041_p2[35:12]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        select_ln6_reg_2301 <= select_ln6_fu_1355_p3;
        tmp_14_reg_2296 <= var_3_fu_1335_p3[32'd23];
        var_3_reg_2285 <= var_3_fu_1335_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        select_ln9_2_reg_2367 <= select_ln9_2_fu_1758_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        select_ln9_reg_2334[47 : 16] <= select_ln9_fu_1551_p3[47 : 16];
        sub_ln9_5_reg_2341[59 : 25] <= sub_ln9_5_fu_1599_p2[59 : 25];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        sext_ln9_8_reg_2383 <= sext_ln9_8_fu_1784_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        sub_ln9_1_reg_2394 <= sub_ln9_1_fu_1788_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        sub_ln9_3_reg_2317[47 : 20] <= sub_ln9_3_fu_1501_p2[47 : 20];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        sub_ln9_7_reg_2357[71 : 30] <= sub_ln9_7_fu_1699_p2[71 : 30];
        sub_ln9_reg_2351[60 : 21] <= sub_ln9_fu_1655_p2[60 : 21];
        tmp_22_reg_2362 <= {{sub_ln9_fu_1655_p2[59:36]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        tmp_10_reg_2258 <= var_1_fu_1206_p3[32'd23];
        var_1_reg_2251 <= var_1_fu_1206_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        tmp_13_reg_2280 <= grp_fu_896_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

always @ (*) begin
    if ((grp_layernorm_kernel_Pipeline_accum_fu_690_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

always @ (*) begin
    if ((grp_layernorm_kernel_Pipeline_norm_fu_824_ap_done == 1'b0)) begin
        ap_ST_fsm_state35_blk = 1'b1;
    end else begin
        ap_ST_fsm_state35_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((grp_layernorm_kernel_Pipeline_norm_fu_824_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state35))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_layernorm_kernel_Pipeline_norm_fu_824_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state35))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_896_opcode = 5'd2;
    end else if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state8))) begin
        grp_fu_896_opcode = 5'd4;
    end else begin
        grp_fu_896_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_896_p0 = bitcast_ln758_2_fu_1462_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_896_p0 = bitcast_ln758_1_fu_1331_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_896_p0 = bitcast_ln758_fu_1191_p1;
    end else begin
        grp_fu_896_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_896_p1 = 64'd4607182418800017408;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_896_p1 = 64'd4620693217682128896;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_896_p1 = 64'd4602678819172646912;
    end else begin
        grp_fu_896_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_layernorm_kernel_Pipeline_accum_fu_690_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            if (((grp_layernorm_kernel_Pipeline_norm_fu_824_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state35))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state35;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign LD_1_fu_1319_p5 = {{tmp_4_fu_1312_p3}, {zext_ln24_5_fu_1276_p1[51:0]}};

assign LD_2_fu_1450_p5 = {{tmp_11_fu_1443_p3}, {zext_ln6_2_fu_1407_p1[51:0]}};

assign LD_fu_1179_p5 = {{tmp_3_fu_1172_p3}, {zext_ln24_4_fu_1136_p1[51:0]}};

assign Y_address0 = grp_layernorm_kernel_Pipeline_norm_fu_824_Y_address0;

assign Y_ce0 = grp_layernorm_kernel_Pipeline_norm_fu_824_Y_ce0;

assign Y_d0 = grp_layernorm_kernel_Pipeline_norm_fu_824_Y_d0;

assign Y_we0 = grp_layernorm_kernel_Pipeline_norm_fu_824_Y_we0;

assign add_ln23_fu_1041_p2 = ($signed(grp_fu_1803_p3) + $signed(36'd1048576));

assign add_ln24_1_fu_1166_p2 = ($signed(sext_ln24_fu_1162_p1) + $signed(select_ln24_1_fu_1148_p3));

assign add_ln24_2_fu_1250_p2 = (trunc_ln24_2_fu_1239_p1 + 6'd30);

assign add_ln24_3_fu_1306_p2 = ($signed(sext_ln24_1_fu_1302_p1) + $signed(select_ln24_3_fu_1288_p3));

assign add_ln24_fu_1110_p2 = (trunc_ln24_fu_1099_p1 + 6'd30);

assign add_ln6_1_fu_1437_p2 = ($signed(sext_ln6_fu_1433_p1) + $signed(select_ln6_1_fu_1419_p3));

assign add_ln6_fu_1381_p2 = (trunc_ln6_fu_1370_p1 + 6'd30);

assign add_ln9_1_fu_1534_p2 = ($signed(add_ln9_fu_1518_p2) + $signed(sext_ln9_9_fu_1530_p1));

assign add_ln9_2_fu_1616_p2 = ($signed(sub_ln9_5_reg_2341) + $signed(sext_ln9_12_fu_1612_p1));

assign add_ln9_3_fu_1632_p2 = ($signed(add_ln9_2_fu_1616_p2) + $signed(sext_ln9_13_fu_1628_p1));

assign add_ln9_4_fu_1726_p2 = ($signed(sub_ln9_7_reg_2357) + $signed(sext_ln9_15_fu_1722_p1));

assign add_ln9_5_fu_1742_p2 = ($signed(add_ln9_4_fu_1726_p2) + $signed(sext_ln9_16_fu_1738_p1));

assign add_ln9_fu_1518_p2 = ($signed(sub_ln9_3_reg_2317) + $signed(sext_ln9_5_fu_1514_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign bitcast_ln758_1_fu_1331_p1 = LD_1_reg_2270;

assign bitcast_ln758_2_fu_1462_p1 = LD_2_reg_2307;

assign bitcast_ln758_fu_1191_p1 = LD_reg_2241;

assign empty_fu_1200_p2 = (icmp_ln24_fu_1195_p2 | grp_fu_896_p2);

assign grp_fu_1803_p0 = sext_ln23_1_fu_970_p1;

assign grp_fu_1803_p1 = sext_ln23_1_fu_970_p1;

assign grp_fu_911_p1 = sext_ln9_8_reg_2383;

assign grp_layernorm_kernel_Pipeline_accum_fu_690_ap_start = grp_layernorm_kernel_Pipeline_accum_fu_690_ap_start_reg;

assign grp_layernorm_kernel_Pipeline_norm_fu_824_ap_start = grp_layernorm_kernel_Pipeline_norm_fu_824_ap_start_reg;

assign icmp_ln24_fu_1195_p2 = ((var_reg_2224 == 24'd0) ? 1'b1 : 1'b0);

assign lshr_ln24_1_fu_1266_p4 = {{shl_ln24_1_fu_1260_p2[63:1]}};

assign lshr_ln6_fu_1397_p4 = {{shl_ln6_fu_1391_p2[63:1]}};

assign lshr_ln_fu_1126_p4 = {{shl_ln24_fu_1120_p2[63:1]}};

assign mean_fu_962_p3 = ((tmp_fu_922_p3[0:0] == 1'b1) ? sub_ln22_1_fu_956_p2 : zext_ln_fu_946_p4);

assign p_shl1_fu_1466_p3 = {{var_3_reg_2285}, {24'd0}};

assign p_shl2_fu_1561_p3 = {{trunc_ln9_fu_1557_p1}, {13'd0}};

assign p_shl3_fu_1673_p3 = {{sub_ln9_fu_1655_p2}, {11'd0}};

assign p_shl_fu_1665_p3 = {{trunc_ln9_1_fu_1661_p1}, {13'd0}};

assign select_ln23_fu_1021_p3 = ((tmp_5_fu_981_p3[0:0] == 1'b1) ? sub_ln23_2_fu_1005_p2 : zext_ln1_fu_1011_p4);

assign select_ln24_1_fu_1148_p3 = ((tmp_8_fu_1140_p3[0:0] == 1'b1) ? 11'd1023 : 11'd1022);

assign select_ln24_2_fu_1226_p3 = ((tmp_10_reg_2258[0:0] == 1'b1) ? sub_ln24_2_fu_1221_p2 : var_1_reg_2251);

assign select_ln24_3_fu_1288_p3 = ((tmp_12_fu_1280_p3[0:0] == 1'b1) ? 11'd1023 : 11'd1022);

assign select_ln24_fu_1080_p3 = ((tmp_6_fu_1066_p3[0:0] == 1'b1) ? sub_ln24_fu_1074_p2 : var_cast_fu_1056_p4);

assign select_ln6_1_fu_1419_p3 = ((tmp_15_fu_1411_p3[0:0] == 1'b1) ? 11'd1023 : 11'd1022);

assign select_ln6_fu_1355_p3 = ((tmp_14_fu_1341_p3[0:0] == 1'b1) ? sub_ln6_fu_1349_p2 : var_3_fu_1335_p3);

assign select_ln9_1_fu_1645_p3 = ((tmp_16_reg_2322[0:0] == 1'b1) ? add_ln9_3_reg_2346 : shl_ln9_2_fu_1638_p3);

assign select_ln9_2_fu_1758_p3 = ((tmp_16_reg_2322[0:0] == 1'b1) ? tmp_21_fu_1748_p4 : tmp_22_reg_2362);

assign select_ln9_fu_1551_p3 = ((tmp_16_reg_2322[0:0] == 1'b1) ? add_ln9_1_reg_2329 : sext_ln9_2_fu_1547_p1);

assign sext_ln22_fu_918_p0 = grp_layernorm_kernel_Pipeline_accum_fu_690_sum_out;

assign sext_ln22_fu_918_p1 = sext_ln22_fu_918_p0;

assign sext_ln23_1_fu_970_p1 = mean_fu_962_p3;

assign sext_ln23_fu_977_p0 = grp_layernorm_kernel_Pipeline_accum_fu_690_sq_sum_out;

assign sext_ln23_fu_977_p1 = sext_ln23_fu_977_p0;

assign sext_ln24_1_fu_1302_p1 = $signed(sub_ln24_3_fu_1296_p2);

assign sext_ln24_fu_1162_p1 = $signed(sub_ln24_1_fu_1156_p2);

assign sext_ln6_fu_1433_p1 = $signed(sub_ln6_1_fu_1427_p2);

assign sext_ln9_10_fu_1577_p1 = $signed(tmp_23_fu_1569_p3);

assign sext_ln9_11_fu_1595_p1 = $signed(tmp_24_fu_1587_p3);

assign sext_ln9_12_fu_1612_p1 = $signed(tmp_25_fu_1605_p3);

assign sext_ln9_13_fu_1628_p1 = $signed(tmp_26_fu_1621_p3);

assign sext_ln9_14_fu_1695_p1 = $signed(tmp_27_fu_1687_p3);

assign sext_ln9_15_fu_1722_p1 = $signed(tmp_28_fu_1715_p3);

assign sext_ln9_16_fu_1738_p1 = $signed(tmp_29_fu_1731_p3);

assign sext_ln9_1_fu_1480_p1 = $signed(tmp_17_fu_1473_p3);

assign sext_ln9_2_fu_1547_p1 = $signed(shl_ln9_1_fu_1540_p3);

assign sext_ln9_3_fu_1497_p1 = $signed(tmp_18_fu_1490_p3);

assign sext_ln9_4_fu_1651_p1 = $signed(select_ln9_1_fu_1645_p3);

assign sext_ln9_5_fu_1514_p1 = $signed(tmp_19_fu_1507_p3);

assign sext_ln9_8_fu_1784_p1 = select_ln9_2_reg_2367;

assign sext_ln9_9_fu_1530_p1 = $signed(tmp_20_fu_1523_p3);

assign shl_ln24_1_fu_1260_p2 = zext_ln24_2_fu_1247_p1 << zext_ln24_3_fu_1256_p1;

assign shl_ln24_fu_1120_p2 = zext_ln24_fu_1107_p1 << zext_ln24_1_fu_1116_p1;

assign shl_ln6_fu_1391_p2 = zext_ln6_fu_1378_p1 << zext_ln6_1_fu_1387_p1;

assign shl_ln9_1_fu_1540_p3 = {{var_3_reg_2285}, {23'd0}};

assign shl_ln9_2_fu_1638_p3 = {{select_ln9_reg_2334}, {12'd0}};

assign shl_ln9_fu_1764_p3 = {{var_3_reg_2285}, {11'd0}};

assign shl_ln_fu_1029_p3 = {{select_ln23_fu_1021_p3}, {12'd0}};

assign sub_ln22_1_fu_956_p2 = (18'd0 - tmp_19_cast_fu_936_p4);

assign sub_ln22_fu_930_p2 = ($signed(25'd0) - $signed(sext_ln22_fu_918_p1));

assign sub_ln23_1_fu_989_p2 = ($signed(25'd0) - $signed(sext_ln23_fu_977_p1));

assign sub_ln23_2_fu_1005_p2 = (18'd0 - tmp_20_cast_fu_995_p4);

assign sub_ln24_1_fu_1156_p2 = (5'd12 - trunc_ln24_1_fu_1103_p1);

assign sub_ln24_2_fu_1221_p2 = (24'd0 - var_1_reg_2251);

assign sub_ln24_3_fu_1296_p2 = (5'd12 - trunc_ln24_3_fu_1243_p1);

assign sub_ln24_fu_1074_p2 = (23'd0 - var_cast_fu_1056_p4);

assign sub_ln6_1_fu_1427_p2 = (5'd12 - trunc_ln6_1_fu_1374_p1);

assign sub_ln6_fu_1349_p2 = (24'd0 - var_3_fu_1335_p3);

assign sub_ln9_1_fu_1788_p2 = (72'd422212465065984 - mul_ln9_1_reg_2389);

assign sub_ln9_2_fu_1484_p2 = ($signed(p_shl1_fu_1466_p3) - $signed(sext_ln9_1_fu_1480_p1));

assign sub_ln9_3_fu_1501_p2 = ($signed(sub_ln9_2_fu_1484_p2) - $signed(sext_ln9_3_fu_1497_p1));

assign sub_ln9_4_fu_1581_p2 = ($signed(p_shl2_fu_1561_p3) - $signed(sext_ln9_10_fu_1577_p1));

assign sub_ln9_5_fu_1599_p2 = ($signed(sub_ln9_4_fu_1581_p2) - $signed(sext_ln9_11_fu_1595_p1));

assign sub_ln9_6_fu_1681_p2 = (p_shl_fu_1665_p3 - p_shl3_fu_1673_p3);

assign sub_ln9_7_fu_1699_p2 = ($signed(sub_ln9_6_fu_1681_p2) - $signed(sext_ln9_14_fu_1695_p1));

assign sub_ln9_fu_1655_p2 = ($signed(61'd422212465065984) - $signed(sext_ln9_4_fu_1651_p1));

assign tmp_11_fu_1443_p3 = {{tmp_14_reg_2296}, {add_ln6_1_fu_1437_p2}};

assign tmp_12_fu_1280_p3 = shl_ln24_1_fu_1260_p2[32'd54];

assign tmp_14_fu_1341_p3 = var_3_fu_1335_p3[32'd23];

assign tmp_15_fu_1411_p3 = shl_ln6_fu_1391_p2[32'd54];

assign tmp_17_fu_1473_p3 = {{var_3_reg_2285}, {22'd0}};

assign tmp_18_fu_1490_p3 = {{var_3_reg_2285}, {20'd0}};

assign tmp_19_cast_fu_936_p4 = {{sub_ln22_fu_930_p2[23:6]}};

assign tmp_19_fu_1507_p3 = {{var_3_reg_2285}, {18'd0}};

assign tmp_20_cast_fu_995_p4 = {{sub_ln23_1_fu_989_p2[23:6]}};

assign tmp_20_fu_1523_p3 = {{var_3_reg_2285}, {16'd0}};

assign tmp_21_fu_1748_p4 = {{add_ln9_5_fu_1742_p2[71:48]}};

assign tmp_23_fu_1569_p3 = {{select_ln9_fu_1551_p3}, {11'd0}};

assign tmp_24_fu_1587_p3 = {{select_ln9_fu_1551_p3}, {9'd0}};

assign tmp_25_fu_1605_p3 = {{select_ln9_reg_2334}, {7'd0}};

assign tmp_26_fu_1621_p3 = {{select_ln9_reg_2334}, {5'd0}};

assign tmp_27_fu_1687_p3 = {{sub_ln9_fu_1655_p2}, {9'd0}};

assign tmp_28_fu_1715_p3 = {{sub_ln9_reg_2351}, {7'd0}};

assign tmp_29_fu_1731_p3 = {{sub_ln9_reg_2351}, {5'd0}};

assign tmp_2_fu_1091_p1 = select_ln24_reg_2235;

assign tmp_3_fu_1172_p3 = {{tmp_6_reg_2230}, {add_ln24_1_fu_1166_p2}};

assign tmp_4_fu_1312_p3 = {{tmp_10_reg_2258}, {add_ln24_3_fu_1306_p2}};

assign tmp_5_fu_981_p1 = grp_layernorm_kernel_Pipeline_accum_fu_690_sq_sum_out;

assign tmp_5_fu_981_p3 = tmp_5_fu_981_p1[32'd23];

assign tmp_6_fu_1066_p3 = add_ln23_fu_1041_p2[32'd35];

assign tmp_8_fu_1140_p3 = shl_ln24_fu_1120_p2[32'd54];

assign tmp_fu_922_p1 = grp_layernorm_kernel_Pipeline_accum_fu_690_sum_out;

assign tmp_fu_922_p3 = tmp_fu_922_p1[32'd23];

assign trunc_ln24_1_fu_1103_p1 = tmp_2_fu_1091_p3[4:0];

assign trunc_ln24_2_fu_1239_p1 = tmp_9_fu_1232_p3[5:0];

assign trunc_ln24_3_fu_1243_p1 = tmp_9_fu_1232_p3[4:0];

assign trunc_ln24_fu_1099_p1 = tmp_2_fu_1091_p3[5:0];

assign trunc_ln6_1_fu_1374_p1 = tmp_7_fu_1363_p3[4:0];

assign trunc_ln6_fu_1370_p1 = tmp_7_fu_1363_p3[5:0];

assign trunc_ln9_1_fu_1661_p1 = sub_ln9_fu_1655_p2[58:0];

assign trunc_ln9_fu_1557_p1 = select_ln9_fu_1551_p3[46:0];

assign var_1_fu_1206_p3 = ((empty_fu_1200_p2[0:0] == 1'b1) ? 24'd2048 : var_reg_2224);

assign var_3_fu_1335_p3 = ((tmp_13_reg_2280[0:0] == 1'b1) ? 24'd32768 : var_1_reg_2251);

assign var_cast_fu_1056_p4 = {{add_ln23_fu_1041_p2[34:12]}};

assign zext_ln1_fu_1011_p1 = grp_layernorm_kernel_Pipeline_accum_fu_690_sq_sum_out;

assign zext_ln1_fu_1011_p4 = {{zext_ln1_fu_1011_p1[23:6]}};

assign zext_ln24_1_fu_1116_p1 = add_ln24_fu_1110_p2;

assign zext_ln24_2_fu_1247_p1 = select_ln24_2_reg_2264;

assign zext_ln24_3_fu_1256_p1 = add_ln24_2_fu_1250_p2;

assign zext_ln24_4_fu_1136_p1 = lshr_ln_fu_1126_p4;

assign zext_ln24_5_fu_1276_p1 = lshr_ln24_1_fu_1266_p4;

assign zext_ln24_fu_1107_p1 = select_ln24_reg_2235;

assign zext_ln6_1_fu_1387_p1 = add_ln6_fu_1381_p2;

assign zext_ln6_2_fu_1407_p1 = lshr_ln6_fu_1397_p4;

assign zext_ln6_fu_1378_p1 = select_ln6_reg_2301;

assign zext_ln_fu_946_p1 = grp_layernorm_kernel_Pipeline_accum_fu_690_sum_out;

assign zext_ln_fu_946_p4 = {{zext_ln_fu_946_p1[23:6]}};

always @ (posedge ap_clk) begin
    sub_ln9_3_reg_2317[19:0] <= 20'b00000000000000000000;
    add_ln9_1_reg_2329[15:0] <= 16'b0000000000000000;
    select_ln9_reg_2334[15:0] <= 16'b0000000000000000;
    sub_ln9_5_reg_2341[24:0] <= 25'b0000000000000000000000000;
    add_ln9_3_reg_2346[20:0] <= 21'b000000000000000000000;
    sub_ln9_reg_2351[20:0] <= 21'b000000000000000000000;
    sub_ln9_7_reg_2357[29:0] <= 30'b000000000000000000000000000000;
end

endmodule //layernorm_kernel
