-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity gelu_embed_kernel is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    X_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    X_ce0 : OUT STD_LOGIC;
    X_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    token_ids_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    token_ids_ce0 : OUT STD_LOGIC;
    token_ids_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_0 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_4 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_5 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_6 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_7 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_8 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_9 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_10 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_11 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_12 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_13 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_14 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_15 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_16 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_17 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_18 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_19 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_20 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_21 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_22 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_23 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_24 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_25 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_26 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_27 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_28 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_29 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_30 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_31 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_32 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_33 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_34 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_35 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_36 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_37 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_38 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_39 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_40 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_41 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_42 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_43 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_44 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_45 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_46 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_47 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_48 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_49 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_50 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_51 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_52 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_53 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_54 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_55 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_56 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_57 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_58 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_59 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_60 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_61 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_62 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_63 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_64 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_65 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_66 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_67 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_68 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_69 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_70 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_71 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_72 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_73 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_74 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_75 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_76 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_77 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_78 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_79 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_80 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_81 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_82 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_83 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_84 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_85 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_86 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_87 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_88 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_89 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_90 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_91 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_92 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_93 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_94 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_95 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_96 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_97 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_98 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_99 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_100 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_101 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_102 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_103 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_104 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_105 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_106 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_107 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_108 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_109 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_110 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_111 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_112 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_113 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_114 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_115 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_116 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_117 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_118 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_119 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_120 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_121 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_122 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_123 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_124 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_125 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_126 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_127 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_128 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_129 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_130 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_131 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_132 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_133 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_134 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_135 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_136 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_137 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_138 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_139 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_140 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_141 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_142 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_143 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_144 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_145 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_146 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_147 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_148 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_149 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_150 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_151 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_152 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_153 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_154 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_155 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_156 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_157 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_158 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_159 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_160 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_161 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_162 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_163 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_164 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_165 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_166 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_167 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_168 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_169 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_170 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_171 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_172 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_173 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_174 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_175 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_176 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_177 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_178 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_179 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_180 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_181 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_182 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_183 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_184 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_185 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_186 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_187 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_188 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_189 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_190 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_191 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_192 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_193 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_194 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_195 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_196 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_197 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_198 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_199 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_200 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_201 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_202 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_203 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_204 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_205 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_206 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_207 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_208 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_209 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_210 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_211 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_212 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_213 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_214 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_215 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_216 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_217 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_218 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_219 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_220 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_221 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_222 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_223 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_224 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_225 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_226 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_227 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_228 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_229 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_230 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_231 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_232 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_233 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_234 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_235 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_236 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_237 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_238 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_239 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_240 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_241 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_242 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_243 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_244 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_245 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_246 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_247 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_248 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_249 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_250 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_251 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_252 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_253 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_254 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_lut_255 : IN STD_LOGIC_VECTOR (7 downto 0);
    embed_lut_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    embed_lut_0_ce0 : OUT STD_LOGIC;
    embed_lut_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    embed_lut_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    embed_lut_1_ce0 : OUT STD_LOGIC;
    embed_lut_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    embed_lut_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    embed_lut_2_ce0 : OUT STD_LOGIC;
    embed_lut_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    embed_lut_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    embed_lut_3_ce0 : OUT STD_LOGIC;
    embed_lut_3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    embed_lut_4_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    embed_lut_4_ce0 : OUT STD_LOGIC;
    embed_lut_4_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    embed_lut_5_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    embed_lut_5_ce0 : OUT STD_LOGIC;
    embed_lut_5_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    embed_lut_6_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    embed_lut_6_ce0 : OUT STD_LOGIC;
    embed_lut_6_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    embed_lut_7_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    embed_lut_7_ce0 : OUT STD_LOGIC;
    embed_lut_7_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    gelu_out_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    gelu_out_ce0 : OUT STD_LOGIC;
    gelu_out_we0 : OUT STD_LOGIC;
    gelu_out_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    embed_out_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    embed_out_ce0 : OUT STD_LOGIC;
    embed_out_we0 : OUT STD_LOGIC;
    embed_out_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of gelu_embed_kernel is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "gelu_embed_kernel_gelu_embed_kernel,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.912000,HLS_SYN_LAT=67,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2092,HLS_SYN_LUT=1513,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal gelu_lut_0_read_reg_2640 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_1_read_reg_2645 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_2_read_reg_2650 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_3_read_reg_2655 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_4_read_reg_2660 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_5_read_reg_2665 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_6_read_reg_2670 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_7_read_reg_2675 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_8_read_reg_2680 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_9_read_reg_2685 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_10_read_reg_2690 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_11_read_reg_2695 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_12_read_reg_2700 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_13_read_reg_2705 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_14_read_reg_2710 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_15_read_reg_2715 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_16_read_reg_2720 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_17_read_reg_2725 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_18_read_reg_2730 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_19_read_reg_2735 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_20_read_reg_2740 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_21_read_reg_2745 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_22_read_reg_2750 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_23_read_reg_2755 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_24_read_reg_2760 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_25_read_reg_2765 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_26_read_reg_2770 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_27_read_reg_2775 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_28_read_reg_2780 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_29_read_reg_2785 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_30_read_reg_2790 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_31_read_reg_2795 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_32_read_reg_2800 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_33_read_reg_2805 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_34_read_reg_2810 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_35_read_reg_2815 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_36_read_reg_2820 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_37_read_reg_2825 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_38_read_reg_2830 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_39_read_reg_2835 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_40_read_reg_2840 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_41_read_reg_2845 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_42_read_reg_2850 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_43_read_reg_2855 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_44_read_reg_2860 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_45_read_reg_2865 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_46_read_reg_2870 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_47_read_reg_2875 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_48_read_reg_2880 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_49_read_reg_2885 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_50_read_reg_2890 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_51_read_reg_2895 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_52_read_reg_2900 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_53_read_reg_2905 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_54_read_reg_2910 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_55_read_reg_2915 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_56_read_reg_2920 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_57_read_reg_2925 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_58_read_reg_2930 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_59_read_reg_2935 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_60_read_reg_2940 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_61_read_reg_2945 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_62_read_reg_2950 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_63_read_reg_2955 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_64_read_reg_2960 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_65_read_reg_2965 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_66_read_reg_2970 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_67_read_reg_2975 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_68_read_reg_2980 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_69_read_reg_2985 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_70_read_reg_2990 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_71_read_reg_2995 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_72_read_reg_3000 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_73_read_reg_3005 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_74_read_reg_3010 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_75_read_reg_3015 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_76_read_reg_3020 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_77_read_reg_3025 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_78_read_reg_3030 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_79_read_reg_3035 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_80_read_reg_3040 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_81_read_reg_3045 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_82_read_reg_3050 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_83_read_reg_3055 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_84_read_reg_3060 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_85_read_reg_3065 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_86_read_reg_3070 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_87_read_reg_3075 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_88_read_reg_3080 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_89_read_reg_3085 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_90_read_reg_3090 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_91_read_reg_3095 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_92_read_reg_3100 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_93_read_reg_3105 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_94_read_reg_3110 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_95_read_reg_3115 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_96_read_reg_3120 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_97_read_reg_3125 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_98_read_reg_3130 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_99_read_reg_3135 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_100_read_reg_3140 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_101_read_reg_3145 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_102_read_reg_3150 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_103_read_reg_3155 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_104_read_reg_3160 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_105_read_reg_3165 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_106_read_reg_3170 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_107_read_reg_3175 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_108_read_reg_3180 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_109_read_reg_3185 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_110_read_reg_3190 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_111_read_reg_3195 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_112_read_reg_3200 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_113_read_reg_3205 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_114_read_reg_3210 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_115_read_reg_3215 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_116_read_reg_3220 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_117_read_reg_3225 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_118_read_reg_3230 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_119_read_reg_3235 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_120_read_reg_3240 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_121_read_reg_3245 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_122_read_reg_3250 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_123_read_reg_3255 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_124_read_reg_3260 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_125_read_reg_3265 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_126_read_reg_3270 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_127_read_reg_3275 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_128_read_reg_3280 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_129_read_reg_3285 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_130_read_reg_3290 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_131_read_reg_3295 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_132_read_reg_3300 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_133_read_reg_3305 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_134_read_reg_3310 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_135_read_reg_3315 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_136_read_reg_3320 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_137_read_reg_3325 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_138_read_reg_3330 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_139_read_reg_3335 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_140_read_reg_3340 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_141_read_reg_3345 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_142_read_reg_3350 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_143_read_reg_3355 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_144_read_reg_3360 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_145_read_reg_3365 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_146_read_reg_3370 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_147_read_reg_3375 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_148_read_reg_3380 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_149_read_reg_3385 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_150_read_reg_3390 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_151_read_reg_3395 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_152_read_reg_3400 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_153_read_reg_3405 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_154_read_reg_3410 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_155_read_reg_3415 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_156_read_reg_3420 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_157_read_reg_3425 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_158_read_reg_3430 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_159_read_reg_3435 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_160_read_reg_3440 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_161_read_reg_3445 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_162_read_reg_3450 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_163_read_reg_3455 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_164_read_reg_3460 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_165_read_reg_3465 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_166_read_reg_3470 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_167_read_reg_3475 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_168_read_reg_3480 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_169_read_reg_3485 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_170_read_reg_3490 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_171_read_reg_3495 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_172_read_reg_3500 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_173_read_reg_3505 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_174_read_reg_3510 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_175_read_reg_3515 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_176_read_reg_3520 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_177_read_reg_3525 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_178_read_reg_3530 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_179_read_reg_3535 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_180_read_reg_3540 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_181_read_reg_3545 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_182_read_reg_3550 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_183_read_reg_3555 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_184_read_reg_3560 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_185_read_reg_3565 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_186_read_reg_3570 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_187_read_reg_3575 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_188_read_reg_3580 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_189_read_reg_3585 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_190_read_reg_3590 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_191_read_reg_3595 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_192_read_reg_3600 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_193_read_reg_3605 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_194_read_reg_3610 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_195_read_reg_3615 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_196_read_reg_3620 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_197_read_reg_3625 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_198_read_reg_3630 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_199_read_reg_3635 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_200_read_reg_3640 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_201_read_reg_3645 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_202_read_reg_3650 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_203_read_reg_3655 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_204_read_reg_3660 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_205_read_reg_3665 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_206_read_reg_3670 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_207_read_reg_3675 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_208_read_reg_3680 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_209_read_reg_3685 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_210_read_reg_3690 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_211_read_reg_3695 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_212_read_reg_3700 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_213_read_reg_3705 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_214_read_reg_3710 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_215_read_reg_3715 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_216_read_reg_3720 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_217_read_reg_3725 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_218_read_reg_3730 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_219_read_reg_3735 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_220_read_reg_3740 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_221_read_reg_3745 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_222_read_reg_3750 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_223_read_reg_3755 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_224_read_reg_3760 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_225_read_reg_3765 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_226_read_reg_3770 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_227_read_reg_3775 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_228_read_reg_3780 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_229_read_reg_3785 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_230_read_reg_3790 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_231_read_reg_3795 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_232_read_reg_3800 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_233_read_reg_3805 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_234_read_reg_3810 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_235_read_reg_3815 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_236_read_reg_3820 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_237_read_reg_3825 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_238_read_reg_3830 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_239_read_reg_3835 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_240_read_reg_3840 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_241_read_reg_3845 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_242_read_reg_3850 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_243_read_reg_3855 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_244_read_reg_3860 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_245_read_reg_3865 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_246_read_reg_3870 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_247_read_reg_3875 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_248_read_reg_3880 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_249_read_reg_3885 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_250_read_reg_3890 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_251_read_reg_3895 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_252_read_reg_3900 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_253_read_reg_3905 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_254_read_reg_3910 : STD_LOGIC_VECTOR (7 downto 0);
    signal gelu_lut_255_read_reg_3915 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_ap_start : STD_LOGIC;
    signal grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_ap_done : STD_LOGIC;
    signal grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_ap_idle : STD_LOGIC;
    signal grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_ap_ready : STD_LOGIC;
    signal grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_X_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_X_ce0 : STD_LOGIC;
    signal grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_gelu_out_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_gelu_out_ce0 : STD_LOGIC;
    signal grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_gelu_out_we0 : STD_LOGIC;
    signal grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_gelu_out_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_gelu_embed_kernel_Pipeline_embed_fu_2616_ap_start : STD_LOGIC;
    signal grp_gelu_embed_kernel_Pipeline_embed_fu_2616_ap_done : STD_LOGIC;
    signal grp_gelu_embed_kernel_Pipeline_embed_fu_2616_ap_idle : STD_LOGIC;
    signal grp_gelu_embed_kernel_Pipeline_embed_fu_2616_ap_ready : STD_LOGIC;
    signal grp_gelu_embed_kernel_Pipeline_embed_fu_2616_token_ids_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_gelu_embed_kernel_Pipeline_embed_fu_2616_token_ids_ce0 : STD_LOGIC;
    signal grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_0_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_0_ce0 : STD_LOGIC;
    signal grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_1_ce0 : STD_LOGIC;
    signal grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_2_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_2_ce0 : STD_LOGIC;
    signal grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_3_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_3_ce0 : STD_LOGIC;
    signal grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_4_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_4_ce0 : STD_LOGIC;
    signal grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_5_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_5_ce0 : STD_LOGIC;
    signal grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_6_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_6_ce0 : STD_LOGIC;
    signal grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_7_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_7_ce0 : STD_LOGIC;
    signal grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_out_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_out_ce0 : STD_LOGIC;
    signal grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_out_we0 : STD_LOGIC;
    signal grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_out_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_gelu_embed_kernel_Pipeline_embed_fu_2616_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component gelu_embed_kernel_gelu_embed_kernel_Pipeline_gelu IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        X_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        X_ce0 : OUT STD_LOGIC;
        X_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_0_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_1_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_2_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_3_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_4_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_5_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_6_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_7_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_8_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_9_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_10_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_11_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_12_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_13_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_14_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_15_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_16_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_17_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_18_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_19_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_20_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_21_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_22_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_23_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_24_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_25_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_26_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_27_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_28_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_29_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_30_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_31_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_32_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_33_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_34_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_35_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_36_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_37_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_38_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_39_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_40_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_41_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_42_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_43_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_44_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_45_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_46_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_47_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_48_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_49_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_50_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_51_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_52_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_53_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_54_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_55_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_56_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_57_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_58_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_59_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_60_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_61_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_62_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_63_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_64_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_65_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_66_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_67_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_68_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_69_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_70_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_71_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_72_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_73_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_74_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_75_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_76_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_77_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_78_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_79_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_80_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_81_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_82_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_83_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_84_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_85_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_86_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_87_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_88_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_89_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_90_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_91_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_92_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_93_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_94_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_95_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_96_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_97_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_98_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_99_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_100_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_101_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_102_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_103_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_104_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_105_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_106_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_107_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_108_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_109_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_110_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_111_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_112_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_113_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_114_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_115_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_116_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_117_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_118_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_119_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_120_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_121_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_122_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_123_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_124_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_125_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_126_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_127_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_128_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_129_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_130_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_131_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_132_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_133_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_134_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_135_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_136_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_137_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_138_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_139_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_140_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_141_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_142_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_143_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_144_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_145_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_146_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_147_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_148_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_149_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_150_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_151_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_152_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_153_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_154_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_155_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_156_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_157_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_158_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_159_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_160_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_161_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_162_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_163_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_164_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_165_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_166_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_167_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_168_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_169_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_170_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_171_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_172_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_173_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_174_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_175_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_176_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_177_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_178_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_179_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_180_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_181_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_182_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_183_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_184_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_185_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_186_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_187_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_188_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_189_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_190_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_191_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_192_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_193_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_194_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_195_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_196_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_197_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_198_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_199_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_200_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_201_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_202_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_203_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_204_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_205_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_206_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_207_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_208_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_209_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_210_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_211_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_212_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_213_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_214_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_215_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_216_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_217_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_218_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_219_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_220_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_221_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_222_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_223_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_224_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_225_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_226_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_227_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_228_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_229_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_230_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_231_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_232_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_233_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_234_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_235_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_236_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_237_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_238_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_239_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_240_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_241_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_242_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_243_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_244_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_245_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_246_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_247_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_248_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_249_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_250_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_251_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_252_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_253_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_254_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_lut_255_load : IN STD_LOGIC_VECTOR (7 downto 0);
        gelu_out_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        gelu_out_ce0 : OUT STD_LOGIC;
        gelu_out_we0 : OUT STD_LOGIC;
        gelu_out_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component gelu_embed_kernel_gelu_embed_kernel_Pipeline_embed IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        token_ids_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        token_ids_ce0 : OUT STD_LOGIC;
        token_ids_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        embed_lut_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        embed_lut_0_ce0 : OUT STD_LOGIC;
        embed_lut_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        embed_lut_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        embed_lut_1_ce0 : OUT STD_LOGIC;
        embed_lut_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        embed_lut_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        embed_lut_2_ce0 : OUT STD_LOGIC;
        embed_lut_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        embed_lut_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        embed_lut_3_ce0 : OUT STD_LOGIC;
        embed_lut_3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        embed_lut_4_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        embed_lut_4_ce0 : OUT STD_LOGIC;
        embed_lut_4_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        embed_lut_5_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        embed_lut_5_ce0 : OUT STD_LOGIC;
        embed_lut_5_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        embed_lut_6_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        embed_lut_6_ce0 : OUT STD_LOGIC;
        embed_lut_6_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        embed_lut_7_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        embed_lut_7_ce0 : OUT STD_LOGIC;
        embed_lut_7_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        embed_out_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        embed_out_ce0 : OUT STD_LOGIC;
        embed_out_we0 : OUT STD_LOGIC;
        embed_out_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    grp_gelu_embed_kernel_Pipeline_gelu_fu_2096 : component gelu_embed_kernel_gelu_embed_kernel_Pipeline_gelu
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_ap_start,
        ap_done => grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_ap_done,
        ap_idle => grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_ap_idle,
        ap_ready => grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_ap_ready,
        X_address0 => grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_X_address0,
        X_ce0 => grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_X_ce0,
        X_q0 => X_q0,
        gelu_lut_0_load => gelu_lut_0_read_reg_2640,
        gelu_lut_1_load => gelu_lut_1_read_reg_2645,
        gelu_lut_2_load => gelu_lut_2_read_reg_2650,
        gelu_lut_3_load => gelu_lut_3_read_reg_2655,
        gelu_lut_4_load => gelu_lut_4_read_reg_2660,
        gelu_lut_5_load => gelu_lut_5_read_reg_2665,
        gelu_lut_6_load => gelu_lut_6_read_reg_2670,
        gelu_lut_7_load => gelu_lut_7_read_reg_2675,
        gelu_lut_8_load => gelu_lut_8_read_reg_2680,
        gelu_lut_9_load => gelu_lut_9_read_reg_2685,
        gelu_lut_10_load => gelu_lut_10_read_reg_2690,
        gelu_lut_11_load => gelu_lut_11_read_reg_2695,
        gelu_lut_12_load => gelu_lut_12_read_reg_2700,
        gelu_lut_13_load => gelu_lut_13_read_reg_2705,
        gelu_lut_14_load => gelu_lut_14_read_reg_2710,
        gelu_lut_15_load => gelu_lut_15_read_reg_2715,
        gelu_lut_16_load => gelu_lut_16_read_reg_2720,
        gelu_lut_17_load => gelu_lut_17_read_reg_2725,
        gelu_lut_18_load => gelu_lut_18_read_reg_2730,
        gelu_lut_19_load => gelu_lut_19_read_reg_2735,
        gelu_lut_20_load => gelu_lut_20_read_reg_2740,
        gelu_lut_21_load => gelu_lut_21_read_reg_2745,
        gelu_lut_22_load => gelu_lut_22_read_reg_2750,
        gelu_lut_23_load => gelu_lut_23_read_reg_2755,
        gelu_lut_24_load => gelu_lut_24_read_reg_2760,
        gelu_lut_25_load => gelu_lut_25_read_reg_2765,
        gelu_lut_26_load => gelu_lut_26_read_reg_2770,
        gelu_lut_27_load => gelu_lut_27_read_reg_2775,
        gelu_lut_28_load => gelu_lut_28_read_reg_2780,
        gelu_lut_29_load => gelu_lut_29_read_reg_2785,
        gelu_lut_30_load => gelu_lut_30_read_reg_2790,
        gelu_lut_31_load => gelu_lut_31_read_reg_2795,
        gelu_lut_32_load => gelu_lut_32_read_reg_2800,
        gelu_lut_33_load => gelu_lut_33_read_reg_2805,
        gelu_lut_34_load => gelu_lut_34_read_reg_2810,
        gelu_lut_35_load => gelu_lut_35_read_reg_2815,
        gelu_lut_36_load => gelu_lut_36_read_reg_2820,
        gelu_lut_37_load => gelu_lut_37_read_reg_2825,
        gelu_lut_38_load => gelu_lut_38_read_reg_2830,
        gelu_lut_39_load => gelu_lut_39_read_reg_2835,
        gelu_lut_40_load => gelu_lut_40_read_reg_2840,
        gelu_lut_41_load => gelu_lut_41_read_reg_2845,
        gelu_lut_42_load => gelu_lut_42_read_reg_2850,
        gelu_lut_43_load => gelu_lut_43_read_reg_2855,
        gelu_lut_44_load => gelu_lut_44_read_reg_2860,
        gelu_lut_45_load => gelu_lut_45_read_reg_2865,
        gelu_lut_46_load => gelu_lut_46_read_reg_2870,
        gelu_lut_47_load => gelu_lut_47_read_reg_2875,
        gelu_lut_48_load => gelu_lut_48_read_reg_2880,
        gelu_lut_49_load => gelu_lut_49_read_reg_2885,
        gelu_lut_50_load => gelu_lut_50_read_reg_2890,
        gelu_lut_51_load => gelu_lut_51_read_reg_2895,
        gelu_lut_52_load => gelu_lut_52_read_reg_2900,
        gelu_lut_53_load => gelu_lut_53_read_reg_2905,
        gelu_lut_54_load => gelu_lut_54_read_reg_2910,
        gelu_lut_55_load => gelu_lut_55_read_reg_2915,
        gelu_lut_56_load => gelu_lut_56_read_reg_2920,
        gelu_lut_57_load => gelu_lut_57_read_reg_2925,
        gelu_lut_58_load => gelu_lut_58_read_reg_2930,
        gelu_lut_59_load => gelu_lut_59_read_reg_2935,
        gelu_lut_60_load => gelu_lut_60_read_reg_2940,
        gelu_lut_61_load => gelu_lut_61_read_reg_2945,
        gelu_lut_62_load => gelu_lut_62_read_reg_2950,
        gelu_lut_63_load => gelu_lut_63_read_reg_2955,
        gelu_lut_64_load => gelu_lut_64_read_reg_2960,
        gelu_lut_65_load => gelu_lut_65_read_reg_2965,
        gelu_lut_66_load => gelu_lut_66_read_reg_2970,
        gelu_lut_67_load => gelu_lut_67_read_reg_2975,
        gelu_lut_68_load => gelu_lut_68_read_reg_2980,
        gelu_lut_69_load => gelu_lut_69_read_reg_2985,
        gelu_lut_70_load => gelu_lut_70_read_reg_2990,
        gelu_lut_71_load => gelu_lut_71_read_reg_2995,
        gelu_lut_72_load => gelu_lut_72_read_reg_3000,
        gelu_lut_73_load => gelu_lut_73_read_reg_3005,
        gelu_lut_74_load => gelu_lut_74_read_reg_3010,
        gelu_lut_75_load => gelu_lut_75_read_reg_3015,
        gelu_lut_76_load => gelu_lut_76_read_reg_3020,
        gelu_lut_77_load => gelu_lut_77_read_reg_3025,
        gelu_lut_78_load => gelu_lut_78_read_reg_3030,
        gelu_lut_79_load => gelu_lut_79_read_reg_3035,
        gelu_lut_80_load => gelu_lut_80_read_reg_3040,
        gelu_lut_81_load => gelu_lut_81_read_reg_3045,
        gelu_lut_82_load => gelu_lut_82_read_reg_3050,
        gelu_lut_83_load => gelu_lut_83_read_reg_3055,
        gelu_lut_84_load => gelu_lut_84_read_reg_3060,
        gelu_lut_85_load => gelu_lut_85_read_reg_3065,
        gelu_lut_86_load => gelu_lut_86_read_reg_3070,
        gelu_lut_87_load => gelu_lut_87_read_reg_3075,
        gelu_lut_88_load => gelu_lut_88_read_reg_3080,
        gelu_lut_89_load => gelu_lut_89_read_reg_3085,
        gelu_lut_90_load => gelu_lut_90_read_reg_3090,
        gelu_lut_91_load => gelu_lut_91_read_reg_3095,
        gelu_lut_92_load => gelu_lut_92_read_reg_3100,
        gelu_lut_93_load => gelu_lut_93_read_reg_3105,
        gelu_lut_94_load => gelu_lut_94_read_reg_3110,
        gelu_lut_95_load => gelu_lut_95_read_reg_3115,
        gelu_lut_96_load => gelu_lut_96_read_reg_3120,
        gelu_lut_97_load => gelu_lut_97_read_reg_3125,
        gelu_lut_98_load => gelu_lut_98_read_reg_3130,
        gelu_lut_99_load => gelu_lut_99_read_reg_3135,
        gelu_lut_100_load => gelu_lut_100_read_reg_3140,
        gelu_lut_101_load => gelu_lut_101_read_reg_3145,
        gelu_lut_102_load => gelu_lut_102_read_reg_3150,
        gelu_lut_103_load => gelu_lut_103_read_reg_3155,
        gelu_lut_104_load => gelu_lut_104_read_reg_3160,
        gelu_lut_105_load => gelu_lut_105_read_reg_3165,
        gelu_lut_106_load => gelu_lut_106_read_reg_3170,
        gelu_lut_107_load => gelu_lut_107_read_reg_3175,
        gelu_lut_108_load => gelu_lut_108_read_reg_3180,
        gelu_lut_109_load => gelu_lut_109_read_reg_3185,
        gelu_lut_110_load => gelu_lut_110_read_reg_3190,
        gelu_lut_111_load => gelu_lut_111_read_reg_3195,
        gelu_lut_112_load => gelu_lut_112_read_reg_3200,
        gelu_lut_113_load => gelu_lut_113_read_reg_3205,
        gelu_lut_114_load => gelu_lut_114_read_reg_3210,
        gelu_lut_115_load => gelu_lut_115_read_reg_3215,
        gelu_lut_116_load => gelu_lut_116_read_reg_3220,
        gelu_lut_117_load => gelu_lut_117_read_reg_3225,
        gelu_lut_118_load => gelu_lut_118_read_reg_3230,
        gelu_lut_119_load => gelu_lut_119_read_reg_3235,
        gelu_lut_120_load => gelu_lut_120_read_reg_3240,
        gelu_lut_121_load => gelu_lut_121_read_reg_3245,
        gelu_lut_122_load => gelu_lut_122_read_reg_3250,
        gelu_lut_123_load => gelu_lut_123_read_reg_3255,
        gelu_lut_124_load => gelu_lut_124_read_reg_3260,
        gelu_lut_125_load => gelu_lut_125_read_reg_3265,
        gelu_lut_126_load => gelu_lut_126_read_reg_3270,
        gelu_lut_127_load => gelu_lut_127_read_reg_3275,
        gelu_lut_128_load => gelu_lut_128_read_reg_3280,
        gelu_lut_129_load => gelu_lut_129_read_reg_3285,
        gelu_lut_130_load => gelu_lut_130_read_reg_3290,
        gelu_lut_131_load => gelu_lut_131_read_reg_3295,
        gelu_lut_132_load => gelu_lut_132_read_reg_3300,
        gelu_lut_133_load => gelu_lut_133_read_reg_3305,
        gelu_lut_134_load => gelu_lut_134_read_reg_3310,
        gelu_lut_135_load => gelu_lut_135_read_reg_3315,
        gelu_lut_136_load => gelu_lut_136_read_reg_3320,
        gelu_lut_137_load => gelu_lut_137_read_reg_3325,
        gelu_lut_138_load => gelu_lut_138_read_reg_3330,
        gelu_lut_139_load => gelu_lut_139_read_reg_3335,
        gelu_lut_140_load => gelu_lut_140_read_reg_3340,
        gelu_lut_141_load => gelu_lut_141_read_reg_3345,
        gelu_lut_142_load => gelu_lut_142_read_reg_3350,
        gelu_lut_143_load => gelu_lut_143_read_reg_3355,
        gelu_lut_144_load => gelu_lut_144_read_reg_3360,
        gelu_lut_145_load => gelu_lut_145_read_reg_3365,
        gelu_lut_146_load => gelu_lut_146_read_reg_3370,
        gelu_lut_147_load => gelu_lut_147_read_reg_3375,
        gelu_lut_148_load => gelu_lut_148_read_reg_3380,
        gelu_lut_149_load => gelu_lut_149_read_reg_3385,
        gelu_lut_150_load => gelu_lut_150_read_reg_3390,
        gelu_lut_151_load => gelu_lut_151_read_reg_3395,
        gelu_lut_152_load => gelu_lut_152_read_reg_3400,
        gelu_lut_153_load => gelu_lut_153_read_reg_3405,
        gelu_lut_154_load => gelu_lut_154_read_reg_3410,
        gelu_lut_155_load => gelu_lut_155_read_reg_3415,
        gelu_lut_156_load => gelu_lut_156_read_reg_3420,
        gelu_lut_157_load => gelu_lut_157_read_reg_3425,
        gelu_lut_158_load => gelu_lut_158_read_reg_3430,
        gelu_lut_159_load => gelu_lut_159_read_reg_3435,
        gelu_lut_160_load => gelu_lut_160_read_reg_3440,
        gelu_lut_161_load => gelu_lut_161_read_reg_3445,
        gelu_lut_162_load => gelu_lut_162_read_reg_3450,
        gelu_lut_163_load => gelu_lut_163_read_reg_3455,
        gelu_lut_164_load => gelu_lut_164_read_reg_3460,
        gelu_lut_165_load => gelu_lut_165_read_reg_3465,
        gelu_lut_166_load => gelu_lut_166_read_reg_3470,
        gelu_lut_167_load => gelu_lut_167_read_reg_3475,
        gelu_lut_168_load => gelu_lut_168_read_reg_3480,
        gelu_lut_169_load => gelu_lut_169_read_reg_3485,
        gelu_lut_170_load => gelu_lut_170_read_reg_3490,
        gelu_lut_171_load => gelu_lut_171_read_reg_3495,
        gelu_lut_172_load => gelu_lut_172_read_reg_3500,
        gelu_lut_173_load => gelu_lut_173_read_reg_3505,
        gelu_lut_174_load => gelu_lut_174_read_reg_3510,
        gelu_lut_175_load => gelu_lut_175_read_reg_3515,
        gelu_lut_176_load => gelu_lut_176_read_reg_3520,
        gelu_lut_177_load => gelu_lut_177_read_reg_3525,
        gelu_lut_178_load => gelu_lut_178_read_reg_3530,
        gelu_lut_179_load => gelu_lut_179_read_reg_3535,
        gelu_lut_180_load => gelu_lut_180_read_reg_3540,
        gelu_lut_181_load => gelu_lut_181_read_reg_3545,
        gelu_lut_182_load => gelu_lut_182_read_reg_3550,
        gelu_lut_183_load => gelu_lut_183_read_reg_3555,
        gelu_lut_184_load => gelu_lut_184_read_reg_3560,
        gelu_lut_185_load => gelu_lut_185_read_reg_3565,
        gelu_lut_186_load => gelu_lut_186_read_reg_3570,
        gelu_lut_187_load => gelu_lut_187_read_reg_3575,
        gelu_lut_188_load => gelu_lut_188_read_reg_3580,
        gelu_lut_189_load => gelu_lut_189_read_reg_3585,
        gelu_lut_190_load => gelu_lut_190_read_reg_3590,
        gelu_lut_191_load => gelu_lut_191_read_reg_3595,
        gelu_lut_192_load => gelu_lut_192_read_reg_3600,
        gelu_lut_193_load => gelu_lut_193_read_reg_3605,
        gelu_lut_194_load => gelu_lut_194_read_reg_3610,
        gelu_lut_195_load => gelu_lut_195_read_reg_3615,
        gelu_lut_196_load => gelu_lut_196_read_reg_3620,
        gelu_lut_197_load => gelu_lut_197_read_reg_3625,
        gelu_lut_198_load => gelu_lut_198_read_reg_3630,
        gelu_lut_199_load => gelu_lut_199_read_reg_3635,
        gelu_lut_200_load => gelu_lut_200_read_reg_3640,
        gelu_lut_201_load => gelu_lut_201_read_reg_3645,
        gelu_lut_202_load => gelu_lut_202_read_reg_3650,
        gelu_lut_203_load => gelu_lut_203_read_reg_3655,
        gelu_lut_204_load => gelu_lut_204_read_reg_3660,
        gelu_lut_205_load => gelu_lut_205_read_reg_3665,
        gelu_lut_206_load => gelu_lut_206_read_reg_3670,
        gelu_lut_207_load => gelu_lut_207_read_reg_3675,
        gelu_lut_208_load => gelu_lut_208_read_reg_3680,
        gelu_lut_209_load => gelu_lut_209_read_reg_3685,
        gelu_lut_210_load => gelu_lut_210_read_reg_3690,
        gelu_lut_211_load => gelu_lut_211_read_reg_3695,
        gelu_lut_212_load => gelu_lut_212_read_reg_3700,
        gelu_lut_213_load => gelu_lut_213_read_reg_3705,
        gelu_lut_214_load => gelu_lut_214_read_reg_3710,
        gelu_lut_215_load => gelu_lut_215_read_reg_3715,
        gelu_lut_216_load => gelu_lut_216_read_reg_3720,
        gelu_lut_217_load => gelu_lut_217_read_reg_3725,
        gelu_lut_218_load => gelu_lut_218_read_reg_3730,
        gelu_lut_219_load => gelu_lut_219_read_reg_3735,
        gelu_lut_220_load => gelu_lut_220_read_reg_3740,
        gelu_lut_221_load => gelu_lut_221_read_reg_3745,
        gelu_lut_222_load => gelu_lut_222_read_reg_3750,
        gelu_lut_223_load => gelu_lut_223_read_reg_3755,
        gelu_lut_224_load => gelu_lut_224_read_reg_3760,
        gelu_lut_225_load => gelu_lut_225_read_reg_3765,
        gelu_lut_226_load => gelu_lut_226_read_reg_3770,
        gelu_lut_227_load => gelu_lut_227_read_reg_3775,
        gelu_lut_228_load => gelu_lut_228_read_reg_3780,
        gelu_lut_229_load => gelu_lut_229_read_reg_3785,
        gelu_lut_230_load => gelu_lut_230_read_reg_3790,
        gelu_lut_231_load => gelu_lut_231_read_reg_3795,
        gelu_lut_232_load => gelu_lut_232_read_reg_3800,
        gelu_lut_233_load => gelu_lut_233_read_reg_3805,
        gelu_lut_234_load => gelu_lut_234_read_reg_3810,
        gelu_lut_235_load => gelu_lut_235_read_reg_3815,
        gelu_lut_236_load => gelu_lut_236_read_reg_3820,
        gelu_lut_237_load => gelu_lut_237_read_reg_3825,
        gelu_lut_238_load => gelu_lut_238_read_reg_3830,
        gelu_lut_239_load => gelu_lut_239_read_reg_3835,
        gelu_lut_240_load => gelu_lut_240_read_reg_3840,
        gelu_lut_241_load => gelu_lut_241_read_reg_3845,
        gelu_lut_242_load => gelu_lut_242_read_reg_3850,
        gelu_lut_243_load => gelu_lut_243_read_reg_3855,
        gelu_lut_244_load => gelu_lut_244_read_reg_3860,
        gelu_lut_245_load => gelu_lut_245_read_reg_3865,
        gelu_lut_246_load => gelu_lut_246_read_reg_3870,
        gelu_lut_247_load => gelu_lut_247_read_reg_3875,
        gelu_lut_248_load => gelu_lut_248_read_reg_3880,
        gelu_lut_249_load => gelu_lut_249_read_reg_3885,
        gelu_lut_250_load => gelu_lut_250_read_reg_3890,
        gelu_lut_251_load => gelu_lut_251_read_reg_3895,
        gelu_lut_252_load => gelu_lut_252_read_reg_3900,
        gelu_lut_253_load => gelu_lut_253_read_reg_3905,
        gelu_lut_254_load => gelu_lut_254_read_reg_3910,
        gelu_lut_255_load => gelu_lut_255_read_reg_3915,
        gelu_out_address0 => grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_gelu_out_address0,
        gelu_out_ce0 => grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_gelu_out_ce0,
        gelu_out_we0 => grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_gelu_out_we0,
        gelu_out_d0 => grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_gelu_out_d0);

    grp_gelu_embed_kernel_Pipeline_embed_fu_2616 : component gelu_embed_kernel_gelu_embed_kernel_Pipeline_embed
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_gelu_embed_kernel_Pipeline_embed_fu_2616_ap_start,
        ap_done => grp_gelu_embed_kernel_Pipeline_embed_fu_2616_ap_done,
        ap_idle => grp_gelu_embed_kernel_Pipeline_embed_fu_2616_ap_idle,
        ap_ready => grp_gelu_embed_kernel_Pipeline_embed_fu_2616_ap_ready,
        token_ids_address0 => grp_gelu_embed_kernel_Pipeline_embed_fu_2616_token_ids_address0,
        token_ids_ce0 => grp_gelu_embed_kernel_Pipeline_embed_fu_2616_token_ids_ce0,
        token_ids_q0 => token_ids_q0,
        embed_lut_0_address0 => grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_0_address0,
        embed_lut_0_ce0 => grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_0_ce0,
        embed_lut_0_q0 => embed_lut_0_q0,
        embed_lut_1_address0 => grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_1_address0,
        embed_lut_1_ce0 => grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_1_ce0,
        embed_lut_1_q0 => embed_lut_1_q0,
        embed_lut_2_address0 => grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_2_address0,
        embed_lut_2_ce0 => grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_2_ce0,
        embed_lut_2_q0 => embed_lut_2_q0,
        embed_lut_3_address0 => grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_3_address0,
        embed_lut_3_ce0 => grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_3_ce0,
        embed_lut_3_q0 => embed_lut_3_q0,
        embed_lut_4_address0 => grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_4_address0,
        embed_lut_4_ce0 => grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_4_ce0,
        embed_lut_4_q0 => embed_lut_4_q0,
        embed_lut_5_address0 => grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_5_address0,
        embed_lut_5_ce0 => grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_5_ce0,
        embed_lut_5_q0 => embed_lut_5_q0,
        embed_lut_6_address0 => grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_6_address0,
        embed_lut_6_ce0 => grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_6_ce0,
        embed_lut_6_q0 => embed_lut_6_q0,
        embed_lut_7_address0 => grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_7_address0,
        embed_lut_7_ce0 => grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_7_ce0,
        embed_lut_7_q0 => embed_lut_7_q0,
        embed_out_address0 => grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_out_address0,
        embed_out_ce0 => grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_out_ce0,
        embed_out_we0 => grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_out_we0,
        embed_out_d0 => grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_out_d0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_gelu_embed_kernel_Pipeline_embed_fu_2616_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_gelu_embed_kernel_Pipeline_embed_fu_2616_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_gelu_embed_kernel_Pipeline_embed_fu_2616_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_gelu_embed_kernel_Pipeline_embed_fu_2616_ap_ready = ap_const_logic_1)) then 
                    grp_gelu_embed_kernel_Pipeline_embed_fu_2616_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_ap_ready = ap_const_logic_1)) then 
                    grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                gelu_lut_0_read_reg_2640 <= gelu_lut_0;
                gelu_lut_100_read_reg_3140 <= gelu_lut_100;
                gelu_lut_101_read_reg_3145 <= gelu_lut_101;
                gelu_lut_102_read_reg_3150 <= gelu_lut_102;
                gelu_lut_103_read_reg_3155 <= gelu_lut_103;
                gelu_lut_104_read_reg_3160 <= gelu_lut_104;
                gelu_lut_105_read_reg_3165 <= gelu_lut_105;
                gelu_lut_106_read_reg_3170 <= gelu_lut_106;
                gelu_lut_107_read_reg_3175 <= gelu_lut_107;
                gelu_lut_108_read_reg_3180 <= gelu_lut_108;
                gelu_lut_109_read_reg_3185 <= gelu_lut_109;
                gelu_lut_10_read_reg_2690 <= gelu_lut_10;
                gelu_lut_110_read_reg_3190 <= gelu_lut_110;
                gelu_lut_111_read_reg_3195 <= gelu_lut_111;
                gelu_lut_112_read_reg_3200 <= gelu_lut_112;
                gelu_lut_113_read_reg_3205 <= gelu_lut_113;
                gelu_lut_114_read_reg_3210 <= gelu_lut_114;
                gelu_lut_115_read_reg_3215 <= gelu_lut_115;
                gelu_lut_116_read_reg_3220 <= gelu_lut_116;
                gelu_lut_117_read_reg_3225 <= gelu_lut_117;
                gelu_lut_118_read_reg_3230 <= gelu_lut_118;
                gelu_lut_119_read_reg_3235 <= gelu_lut_119;
                gelu_lut_11_read_reg_2695 <= gelu_lut_11;
                gelu_lut_120_read_reg_3240 <= gelu_lut_120;
                gelu_lut_121_read_reg_3245 <= gelu_lut_121;
                gelu_lut_122_read_reg_3250 <= gelu_lut_122;
                gelu_lut_123_read_reg_3255 <= gelu_lut_123;
                gelu_lut_124_read_reg_3260 <= gelu_lut_124;
                gelu_lut_125_read_reg_3265 <= gelu_lut_125;
                gelu_lut_126_read_reg_3270 <= gelu_lut_126;
                gelu_lut_127_read_reg_3275 <= gelu_lut_127;
                gelu_lut_128_read_reg_3280 <= gelu_lut_128;
                gelu_lut_129_read_reg_3285 <= gelu_lut_129;
                gelu_lut_12_read_reg_2700 <= gelu_lut_12;
                gelu_lut_130_read_reg_3290 <= gelu_lut_130;
                gelu_lut_131_read_reg_3295 <= gelu_lut_131;
                gelu_lut_132_read_reg_3300 <= gelu_lut_132;
                gelu_lut_133_read_reg_3305 <= gelu_lut_133;
                gelu_lut_134_read_reg_3310 <= gelu_lut_134;
                gelu_lut_135_read_reg_3315 <= gelu_lut_135;
                gelu_lut_136_read_reg_3320 <= gelu_lut_136;
                gelu_lut_137_read_reg_3325 <= gelu_lut_137;
                gelu_lut_138_read_reg_3330 <= gelu_lut_138;
                gelu_lut_139_read_reg_3335 <= gelu_lut_139;
                gelu_lut_13_read_reg_2705 <= gelu_lut_13;
                gelu_lut_140_read_reg_3340 <= gelu_lut_140;
                gelu_lut_141_read_reg_3345 <= gelu_lut_141;
                gelu_lut_142_read_reg_3350 <= gelu_lut_142;
                gelu_lut_143_read_reg_3355 <= gelu_lut_143;
                gelu_lut_144_read_reg_3360 <= gelu_lut_144;
                gelu_lut_145_read_reg_3365 <= gelu_lut_145;
                gelu_lut_146_read_reg_3370 <= gelu_lut_146;
                gelu_lut_147_read_reg_3375 <= gelu_lut_147;
                gelu_lut_148_read_reg_3380 <= gelu_lut_148;
                gelu_lut_149_read_reg_3385 <= gelu_lut_149;
                gelu_lut_14_read_reg_2710 <= gelu_lut_14;
                gelu_lut_150_read_reg_3390 <= gelu_lut_150;
                gelu_lut_151_read_reg_3395 <= gelu_lut_151;
                gelu_lut_152_read_reg_3400 <= gelu_lut_152;
                gelu_lut_153_read_reg_3405 <= gelu_lut_153;
                gelu_lut_154_read_reg_3410 <= gelu_lut_154;
                gelu_lut_155_read_reg_3415 <= gelu_lut_155;
                gelu_lut_156_read_reg_3420 <= gelu_lut_156;
                gelu_lut_157_read_reg_3425 <= gelu_lut_157;
                gelu_lut_158_read_reg_3430 <= gelu_lut_158;
                gelu_lut_159_read_reg_3435 <= gelu_lut_159;
                gelu_lut_15_read_reg_2715 <= gelu_lut_15;
                gelu_lut_160_read_reg_3440 <= gelu_lut_160;
                gelu_lut_161_read_reg_3445 <= gelu_lut_161;
                gelu_lut_162_read_reg_3450 <= gelu_lut_162;
                gelu_lut_163_read_reg_3455 <= gelu_lut_163;
                gelu_lut_164_read_reg_3460 <= gelu_lut_164;
                gelu_lut_165_read_reg_3465 <= gelu_lut_165;
                gelu_lut_166_read_reg_3470 <= gelu_lut_166;
                gelu_lut_167_read_reg_3475 <= gelu_lut_167;
                gelu_lut_168_read_reg_3480 <= gelu_lut_168;
                gelu_lut_169_read_reg_3485 <= gelu_lut_169;
                gelu_lut_16_read_reg_2720 <= gelu_lut_16;
                gelu_lut_170_read_reg_3490 <= gelu_lut_170;
                gelu_lut_171_read_reg_3495 <= gelu_lut_171;
                gelu_lut_172_read_reg_3500 <= gelu_lut_172;
                gelu_lut_173_read_reg_3505 <= gelu_lut_173;
                gelu_lut_174_read_reg_3510 <= gelu_lut_174;
                gelu_lut_175_read_reg_3515 <= gelu_lut_175;
                gelu_lut_176_read_reg_3520 <= gelu_lut_176;
                gelu_lut_177_read_reg_3525 <= gelu_lut_177;
                gelu_lut_178_read_reg_3530 <= gelu_lut_178;
                gelu_lut_179_read_reg_3535 <= gelu_lut_179;
                gelu_lut_17_read_reg_2725 <= gelu_lut_17;
                gelu_lut_180_read_reg_3540 <= gelu_lut_180;
                gelu_lut_181_read_reg_3545 <= gelu_lut_181;
                gelu_lut_182_read_reg_3550 <= gelu_lut_182;
                gelu_lut_183_read_reg_3555 <= gelu_lut_183;
                gelu_lut_184_read_reg_3560 <= gelu_lut_184;
                gelu_lut_185_read_reg_3565 <= gelu_lut_185;
                gelu_lut_186_read_reg_3570 <= gelu_lut_186;
                gelu_lut_187_read_reg_3575 <= gelu_lut_187;
                gelu_lut_188_read_reg_3580 <= gelu_lut_188;
                gelu_lut_189_read_reg_3585 <= gelu_lut_189;
                gelu_lut_18_read_reg_2730 <= gelu_lut_18;
                gelu_lut_190_read_reg_3590 <= gelu_lut_190;
                gelu_lut_191_read_reg_3595 <= gelu_lut_191;
                gelu_lut_192_read_reg_3600 <= gelu_lut_192;
                gelu_lut_193_read_reg_3605 <= gelu_lut_193;
                gelu_lut_194_read_reg_3610 <= gelu_lut_194;
                gelu_lut_195_read_reg_3615 <= gelu_lut_195;
                gelu_lut_196_read_reg_3620 <= gelu_lut_196;
                gelu_lut_197_read_reg_3625 <= gelu_lut_197;
                gelu_lut_198_read_reg_3630 <= gelu_lut_198;
                gelu_lut_199_read_reg_3635 <= gelu_lut_199;
                gelu_lut_19_read_reg_2735 <= gelu_lut_19;
                gelu_lut_1_read_reg_2645 <= gelu_lut_1;
                gelu_lut_200_read_reg_3640 <= gelu_lut_200;
                gelu_lut_201_read_reg_3645 <= gelu_lut_201;
                gelu_lut_202_read_reg_3650 <= gelu_lut_202;
                gelu_lut_203_read_reg_3655 <= gelu_lut_203;
                gelu_lut_204_read_reg_3660 <= gelu_lut_204;
                gelu_lut_205_read_reg_3665 <= gelu_lut_205;
                gelu_lut_206_read_reg_3670 <= gelu_lut_206;
                gelu_lut_207_read_reg_3675 <= gelu_lut_207;
                gelu_lut_208_read_reg_3680 <= gelu_lut_208;
                gelu_lut_209_read_reg_3685 <= gelu_lut_209;
                gelu_lut_20_read_reg_2740 <= gelu_lut_20;
                gelu_lut_210_read_reg_3690 <= gelu_lut_210;
                gelu_lut_211_read_reg_3695 <= gelu_lut_211;
                gelu_lut_212_read_reg_3700 <= gelu_lut_212;
                gelu_lut_213_read_reg_3705 <= gelu_lut_213;
                gelu_lut_214_read_reg_3710 <= gelu_lut_214;
                gelu_lut_215_read_reg_3715 <= gelu_lut_215;
                gelu_lut_216_read_reg_3720 <= gelu_lut_216;
                gelu_lut_217_read_reg_3725 <= gelu_lut_217;
                gelu_lut_218_read_reg_3730 <= gelu_lut_218;
                gelu_lut_219_read_reg_3735 <= gelu_lut_219;
                gelu_lut_21_read_reg_2745 <= gelu_lut_21;
                gelu_lut_220_read_reg_3740 <= gelu_lut_220;
                gelu_lut_221_read_reg_3745 <= gelu_lut_221;
                gelu_lut_222_read_reg_3750 <= gelu_lut_222;
                gelu_lut_223_read_reg_3755 <= gelu_lut_223;
                gelu_lut_224_read_reg_3760 <= gelu_lut_224;
                gelu_lut_225_read_reg_3765 <= gelu_lut_225;
                gelu_lut_226_read_reg_3770 <= gelu_lut_226;
                gelu_lut_227_read_reg_3775 <= gelu_lut_227;
                gelu_lut_228_read_reg_3780 <= gelu_lut_228;
                gelu_lut_229_read_reg_3785 <= gelu_lut_229;
                gelu_lut_22_read_reg_2750 <= gelu_lut_22;
                gelu_lut_230_read_reg_3790 <= gelu_lut_230;
                gelu_lut_231_read_reg_3795 <= gelu_lut_231;
                gelu_lut_232_read_reg_3800 <= gelu_lut_232;
                gelu_lut_233_read_reg_3805 <= gelu_lut_233;
                gelu_lut_234_read_reg_3810 <= gelu_lut_234;
                gelu_lut_235_read_reg_3815 <= gelu_lut_235;
                gelu_lut_236_read_reg_3820 <= gelu_lut_236;
                gelu_lut_237_read_reg_3825 <= gelu_lut_237;
                gelu_lut_238_read_reg_3830 <= gelu_lut_238;
                gelu_lut_239_read_reg_3835 <= gelu_lut_239;
                gelu_lut_23_read_reg_2755 <= gelu_lut_23;
                gelu_lut_240_read_reg_3840 <= gelu_lut_240;
                gelu_lut_241_read_reg_3845 <= gelu_lut_241;
                gelu_lut_242_read_reg_3850 <= gelu_lut_242;
                gelu_lut_243_read_reg_3855 <= gelu_lut_243;
                gelu_lut_244_read_reg_3860 <= gelu_lut_244;
                gelu_lut_245_read_reg_3865 <= gelu_lut_245;
                gelu_lut_246_read_reg_3870 <= gelu_lut_246;
                gelu_lut_247_read_reg_3875 <= gelu_lut_247;
                gelu_lut_248_read_reg_3880 <= gelu_lut_248;
                gelu_lut_249_read_reg_3885 <= gelu_lut_249;
                gelu_lut_24_read_reg_2760 <= gelu_lut_24;
                gelu_lut_250_read_reg_3890 <= gelu_lut_250;
                gelu_lut_251_read_reg_3895 <= gelu_lut_251;
                gelu_lut_252_read_reg_3900 <= gelu_lut_252;
                gelu_lut_253_read_reg_3905 <= gelu_lut_253;
                gelu_lut_254_read_reg_3910 <= gelu_lut_254;
                gelu_lut_255_read_reg_3915 <= gelu_lut_255;
                gelu_lut_25_read_reg_2765 <= gelu_lut_25;
                gelu_lut_26_read_reg_2770 <= gelu_lut_26;
                gelu_lut_27_read_reg_2775 <= gelu_lut_27;
                gelu_lut_28_read_reg_2780 <= gelu_lut_28;
                gelu_lut_29_read_reg_2785 <= gelu_lut_29;
                gelu_lut_2_read_reg_2650 <= gelu_lut_2;
                gelu_lut_30_read_reg_2790 <= gelu_lut_30;
                gelu_lut_31_read_reg_2795 <= gelu_lut_31;
                gelu_lut_32_read_reg_2800 <= gelu_lut_32;
                gelu_lut_33_read_reg_2805 <= gelu_lut_33;
                gelu_lut_34_read_reg_2810 <= gelu_lut_34;
                gelu_lut_35_read_reg_2815 <= gelu_lut_35;
                gelu_lut_36_read_reg_2820 <= gelu_lut_36;
                gelu_lut_37_read_reg_2825 <= gelu_lut_37;
                gelu_lut_38_read_reg_2830 <= gelu_lut_38;
                gelu_lut_39_read_reg_2835 <= gelu_lut_39;
                gelu_lut_3_read_reg_2655 <= gelu_lut_3;
                gelu_lut_40_read_reg_2840 <= gelu_lut_40;
                gelu_lut_41_read_reg_2845 <= gelu_lut_41;
                gelu_lut_42_read_reg_2850 <= gelu_lut_42;
                gelu_lut_43_read_reg_2855 <= gelu_lut_43;
                gelu_lut_44_read_reg_2860 <= gelu_lut_44;
                gelu_lut_45_read_reg_2865 <= gelu_lut_45;
                gelu_lut_46_read_reg_2870 <= gelu_lut_46;
                gelu_lut_47_read_reg_2875 <= gelu_lut_47;
                gelu_lut_48_read_reg_2880 <= gelu_lut_48;
                gelu_lut_49_read_reg_2885 <= gelu_lut_49;
                gelu_lut_4_read_reg_2660 <= gelu_lut_4;
                gelu_lut_50_read_reg_2890 <= gelu_lut_50;
                gelu_lut_51_read_reg_2895 <= gelu_lut_51;
                gelu_lut_52_read_reg_2900 <= gelu_lut_52;
                gelu_lut_53_read_reg_2905 <= gelu_lut_53;
                gelu_lut_54_read_reg_2910 <= gelu_lut_54;
                gelu_lut_55_read_reg_2915 <= gelu_lut_55;
                gelu_lut_56_read_reg_2920 <= gelu_lut_56;
                gelu_lut_57_read_reg_2925 <= gelu_lut_57;
                gelu_lut_58_read_reg_2930 <= gelu_lut_58;
                gelu_lut_59_read_reg_2935 <= gelu_lut_59;
                gelu_lut_5_read_reg_2665 <= gelu_lut_5;
                gelu_lut_60_read_reg_2940 <= gelu_lut_60;
                gelu_lut_61_read_reg_2945 <= gelu_lut_61;
                gelu_lut_62_read_reg_2950 <= gelu_lut_62;
                gelu_lut_63_read_reg_2955 <= gelu_lut_63;
                gelu_lut_64_read_reg_2960 <= gelu_lut_64;
                gelu_lut_65_read_reg_2965 <= gelu_lut_65;
                gelu_lut_66_read_reg_2970 <= gelu_lut_66;
                gelu_lut_67_read_reg_2975 <= gelu_lut_67;
                gelu_lut_68_read_reg_2980 <= gelu_lut_68;
                gelu_lut_69_read_reg_2985 <= gelu_lut_69;
                gelu_lut_6_read_reg_2670 <= gelu_lut_6;
                gelu_lut_70_read_reg_2990 <= gelu_lut_70;
                gelu_lut_71_read_reg_2995 <= gelu_lut_71;
                gelu_lut_72_read_reg_3000 <= gelu_lut_72;
                gelu_lut_73_read_reg_3005 <= gelu_lut_73;
                gelu_lut_74_read_reg_3010 <= gelu_lut_74;
                gelu_lut_75_read_reg_3015 <= gelu_lut_75;
                gelu_lut_76_read_reg_3020 <= gelu_lut_76;
                gelu_lut_77_read_reg_3025 <= gelu_lut_77;
                gelu_lut_78_read_reg_3030 <= gelu_lut_78;
                gelu_lut_79_read_reg_3035 <= gelu_lut_79;
                gelu_lut_7_read_reg_2675 <= gelu_lut_7;
                gelu_lut_80_read_reg_3040 <= gelu_lut_80;
                gelu_lut_81_read_reg_3045 <= gelu_lut_81;
                gelu_lut_82_read_reg_3050 <= gelu_lut_82;
                gelu_lut_83_read_reg_3055 <= gelu_lut_83;
                gelu_lut_84_read_reg_3060 <= gelu_lut_84;
                gelu_lut_85_read_reg_3065 <= gelu_lut_85;
                gelu_lut_86_read_reg_3070 <= gelu_lut_86;
                gelu_lut_87_read_reg_3075 <= gelu_lut_87;
                gelu_lut_88_read_reg_3080 <= gelu_lut_88;
                gelu_lut_89_read_reg_3085 <= gelu_lut_89;
                gelu_lut_8_read_reg_2680 <= gelu_lut_8;
                gelu_lut_90_read_reg_3090 <= gelu_lut_90;
                gelu_lut_91_read_reg_3095 <= gelu_lut_91;
                gelu_lut_92_read_reg_3100 <= gelu_lut_92;
                gelu_lut_93_read_reg_3105 <= gelu_lut_93;
                gelu_lut_94_read_reg_3110 <= gelu_lut_94;
                gelu_lut_95_read_reg_3115 <= gelu_lut_95;
                gelu_lut_96_read_reg_3120 <= gelu_lut_96;
                gelu_lut_97_read_reg_3125 <= gelu_lut_97;
                gelu_lut_98_read_reg_3130 <= gelu_lut_98;
                gelu_lut_99_read_reg_3135 <= gelu_lut_99;
                gelu_lut_9_read_reg_2685 <= gelu_lut_9;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2_on_subcall_done))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    X_address0 <= grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_X_address0;
    X_ce0 <= grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_X_ce0;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state2_on_subcall_done)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state2_on_subcall_done_assign_proc : process(grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_ap_done, grp_gelu_embed_kernel_Pipeline_embed_fu_2616_ap_done)
    begin
                ap_block_state2_on_subcall_done <= ((grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_ap_done = ap_const_logic_0) or (grp_gelu_embed_kernel_Pipeline_embed_fu_2616_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2_on_subcall_done))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2_on_subcall_done))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    embed_lut_0_address0 <= grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_0_address0;
    embed_lut_0_ce0 <= grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_0_ce0;
    embed_lut_1_address0 <= grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_1_address0;
    embed_lut_1_ce0 <= grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_1_ce0;
    embed_lut_2_address0 <= grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_2_address0;
    embed_lut_2_ce0 <= grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_2_ce0;
    embed_lut_3_address0 <= grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_3_address0;
    embed_lut_3_ce0 <= grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_3_ce0;
    embed_lut_4_address0 <= grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_4_address0;
    embed_lut_4_ce0 <= grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_4_ce0;
    embed_lut_5_address0 <= grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_5_address0;
    embed_lut_5_ce0 <= grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_5_ce0;
    embed_lut_6_address0 <= grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_6_address0;
    embed_lut_6_ce0 <= grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_6_ce0;
    embed_lut_7_address0 <= grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_7_address0;
    embed_lut_7_ce0 <= grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_lut_7_ce0;
    embed_out_address0 <= grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_out_address0;
    embed_out_ce0 <= grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_out_ce0;
    embed_out_d0 <= grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_out_d0;
    embed_out_we0 <= grp_gelu_embed_kernel_Pipeline_embed_fu_2616_embed_out_we0;
    gelu_out_address0 <= grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_gelu_out_address0;
    gelu_out_ce0 <= grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_gelu_out_ce0;
    gelu_out_d0 <= grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_gelu_out_d0;
    gelu_out_we0 <= grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_gelu_out_we0;
    grp_gelu_embed_kernel_Pipeline_embed_fu_2616_ap_start <= grp_gelu_embed_kernel_Pipeline_embed_fu_2616_ap_start_reg;
    grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_ap_start <= grp_gelu_embed_kernel_Pipeline_gelu_fu_2096_ap_start_reg;
    token_ids_address0 <= grp_gelu_embed_kernel_Pipeline_embed_fu_2616_token_ids_address0;
    token_ids_ce0 <= grp_gelu_embed_kernel_Pipeline_embed_fu_2616_token_ids_ce0;
end behav;
