-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity layernorm_kernel is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    X_0 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_4 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_5 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_6 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_7 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_8 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_9 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_10 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_11 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_12 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_13 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_14 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_15 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_16 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_17 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_18 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_19 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_20 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_21 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_22 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_23 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_24 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_25 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_26 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_27 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_28 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_29 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_30 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_31 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_32 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_33 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_34 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_35 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_36 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_37 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_38 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_39 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_40 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_41 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_42 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_43 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_44 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_45 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_46 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_47 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_48 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_49 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_50 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_51 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_52 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_53 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_54 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_55 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_56 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_57 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_58 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_59 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_60 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_61 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_62 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_63 : IN STD_LOGIC_VECTOR (7 downto 0);
    Y_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    Y_ce0 : OUT STD_LOGIC;
    Y_we0 : OUT STD_LOGIC;
    Y_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of layernorm_kernel is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "layernorm_kernel_layernorm_kernel,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.299533,HLS_SYN_LAT=168,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2605,HLS_SYN_LUT=3759,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (34 downto 0) := "00000000001000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (34 downto 0) := "00000000010000000000000000000000000";
    constant ap_ST_fsm_state27 : STD_LOGIC_VECTOR (34 downto 0) := "00000000100000000000000000000000000";
    constant ap_ST_fsm_state28 : STD_LOGIC_VECTOR (34 downto 0) := "00000001000000000000000000000000000";
    constant ap_ST_fsm_state29 : STD_LOGIC_VECTOR (34 downto 0) := "00000010000000000000000000000000000";
    constant ap_ST_fsm_state30 : STD_LOGIC_VECTOR (34 downto 0) := "00000100000000000000000000000000000";
    constant ap_ST_fsm_state31 : STD_LOGIC_VECTOR (34 downto 0) := "00001000000000000000000000000000000";
    constant ap_ST_fsm_state32 : STD_LOGIC_VECTOR (34 downto 0) := "00010000000000000000000000000000000";
    constant ap_ST_fsm_state33 : STD_LOGIC_VECTOR (34 downto 0) := "00100000000000000000000000000000000";
    constant ap_ST_fsm_state34 : STD_LOGIC_VECTOR (34 downto 0) := "01000000000000000000000000000000000";
    constant ap_ST_fsm_state35 : STD_LOGIC_VECTOR (34 downto 0) := "10000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_21 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100001";
    constant ap_const_lv32_22 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100010";
    constant ap_const_lv64_3FE0000000000000 : STD_LOGIC_VECTOR (63 downto 0) := "0011111111100000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_4020000000000000 : STD_LOGIC_VECTOR (63 downto 0) := "0100000000100000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_3FF0000000000000 : STD_LOGIC_VECTOR (63 downto 0) := "0011111111110000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv25_0 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000000";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv36_100000 : STD_LOGIC_VECTOR (35 downto 0) := "000000000000000100000000000000000000";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv6_1E : STD_LOGIC_VECTOR (5 downto 0) := "011110";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_36 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110110";
    constant ap_const_lv11_3FF : STD_LOGIC_VECTOR (10 downto 0) := "01111111111";
    constant ap_const_lv11_3FE : STD_LOGIC_VECTOR (10 downto 0) := "01111111110";
    constant ap_const_lv5_C : STD_LOGIC_VECTOR (4 downto 0) := "01100";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv24_800 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000100000000000";
    constant ap_const_lv24_8000 : STD_LOGIC_VECTOR (23 downto 0) := "000000001000000000000000";
    constant ap_const_lv22_0 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv61_1800000000000 : STD_LOGIC_VECTOR (60 downto 0) := "0000000000001100000000000000000000000000000000000000000000000";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv32_3B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111011";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv72_1800000000000 : STD_LOGIC_VECTOR (71 downto 0) := "000000000000000000000001100000000000000000000000000000000000000000000000";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal X_0_read_reg_1824 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_1_read_reg_1830 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_2_read_reg_1836 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_3_read_reg_1842 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_4_read_reg_1848 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_5_read_reg_1854 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_6_read_reg_1860 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_7_read_reg_1866 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_8_read_reg_1872 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_9_read_reg_1878 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_10_read_reg_1884 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_11_read_reg_1890 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_12_read_reg_1896 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_13_read_reg_1902 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_14_read_reg_1908 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_15_read_reg_1914 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_16_read_reg_1920 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_17_read_reg_1926 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_18_read_reg_1932 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_19_read_reg_1938 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_20_read_reg_1944 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_21_read_reg_1950 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_22_read_reg_1956 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_23_read_reg_1962 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_24_read_reg_1968 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_25_read_reg_1974 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_26_read_reg_1980 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_27_read_reg_1986 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_28_read_reg_1992 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_29_read_reg_1998 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_30_read_reg_2004 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_31_read_reg_2010 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_32_read_reg_2016 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_33_read_reg_2022 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_34_read_reg_2028 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_35_read_reg_2034 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_36_read_reg_2040 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_37_read_reg_2046 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_38_read_reg_2052 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_39_read_reg_2058 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_40_read_reg_2064 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_41_read_reg_2070 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_42_read_reg_2076 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_43_read_reg_2082 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_44_read_reg_2088 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_45_read_reg_2094 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_46_read_reg_2100 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_47_read_reg_2106 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_48_read_reg_2112 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_49_read_reg_2118 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_50_read_reg_2124 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_51_read_reg_2130 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_52_read_reg_2136 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_53_read_reg_2142 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_54_read_reg_2148 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_55_read_reg_2154 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_56_read_reg_2160 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_57_read_reg_2166 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_58_read_reg_2172 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_59_read_reg_2178 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_60_read_reg_2184 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_61_read_reg_2190 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_62_read_reg_2196 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_63_read_reg_2202 : STD_LOGIC_VECTOR (7 downto 0);
    signal mean_fu_962_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal mean_reg_2208 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal sext_ln23_1_fu_970_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal var_reg_2224 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal tmp_6_fu_1066_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_2230 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln24_fu_1080_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal select_ln24_reg_2235 : STD_LOGIC_VECTOR (22 downto 0);
    signal LD_fu_1179_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal LD_reg_2241 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal bitcast_ln758_fu_1191_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal var_1_fu_1206_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal var_1_reg_2251 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal tmp_10_reg_2258 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln24_2_fu_1226_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal select_ln24_2_reg_2264 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal LD_1_fu_1319_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal LD_1_reg_2270 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal bitcast_ln758_1_fu_1331_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal grp_fu_896_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_reg_2280 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal var_3_fu_1335_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal var_3_reg_2285 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal tmp_14_fu_1341_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_reg_2296 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln6_fu_1355_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal select_ln6_reg_2301 : STD_LOGIC_VECTOR (23 downto 0);
    signal LD_2_fu_1450_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal LD_2_reg_2307 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal bitcast_ln758_2_fu_1462_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal sub_ln9_3_fu_1501_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal sub_ln9_3_reg_2317 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_16_reg_2322 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal add_ln9_1_fu_1534_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal add_ln9_1_reg_2329 : STD_LOGIC_VECTOR (47 downto 0);
    signal select_ln9_fu_1551_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal select_ln9_reg_2334 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal sub_ln9_5_fu_1599_p2 : STD_LOGIC_VECTOR (59 downto 0);
    signal sub_ln9_5_reg_2341 : STD_LOGIC_VECTOR (59 downto 0);
    signal add_ln9_3_fu_1632_p2 : STD_LOGIC_VECTOR (59 downto 0);
    signal add_ln9_3_reg_2346 : STD_LOGIC_VECTOR (59 downto 0);
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal sub_ln9_fu_1655_p2 : STD_LOGIC_VECTOR (60 downto 0);
    signal sub_ln9_reg_2351 : STD_LOGIC_VECTOR (60 downto 0);
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal sub_ln9_7_fu_1699_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal sub_ln9_7_reg_2357 : STD_LOGIC_VECTOR (71 downto 0);
    signal tmp_22_reg_2362 : STD_LOGIC_VECTOR (23 downto 0);
    signal select_ln9_2_fu_1758_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal select_ln9_2_reg_2367 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal mul_ln9_fu_903_p2 : STD_LOGIC_VECTOR (58 downto 0);
    signal mul_ln9_reg_2373 : STD_LOGIC_VECTOR (58 downto 0);
    signal ap_CS_fsm_state22 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state22 : signal is "none";
    signal ap_CS_fsm_state23 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state23 : signal is "none";
    signal sext_ln9_8_fu_1784_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln9_8_reg_2383 : STD_LOGIC_VECTOR (71 downto 0);
    signal grp_fu_907_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal mul_ln9_1_reg_2389 : STD_LOGIC_VECTOR (71 downto 0);
    signal ap_CS_fsm_state27 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state27 : signal is "none";
    signal sub_ln9_1_fu_1788_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal sub_ln9_1_reg_2394 : STD_LOGIC_VECTOR (71 downto 0);
    signal ap_CS_fsm_state28 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state28 : signal is "none";
    signal inv_reg_2399 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_state33 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state33 : signal is "none";
    signal grp_layernorm_kernel_Pipeline_accum_fu_690_ap_start : STD_LOGIC;
    signal grp_layernorm_kernel_Pipeline_accum_fu_690_ap_done : STD_LOGIC;
    signal grp_layernorm_kernel_Pipeline_accum_fu_690_ap_idle : STD_LOGIC;
    signal grp_layernorm_kernel_Pipeline_accum_fu_690_ap_ready : STD_LOGIC;
    signal grp_layernorm_kernel_Pipeline_accum_fu_690_sq_sum_out : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_layernorm_kernel_Pipeline_accum_fu_690_sq_sum_out_ap_vld : STD_LOGIC;
    signal grp_layernorm_kernel_Pipeline_accum_fu_690_sum_out : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_layernorm_kernel_Pipeline_accum_fu_690_sum_out_ap_vld : STD_LOGIC;
    signal grp_layernorm_kernel_Pipeline_norm_fu_824_ap_start : STD_LOGIC;
    signal grp_layernorm_kernel_Pipeline_norm_fu_824_ap_done : STD_LOGIC;
    signal grp_layernorm_kernel_Pipeline_norm_fu_824_ap_idle : STD_LOGIC;
    signal grp_layernorm_kernel_Pipeline_norm_fu_824_ap_ready : STD_LOGIC;
    signal grp_layernorm_kernel_Pipeline_norm_fu_824_Y_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_layernorm_kernel_Pipeline_norm_fu_824_Y_ce0 : STD_LOGIC;
    signal grp_layernorm_kernel_Pipeline_norm_fu_824_Y_we0 : STD_LOGIC;
    signal grp_layernorm_kernel_Pipeline_norm_fu_824_Y_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_layernorm_kernel_Pipeline_accum_fu_690_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_layernorm_kernel_Pipeline_norm_fu_824_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state34 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state34 : signal is "none";
    signal ap_CS_fsm_state35 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state35 : signal is "none";
    signal grp_fu_896_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_896_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_911_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_state29 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state29 : signal is "none";
    signal sext_ln22_fu_918_p0 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_fu_922_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln22_fu_918_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal sub_ln22_fu_930_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal zext_ln_fu_946_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_19_cast_fu_936_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_fu_922_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln22_1_fu_956_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln_fu_946_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln23_fu_977_p0 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_5_fu_981_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln23_fu_977_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal sub_ln23_1_fu_989_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_20_cast_fu_995_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln1_fu_1011_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_5_fu_981_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln23_2_fu_1005_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln1_fu_1011_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln23_fu_1021_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal shl_ln_fu_1029_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_fu_1803_p3 : STD_LOGIC_VECTOR (35 downto 0);
    signal add_ln23_fu_1041_p2 : STD_LOGIC_VECTOR (35 downto 0);
    attribute use_dsp : string;
    attribute use_dsp of add_ln23_fu_1041_p2 : signal is "no";
    signal var_cast_fu_1056_p4 : STD_LOGIC_VECTOR (22 downto 0);
    signal sub_ln24_fu_1074_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_2_fu_1091_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_2_fu_1091_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln24_fu_1099_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln24_fu_1110_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln24_fu_1107_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln24_1_fu_1116_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln24_fu_1120_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal lshr_ln_fu_1126_p4 : STD_LOGIC_VECTOR (62 downto 0);
    signal tmp_8_fu_1140_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln24_1_fu_1103_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln24_1_fu_1156_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln24_fu_1162_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln24_1_fu_1148_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln24_1_fu_1166_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln24_4_fu_1136_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_3_fu_1172_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln24_fu_1195_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_1200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln24_2_fu_1221_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_9_fu_1232_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln24_2_fu_1239_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln24_2_fu_1250_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln24_2_fu_1247_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln24_3_fu_1256_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln24_1_fu_1260_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal lshr_ln24_1_fu_1266_p4 : STD_LOGIC_VECTOR (62 downto 0);
    signal tmp_12_fu_1280_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln24_3_fu_1243_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln24_3_fu_1296_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln24_1_fu_1302_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln24_3_fu_1288_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln24_3_fu_1306_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln24_5_fu_1276_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_4_fu_1312_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln6_fu_1349_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_7_fu_1363_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln6_fu_1370_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln6_fu_1381_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln6_fu_1378_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln6_1_fu_1387_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln6_fu_1391_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal lshr_ln6_fu_1397_p4 : STD_LOGIC_VECTOR (62 downto 0);
    signal tmp_15_fu_1411_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln6_1_fu_1374_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln6_1_fu_1427_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln6_fu_1433_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln6_1_fu_1419_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln6_1_fu_1437_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln6_2_fu_1407_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_11_fu_1443_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_17_fu_1473_p3 : STD_LOGIC_VECTOR (45 downto 0);
    signal p_shl1_fu_1466_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln9_1_fu_1480_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_18_fu_1490_p3 : STD_LOGIC_VECTOR (43 downto 0);
    signal sub_ln9_2_fu_1484_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln9_3_fu_1497_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_19_fu_1507_p3 : STD_LOGIC_VECTOR (41 downto 0);
    signal sext_ln9_5_fu_1514_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_20_fu_1523_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal add_ln9_fu_1518_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln9_9_fu_1530_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal shl_ln9_1_fu_1540_p3 : STD_LOGIC_VECTOR (46 downto 0);
    signal sext_ln9_2_fu_1547_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal trunc_ln9_fu_1557_p1 : STD_LOGIC_VECTOR (46 downto 0);
    signal tmp_23_fu_1569_p3 : STD_LOGIC_VECTOR (58 downto 0);
    signal p_shl2_fu_1561_p3 : STD_LOGIC_VECTOR (59 downto 0);
    signal sext_ln9_10_fu_1577_p1 : STD_LOGIC_VECTOR (59 downto 0);
    signal tmp_24_fu_1587_p3 : STD_LOGIC_VECTOR (56 downto 0);
    signal sub_ln9_4_fu_1581_p2 : STD_LOGIC_VECTOR (59 downto 0);
    signal sext_ln9_11_fu_1595_p1 : STD_LOGIC_VECTOR (59 downto 0);
    signal tmp_25_fu_1605_p3 : STD_LOGIC_VECTOR (54 downto 0);
    signal sext_ln9_12_fu_1612_p1 : STD_LOGIC_VECTOR (59 downto 0);
    signal tmp_26_fu_1621_p3 : STD_LOGIC_VECTOR (52 downto 0);
    signal add_ln9_2_fu_1616_p2 : STD_LOGIC_VECTOR (59 downto 0);
    signal sext_ln9_13_fu_1628_p1 : STD_LOGIC_VECTOR (59 downto 0);
    signal shl_ln9_2_fu_1638_p3 : STD_LOGIC_VECTOR (59 downto 0);
    signal select_ln9_1_fu_1645_p3 : STD_LOGIC_VECTOR (59 downto 0);
    signal sext_ln9_4_fu_1651_p1 : STD_LOGIC_VECTOR (60 downto 0);
    signal trunc_ln9_1_fu_1661_p1 : STD_LOGIC_VECTOR (58 downto 0);
    signal p_shl_fu_1665_p3 : STD_LOGIC_VECTOR (71 downto 0);
    signal p_shl3_fu_1673_p3 : STD_LOGIC_VECTOR (71 downto 0);
    signal tmp_27_fu_1687_p3 : STD_LOGIC_VECTOR (69 downto 0);
    signal sub_ln9_6_fu_1681_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln9_14_fu_1695_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal tmp_28_fu_1715_p3 : STD_LOGIC_VECTOR (67 downto 0);
    signal sext_ln9_15_fu_1722_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal tmp_29_fu_1731_p3 : STD_LOGIC_VECTOR (65 downto 0);
    signal add_ln9_4_fu_1726_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln9_16_fu_1738_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal add_ln9_5_fu_1742_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal tmp_21_fu_1748_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal shl_ln9_fu_1764_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal grp_fu_911_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal grp_fu_1803_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_1803_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_896_opcode : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (34 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_ST_fsm_state23_blk : STD_LOGIC;
    signal ap_ST_fsm_state24_blk : STD_LOGIC;
    signal ap_ST_fsm_state25_blk : STD_LOGIC;
    signal ap_ST_fsm_state26_blk : STD_LOGIC;
    signal ap_ST_fsm_state27_blk : STD_LOGIC;
    signal ap_ST_fsm_state28_blk : STD_LOGIC;
    signal ap_ST_fsm_state29_blk : STD_LOGIC;
    signal ap_ST_fsm_state30_blk : STD_LOGIC;
    signal ap_ST_fsm_state31_blk : STD_LOGIC;
    signal ap_ST_fsm_state32_blk : STD_LOGIC;
    signal ap_ST_fsm_state33_blk : STD_LOGIC;
    signal ap_ST_fsm_state34_blk : STD_LOGIC;
    signal ap_ST_fsm_state35_blk : STD_LOGIC;
    signal tmp_2_fu_1091_p0 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_2_fu_1091_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_1232_p0 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_9_fu_1232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_1363_p0 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_7_fu_1363_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component layernorm_kernel_layernorm_kernel_Pipeline_accum IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        X_0_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_1_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_2_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_3_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_4_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_5_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_6_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_7_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_8_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_9_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_10_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_11_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_12_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_13_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_14_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_15_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_16_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_17_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_18_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_19_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_20_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_21_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_22_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_23_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_24_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_25_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_26_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_27_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_28_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_29_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_30_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_31_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_32_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_33_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_34_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_35_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_36_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_37_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_38_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_39_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_40_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_41_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_42_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_43_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_44_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_45_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_46_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_47_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_48_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_49_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_50_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_51_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_52_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_53_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_54_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_55_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_56_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_57_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_58_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_59_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_60_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_61_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_62_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_63_load : IN STD_LOGIC_VECTOR (7 downto 0);
        sq_sum_out : OUT STD_LOGIC_VECTOR (23 downto 0);
        sq_sum_out_ap_vld : OUT STD_LOGIC;
        sum_out : OUT STD_LOGIC_VECTOR (23 downto 0);
        sum_out_ap_vld : OUT STD_LOGIC );
    end component;


    component layernorm_kernel_layernorm_kernel_Pipeline_norm IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        X_0_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_1_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_2_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_3_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_4_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_5_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_6_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_7_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_8_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_9_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_10_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_11_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_12_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_13_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_14_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_15_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_16_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_17_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_18_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_19_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_20_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_21_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_22_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_23_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_24_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_25_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_26_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_27_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_28_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_29_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_30_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_31_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_32_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_33_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_34_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_35_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_36_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_37_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_38_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_39_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_40_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_41_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_42_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_43_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_44_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_45_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_46_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_47_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_48_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_49_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_50_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_51_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_52_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_53_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_54_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_55_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_56_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_57_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_58_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_59_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_60_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_61_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_62_load : IN STD_LOGIC_VECTOR (7 downto 0);
        X_63_load : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln29 : IN STD_LOGIC_VECTOR (17 downto 0);
        sext_ln27 : IN STD_LOGIC_VECTOR (23 downto 0);
        Y_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        Y_ce0 : OUT STD_LOGIC;
        Y_we0 : OUT STD_LOGIC;
        Y_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component layernorm_kernel_dcmp_64ns_64ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component layernorm_kernel_mul_35s_24s_59_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (34 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        dout : OUT STD_LOGIC_VECTOR (58 downto 0) );
    end component;


    component layernorm_kernel_mul_59s_24s_72_5_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (58 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (71 downto 0) );
    end component;


    component layernorm_kernel_mul_72s_24s_72_5_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (71 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (71 downto 0) );
    end component;


    component layernorm_kernel_ctlz_24_24_1_1 IS
    generic (
        din_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din : IN STD_LOGIC_VECTOR (23 downto 0);
        dout : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component layernorm_kernel_mac_mulsub_18s_18s_30s_36_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (17 downto 0);
        din2 : IN STD_LOGIC_VECTOR (29 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (35 downto 0) );
    end component;



begin
    grp_layernorm_kernel_Pipeline_accum_fu_690 : component layernorm_kernel_layernorm_kernel_Pipeline_accum
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_layernorm_kernel_Pipeline_accum_fu_690_ap_start,
        ap_done => grp_layernorm_kernel_Pipeline_accum_fu_690_ap_done,
        ap_idle => grp_layernorm_kernel_Pipeline_accum_fu_690_ap_idle,
        ap_ready => grp_layernorm_kernel_Pipeline_accum_fu_690_ap_ready,
        X_0_load => X_0_read_reg_1824,
        X_1_load => X_1_read_reg_1830,
        X_2_load => X_2_read_reg_1836,
        X_3_load => X_3_read_reg_1842,
        X_4_load => X_4_read_reg_1848,
        X_5_load => X_5_read_reg_1854,
        X_6_load => X_6_read_reg_1860,
        X_7_load => X_7_read_reg_1866,
        X_8_load => X_8_read_reg_1872,
        X_9_load => X_9_read_reg_1878,
        X_10_load => X_10_read_reg_1884,
        X_11_load => X_11_read_reg_1890,
        X_12_load => X_12_read_reg_1896,
        X_13_load => X_13_read_reg_1902,
        X_14_load => X_14_read_reg_1908,
        X_15_load => X_15_read_reg_1914,
        X_16_load => X_16_read_reg_1920,
        X_17_load => X_17_read_reg_1926,
        X_18_load => X_18_read_reg_1932,
        X_19_load => X_19_read_reg_1938,
        X_20_load => X_20_read_reg_1944,
        X_21_load => X_21_read_reg_1950,
        X_22_load => X_22_read_reg_1956,
        X_23_load => X_23_read_reg_1962,
        X_24_load => X_24_read_reg_1968,
        X_25_load => X_25_read_reg_1974,
        X_26_load => X_26_read_reg_1980,
        X_27_load => X_27_read_reg_1986,
        X_28_load => X_28_read_reg_1992,
        X_29_load => X_29_read_reg_1998,
        X_30_load => X_30_read_reg_2004,
        X_31_load => X_31_read_reg_2010,
        X_32_load => X_32_read_reg_2016,
        X_33_load => X_33_read_reg_2022,
        X_34_load => X_34_read_reg_2028,
        X_35_load => X_35_read_reg_2034,
        X_36_load => X_36_read_reg_2040,
        X_37_load => X_37_read_reg_2046,
        X_38_load => X_38_read_reg_2052,
        X_39_load => X_39_read_reg_2058,
        X_40_load => X_40_read_reg_2064,
        X_41_load => X_41_read_reg_2070,
        X_42_load => X_42_read_reg_2076,
        X_43_load => X_43_read_reg_2082,
        X_44_load => X_44_read_reg_2088,
        X_45_load => X_45_read_reg_2094,
        X_46_load => X_46_read_reg_2100,
        X_47_load => X_47_read_reg_2106,
        X_48_load => X_48_read_reg_2112,
        X_49_load => X_49_read_reg_2118,
        X_50_load => X_50_read_reg_2124,
        X_51_load => X_51_read_reg_2130,
        X_52_load => X_52_read_reg_2136,
        X_53_load => X_53_read_reg_2142,
        X_54_load => X_54_read_reg_2148,
        X_55_load => X_55_read_reg_2154,
        X_56_load => X_56_read_reg_2160,
        X_57_load => X_57_read_reg_2166,
        X_58_load => X_58_read_reg_2172,
        X_59_load => X_59_read_reg_2178,
        X_60_load => X_60_read_reg_2184,
        X_61_load => X_61_read_reg_2190,
        X_62_load => X_62_read_reg_2196,
        X_63_load => X_63_read_reg_2202,
        sq_sum_out => grp_layernorm_kernel_Pipeline_accum_fu_690_sq_sum_out,
        sq_sum_out_ap_vld => grp_layernorm_kernel_Pipeline_accum_fu_690_sq_sum_out_ap_vld,
        sum_out => grp_layernorm_kernel_Pipeline_accum_fu_690_sum_out,
        sum_out_ap_vld => grp_layernorm_kernel_Pipeline_accum_fu_690_sum_out_ap_vld);

    grp_layernorm_kernel_Pipeline_norm_fu_824 : component layernorm_kernel_layernorm_kernel_Pipeline_norm
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_layernorm_kernel_Pipeline_norm_fu_824_ap_start,
        ap_done => grp_layernorm_kernel_Pipeline_norm_fu_824_ap_done,
        ap_idle => grp_layernorm_kernel_Pipeline_norm_fu_824_ap_idle,
        ap_ready => grp_layernorm_kernel_Pipeline_norm_fu_824_ap_ready,
        X_0_load => X_0_read_reg_1824,
        X_1_load => X_1_read_reg_1830,
        X_2_load => X_2_read_reg_1836,
        X_3_load => X_3_read_reg_1842,
        X_4_load => X_4_read_reg_1848,
        X_5_load => X_5_read_reg_1854,
        X_6_load => X_6_read_reg_1860,
        X_7_load => X_7_read_reg_1866,
        X_8_load => X_8_read_reg_1872,
        X_9_load => X_9_read_reg_1878,
        X_10_load => X_10_read_reg_1884,
        X_11_load => X_11_read_reg_1890,
        X_12_load => X_12_read_reg_1896,
        X_13_load => X_13_read_reg_1902,
        X_14_load => X_14_read_reg_1908,
        X_15_load => X_15_read_reg_1914,
        X_16_load => X_16_read_reg_1920,
        X_17_load => X_17_read_reg_1926,
        X_18_load => X_18_read_reg_1932,
        X_19_load => X_19_read_reg_1938,
        X_20_load => X_20_read_reg_1944,
        X_21_load => X_21_read_reg_1950,
        X_22_load => X_22_read_reg_1956,
        X_23_load => X_23_read_reg_1962,
        X_24_load => X_24_read_reg_1968,
        X_25_load => X_25_read_reg_1974,
        X_26_load => X_26_read_reg_1980,
        X_27_load => X_27_read_reg_1986,
        X_28_load => X_28_read_reg_1992,
        X_29_load => X_29_read_reg_1998,
        X_30_load => X_30_read_reg_2004,
        X_31_load => X_31_read_reg_2010,
        X_32_load => X_32_read_reg_2016,
        X_33_load => X_33_read_reg_2022,
        X_34_load => X_34_read_reg_2028,
        X_35_load => X_35_read_reg_2034,
        X_36_load => X_36_read_reg_2040,
        X_37_load => X_37_read_reg_2046,
        X_38_load => X_38_read_reg_2052,
        X_39_load => X_39_read_reg_2058,
        X_40_load => X_40_read_reg_2064,
        X_41_load => X_41_read_reg_2070,
        X_42_load => X_42_read_reg_2076,
        X_43_load => X_43_read_reg_2082,
        X_44_load => X_44_read_reg_2088,
        X_45_load => X_45_read_reg_2094,
        X_46_load => X_46_read_reg_2100,
        X_47_load => X_47_read_reg_2106,
        X_48_load => X_48_read_reg_2112,
        X_49_load => X_49_read_reg_2118,
        X_50_load => X_50_read_reg_2124,
        X_51_load => X_51_read_reg_2130,
        X_52_load => X_52_read_reg_2136,
        X_53_load => X_53_read_reg_2142,
        X_54_load => X_54_read_reg_2148,
        X_55_load => X_55_read_reg_2154,
        X_56_load => X_56_read_reg_2160,
        X_57_load => X_57_read_reg_2166,
        X_58_load => X_58_read_reg_2172,
        X_59_load => X_59_read_reg_2178,
        X_60_load => X_60_read_reg_2184,
        X_61_load => X_61_read_reg_2190,
        X_62_load => X_62_read_reg_2196,
        X_63_load => X_63_read_reg_2202,
        sext_ln29 => mean_reg_2208,
        sext_ln27 => inv_reg_2399,
        Y_address0 => grp_layernorm_kernel_Pipeline_norm_fu_824_Y_address0,
        Y_ce0 => grp_layernorm_kernel_Pipeline_norm_fu_824_Y_ce0,
        Y_we0 => grp_layernorm_kernel_Pipeline_norm_fu_824_Y_we0,
        Y_d0 => grp_layernorm_kernel_Pipeline_norm_fu_824_Y_d0);

    dcmp_64ns_64ns_1_2_no_dsp_1_U141 : component layernorm_kernel_dcmp_64ns_64ns_1_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_896_p0,
        din1 => grp_fu_896_p1,
        ce => ap_const_logic_1,
        opcode => grp_fu_896_opcode,
        dout => grp_fu_896_p2);

    mul_35s_24s_59_1_1_U142 : component layernorm_kernel_mul_35s_24s_59_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 35,
        din1_WIDTH => 24,
        dout_WIDTH => 59)
    port map (
        din0 => shl_ln9_fu_1764_p3,
        din1 => select_ln9_2_reg_2367,
        dout => mul_ln9_fu_903_p2);

    mul_59s_24s_72_5_1_U143 : component layernorm_kernel_mul_59s_24s_72_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 59,
        din1_WIDTH => 24,
        dout_WIDTH => 72)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => mul_ln9_reg_2373,
        din1 => select_ln9_2_reg_2367,
        ce => ap_const_logic_1,
        dout => grp_fu_907_p2);

    mul_72s_24s_72_5_1_U144 : component layernorm_kernel_mul_72s_24s_72_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 72,
        din1_WIDTH => 24,
        dout_WIDTH => 72)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sub_ln9_1_reg_2394,
        din1 => grp_fu_911_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_911_p2);

    ctlz_24_24_1_1_U145 : component layernorm_kernel_ctlz_24_24_1_1
    generic map (
        din_WIDTH => 24,
        dout_WIDTH => 24)
    port map (
        din => tmp_2_fu_1091_p1,
        dout => tmp_2_fu_1091_p3);

    ctlz_24_24_1_1_U146 : component layernorm_kernel_ctlz_24_24_1_1
    generic map (
        din_WIDTH => 24,
        dout_WIDTH => 24)
    port map (
        din => select_ln24_2_reg_2264,
        dout => tmp_9_fu_1232_p3);

    ctlz_24_24_1_1_U147 : component layernorm_kernel_ctlz_24_24_1_1
    generic map (
        din_WIDTH => 24,
        dout_WIDTH => 24)
    port map (
        din => select_ln6_reg_2301,
        dout => tmp_7_fu_1363_p3);

    mac_mulsub_18s_18s_30s_36_4_1_U148 : component layernorm_kernel_mac_mulsub_18s_18s_30s_36_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 18,
        din1_WIDTH => 18,
        din2_WIDTH => 30,
        dout_WIDTH => 36)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1803_p0,
        din1 => grp_fu_1803_p1,
        din2 => shl_ln_fu_1029_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_1803_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_layernorm_kernel_Pipeline_accum_fu_690_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_layernorm_kernel_Pipeline_accum_fu_690_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_layernorm_kernel_Pipeline_accum_fu_690_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_layernorm_kernel_Pipeline_accum_fu_690_ap_ready = ap_const_logic_1)) then 
                    grp_layernorm_kernel_Pipeline_accum_fu_690_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_layernorm_kernel_Pipeline_norm_fu_824_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_layernorm_kernel_Pipeline_norm_fu_824_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state34)) then 
                    grp_layernorm_kernel_Pipeline_norm_fu_824_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_layernorm_kernel_Pipeline_norm_fu_824_ap_ready = ap_const_logic_1)) then 
                    grp_layernorm_kernel_Pipeline_norm_fu_824_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                LD_1_reg_2270 <= LD_1_fu_1319_p5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then
                LD_2_reg_2307 <= LD_2_fu_1450_p5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                LD_reg_2241 <= LD_fu_1179_p5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                X_0_read_reg_1824 <= X_0;
                X_10_read_reg_1884 <= X_10;
                X_11_read_reg_1890 <= X_11;
                X_12_read_reg_1896 <= X_12;
                X_13_read_reg_1902 <= X_13;
                X_14_read_reg_1908 <= X_14;
                X_15_read_reg_1914 <= X_15;
                X_16_read_reg_1920 <= X_16;
                X_17_read_reg_1926 <= X_17;
                X_18_read_reg_1932 <= X_18;
                X_19_read_reg_1938 <= X_19;
                X_1_read_reg_1830 <= X_1;
                X_20_read_reg_1944 <= X_20;
                X_21_read_reg_1950 <= X_21;
                X_22_read_reg_1956 <= X_22;
                X_23_read_reg_1962 <= X_23;
                X_24_read_reg_1968 <= X_24;
                X_25_read_reg_1974 <= X_25;
                X_26_read_reg_1980 <= X_26;
                X_27_read_reg_1986 <= X_27;
                X_28_read_reg_1992 <= X_28;
                X_29_read_reg_1998 <= X_29;
                X_2_read_reg_1836 <= X_2;
                X_30_read_reg_2004 <= X_30;
                X_31_read_reg_2010 <= X_31;
                X_32_read_reg_2016 <= X_32;
                X_33_read_reg_2022 <= X_33;
                X_34_read_reg_2028 <= X_34;
                X_35_read_reg_2034 <= X_35;
                X_36_read_reg_2040 <= X_36;
                X_37_read_reg_2046 <= X_37;
                X_38_read_reg_2052 <= X_38;
                X_39_read_reg_2058 <= X_39;
                X_3_read_reg_1842 <= X_3;
                X_40_read_reg_2064 <= X_40;
                X_41_read_reg_2070 <= X_41;
                X_42_read_reg_2076 <= X_42;
                X_43_read_reg_2082 <= X_43;
                X_44_read_reg_2088 <= X_44;
                X_45_read_reg_2094 <= X_45;
                X_46_read_reg_2100 <= X_46;
                X_47_read_reg_2106 <= X_47;
                X_48_read_reg_2112 <= X_48;
                X_49_read_reg_2118 <= X_49;
                X_4_read_reg_1848 <= X_4;
                X_50_read_reg_2124 <= X_50;
                X_51_read_reg_2130 <= X_51;
                X_52_read_reg_2136 <= X_52;
                X_53_read_reg_2142 <= X_53;
                X_54_read_reg_2148 <= X_54;
                X_55_read_reg_2154 <= X_55;
                X_56_read_reg_2160 <= X_56;
                X_57_read_reg_2166 <= X_57;
                X_58_read_reg_2172 <= X_58;
                X_59_read_reg_2178 <= X_59;
                X_5_read_reg_1854 <= X_5;
                X_60_read_reg_2184 <= X_60;
                X_61_read_reg_2190 <= X_61;
                X_62_read_reg_2196 <= X_62;
                X_63_read_reg_2202 <= X_63;
                X_6_read_reg_1860 <= X_6;
                X_7_read_reg_1866 <= X_7;
                X_8_read_reg_1872 <= X_8;
                X_9_read_reg_1878 <= X_9;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state17)) then
                    add_ln9_1_reg_2329(47 downto 16) <= add_ln9_1_fu_1534_p2(47 downto 16);
                tmp_16_reg_2322 <= grp_fu_896_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state19)) then
                    add_ln9_3_reg_2346(59 downto 21) <= add_ln9_3_fu_1632_p2(59 downto 21);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state33)) then
                inv_reg_2399 <= grp_fu_911_p2(71 downto 48);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                mean_reg_2208 <= mean_fu_962_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state27)) then
                mul_ln9_1_reg_2389 <= grp_fu_907_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state22)) then
                mul_ln9_reg_2373 <= mul_ln9_fu_903_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                select_ln24_2_reg_2264 <= select_ln24_2_fu_1226_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                select_ln24_reg_2235 <= select_ln24_fu_1080_p3;
                tmp_6_reg_2230 <= add_ln23_fu_1041_p2(35 downto 35);
                var_reg_2224 <= add_ln23_fu_1041_p2(35 downto 12);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state14)) then
                select_ln6_reg_2301 <= select_ln6_fu_1355_p3;
                tmp_14_reg_2296 <= var_3_fu_1335_p3(23 downto 23);
                var_3_reg_2285 <= var_3_fu_1335_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state21)) then
                select_ln9_2_reg_2367 <= select_ln9_2_fu_1758_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state18)) then
                    select_ln9_reg_2334(47 downto 16) <= select_ln9_fu_1551_p3(47 downto 16);
                    sub_ln9_5_reg_2341(59 downto 25) <= sub_ln9_5_fu_1599_p2(59 downto 25);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state23)) then
                sext_ln9_8_reg_2383 <= sext_ln9_8_fu_1784_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state28)) then
                sub_ln9_1_reg_2394 <= sub_ln9_1_fu_1788_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state16)) then
                    sub_ln9_3_reg_2317(47 downto 20) <= sub_ln9_3_fu_1501_p2(47 downto 20);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state20)) then
                    sub_ln9_7_reg_2357(71 downto 30) <= sub_ln9_7_fu_1699_p2(71 downto 30);
                    sub_ln9_reg_2351(60 downto 21) <= sub_ln9_fu_1655_p2(60 downto 21);
                tmp_22_reg_2362 <= sub_ln9_fu_1655_p2(59 downto 36);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                tmp_10_reg_2258 <= var_1_fu_1206_p3(23 downto 23);
                var_1_reg_2251 <= var_1_fu_1206_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state13)) then
                tmp_13_reg_2280 <= grp_fu_896_p2;
            end if;
        end if;
    end process;
    sub_ln9_3_reg_2317(19 downto 0) <= "00000000000000000000";
    add_ln9_1_reg_2329(15 downto 0) <= "0000000000000000";
    select_ln9_reg_2334(15 downto 0) <= "0000000000000000";
    sub_ln9_5_reg_2341(24 downto 0) <= "0000000000000000000000000";
    add_ln9_3_reg_2346(20 downto 0) <= "000000000000000000000";
    sub_ln9_reg_2351(20 downto 0) <= "000000000000000000000";
    sub_ln9_7_reg_2357(29 downto 0) <= "000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_layernorm_kernel_Pipeline_accum_fu_690_ap_done, grp_layernorm_kernel_Pipeline_norm_fu_824_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state35)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_layernorm_kernel_Pipeline_accum_fu_690_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state26;
            when ap_ST_fsm_state26 => 
                ap_NS_fsm <= ap_ST_fsm_state27;
            when ap_ST_fsm_state27 => 
                ap_NS_fsm <= ap_ST_fsm_state28;
            when ap_ST_fsm_state28 => 
                ap_NS_fsm <= ap_ST_fsm_state29;
            when ap_ST_fsm_state29 => 
                ap_NS_fsm <= ap_ST_fsm_state30;
            when ap_ST_fsm_state30 => 
                ap_NS_fsm <= ap_ST_fsm_state31;
            when ap_ST_fsm_state31 => 
                ap_NS_fsm <= ap_ST_fsm_state32;
            when ap_ST_fsm_state32 => 
                ap_NS_fsm <= ap_ST_fsm_state33;
            when ap_ST_fsm_state33 => 
                ap_NS_fsm <= ap_ST_fsm_state34;
            when ap_ST_fsm_state34 => 
                ap_NS_fsm <= ap_ST_fsm_state35;
            when ap_ST_fsm_state35 => 
                if (((grp_layernorm_kernel_Pipeline_norm_fu_824_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state35))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state35;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    LD_1_fu_1319_p5 <= (tmp_4_fu_1312_p3 & zext_ln24_5_fu_1276_p1(51 downto 0));
    LD_2_fu_1450_p5 <= (tmp_11_fu_1443_p3 & zext_ln6_2_fu_1407_p1(51 downto 0));
    LD_fu_1179_p5 <= (tmp_3_fu_1172_p3 & zext_ln24_4_fu_1136_p1(51 downto 0));
    Y_address0 <= grp_layernorm_kernel_Pipeline_norm_fu_824_Y_address0;
    Y_ce0 <= grp_layernorm_kernel_Pipeline_norm_fu_824_Y_ce0;
    Y_d0 <= grp_layernorm_kernel_Pipeline_norm_fu_824_Y_d0;
    Y_we0 <= grp_layernorm_kernel_Pipeline_norm_fu_824_Y_we0;
    add_ln23_fu_1041_p2 <= std_logic_vector(signed(grp_fu_1803_p3) + signed(ap_const_lv36_100000));
    add_ln24_1_fu_1166_p2 <= std_logic_vector(signed(sext_ln24_fu_1162_p1) + signed(select_ln24_1_fu_1148_p3));
    add_ln24_2_fu_1250_p2 <= std_logic_vector(unsigned(trunc_ln24_2_fu_1239_p1) + unsigned(ap_const_lv6_1E));
    add_ln24_3_fu_1306_p2 <= std_logic_vector(signed(sext_ln24_1_fu_1302_p1) + signed(select_ln24_3_fu_1288_p3));
    add_ln24_fu_1110_p2 <= std_logic_vector(unsigned(trunc_ln24_fu_1099_p1) + unsigned(ap_const_lv6_1E));
    add_ln6_1_fu_1437_p2 <= std_logic_vector(signed(sext_ln6_fu_1433_p1) + signed(select_ln6_1_fu_1419_p3));
    add_ln6_fu_1381_p2 <= std_logic_vector(unsigned(trunc_ln6_fu_1370_p1) + unsigned(ap_const_lv6_1E));
    add_ln9_1_fu_1534_p2 <= std_logic_vector(unsigned(add_ln9_fu_1518_p2) + unsigned(sext_ln9_9_fu_1530_p1));
    add_ln9_2_fu_1616_p2 <= std_logic_vector(unsigned(sub_ln9_5_reg_2341) + unsigned(sext_ln9_12_fu_1612_p1));
    add_ln9_3_fu_1632_p2 <= std_logic_vector(unsigned(add_ln9_2_fu_1616_p2) + unsigned(sext_ln9_13_fu_1628_p1));
    add_ln9_4_fu_1726_p2 <= std_logic_vector(unsigned(sub_ln9_7_reg_2357) + unsigned(sext_ln9_15_fu_1722_p1));
    add_ln9_5_fu_1742_p2 <= std_logic_vector(unsigned(add_ln9_4_fu_1726_p2) + unsigned(sext_ln9_16_fu_1738_p1));
    add_ln9_fu_1518_p2 <= std_logic_vector(unsigned(sub_ln9_3_reg_2317) + unsigned(sext_ln9_5_fu_1514_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state21 <= ap_CS_fsm(20);
    ap_CS_fsm_state22 <= ap_CS_fsm(21);
    ap_CS_fsm_state23 <= ap_CS_fsm(22);
    ap_CS_fsm_state27 <= ap_CS_fsm(26);
    ap_CS_fsm_state28 <= ap_CS_fsm(27);
    ap_CS_fsm_state29 <= ap_CS_fsm(28);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state33 <= ap_CS_fsm(32);
    ap_CS_fsm_state34 <= ap_CS_fsm(33);
    ap_CS_fsm_state35 <= ap_CS_fsm(34);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state20_blk <= ap_const_logic_0;
    ap_ST_fsm_state21_blk <= ap_const_logic_0;
    ap_ST_fsm_state22_blk <= ap_const_logic_0;
    ap_ST_fsm_state23_blk <= ap_const_logic_0;
    ap_ST_fsm_state24_blk <= ap_const_logic_0;
    ap_ST_fsm_state25_blk <= ap_const_logic_0;
    ap_ST_fsm_state26_blk <= ap_const_logic_0;
    ap_ST_fsm_state27_blk <= ap_const_logic_0;
    ap_ST_fsm_state28_blk <= ap_const_logic_0;
    ap_ST_fsm_state29_blk <= ap_const_logic_0;

    ap_ST_fsm_state2_blk_assign_proc : process(grp_layernorm_kernel_Pipeline_accum_fu_690_ap_done)
    begin
        if ((grp_layernorm_kernel_Pipeline_accum_fu_690_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state30_blk <= ap_const_logic_0;
    ap_ST_fsm_state31_blk <= ap_const_logic_0;
    ap_ST_fsm_state32_blk <= ap_const_logic_0;
    ap_ST_fsm_state33_blk <= ap_const_logic_0;
    ap_ST_fsm_state34_blk <= ap_const_logic_0;

    ap_ST_fsm_state35_blk_assign_proc : process(grp_layernorm_kernel_Pipeline_norm_fu_824_ap_done)
    begin
        if ((grp_layernorm_kernel_Pipeline_norm_fu_824_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state35_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state35_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(grp_layernorm_kernel_Pipeline_norm_fu_824_ap_done, ap_CS_fsm_state35)
    begin
        if (((grp_layernorm_kernel_Pipeline_norm_fu_824_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state35))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_layernorm_kernel_Pipeline_norm_fu_824_ap_done, ap_CS_fsm_state35)
    begin
        if (((grp_layernorm_kernel_Pipeline_norm_fu_824_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state35))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bitcast_ln758_1_fu_1331_p1 <= LD_1_reg_2270;
    bitcast_ln758_2_fu_1462_p1 <= LD_2_reg_2307;
    bitcast_ln758_fu_1191_p1 <= LD_reg_2241;
    empty_fu_1200_p2 <= (icmp_ln24_fu_1195_p2 or grp_fu_896_p2);
    grp_fu_1803_p0 <= sext_ln23_1_fu_970_p1(18 - 1 downto 0);
    grp_fu_1803_p1 <= sext_ln23_1_fu_970_p1(18 - 1 downto 0);

    grp_fu_896_opcode_assign_proc : process(ap_CS_fsm_state8, ap_CS_fsm_state12, ap_CS_fsm_state16)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_896_opcode <= ap_const_lv5_2;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            grp_fu_896_opcode <= ap_const_lv5_4;
        else 
            grp_fu_896_opcode <= "XXXXX";
        end if; 
    end process;


    grp_fu_896_p0_assign_proc : process(bitcast_ln758_fu_1191_p1, ap_CS_fsm_state8, bitcast_ln758_1_fu_1331_p1, ap_CS_fsm_state12, bitcast_ln758_2_fu_1462_p1, ap_CS_fsm_state16)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            grp_fu_896_p0 <= bitcast_ln758_2_fu_1462_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_896_p0 <= bitcast_ln758_1_fu_1331_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_896_p0 <= bitcast_ln758_fu_1191_p1;
        else 
            grp_fu_896_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_896_p1_assign_proc : process(ap_CS_fsm_state8, ap_CS_fsm_state12, ap_CS_fsm_state16)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            grp_fu_896_p1 <= ap_const_lv64_3FF0000000000000;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_896_p1 <= ap_const_lv64_4020000000000000;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_896_p1 <= ap_const_lv64_3FE0000000000000;
        else 
            grp_fu_896_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_fu_911_p1 <= sext_ln9_8_reg_2383(24 - 1 downto 0);
    grp_layernorm_kernel_Pipeline_accum_fu_690_ap_start <= grp_layernorm_kernel_Pipeline_accum_fu_690_ap_start_reg;
    grp_layernorm_kernel_Pipeline_norm_fu_824_ap_start <= grp_layernorm_kernel_Pipeline_norm_fu_824_ap_start_reg;
    icmp_ln24_fu_1195_p2 <= "1" when (var_reg_2224 = ap_const_lv24_0) else "0";
    lshr_ln24_1_fu_1266_p4 <= shl_ln24_1_fu_1260_p2(63 downto 1);
    lshr_ln6_fu_1397_p4 <= shl_ln6_fu_1391_p2(63 downto 1);
    lshr_ln_fu_1126_p4 <= shl_ln24_fu_1120_p2(63 downto 1);
    mean_fu_962_p3 <= 
        sub_ln22_1_fu_956_p2 when (tmp_fu_922_p3(0) = '1') else 
        zext_ln_fu_946_p4;
    p_shl1_fu_1466_p3 <= (var_3_reg_2285 & ap_const_lv24_0);
    p_shl2_fu_1561_p3 <= (trunc_ln9_fu_1557_p1 & ap_const_lv13_0);
    p_shl3_fu_1673_p3 <= (sub_ln9_fu_1655_p2 & ap_const_lv11_0);
    p_shl_fu_1665_p3 <= (trunc_ln9_1_fu_1661_p1 & ap_const_lv13_0);
    select_ln23_fu_1021_p3 <= 
        sub_ln23_2_fu_1005_p2 when (tmp_5_fu_981_p3(0) = '1') else 
        zext_ln1_fu_1011_p4;
    select_ln24_1_fu_1148_p3 <= 
        ap_const_lv11_3FF when (tmp_8_fu_1140_p3(0) = '1') else 
        ap_const_lv11_3FE;
    select_ln24_2_fu_1226_p3 <= 
        sub_ln24_2_fu_1221_p2 when (tmp_10_reg_2258(0) = '1') else 
        var_1_reg_2251;
    select_ln24_3_fu_1288_p3 <= 
        ap_const_lv11_3FF when (tmp_12_fu_1280_p3(0) = '1') else 
        ap_const_lv11_3FE;
    select_ln24_fu_1080_p3 <= 
        sub_ln24_fu_1074_p2 when (tmp_6_fu_1066_p3(0) = '1') else 
        var_cast_fu_1056_p4;
    select_ln6_1_fu_1419_p3 <= 
        ap_const_lv11_3FF when (tmp_15_fu_1411_p3(0) = '1') else 
        ap_const_lv11_3FE;
    select_ln6_fu_1355_p3 <= 
        sub_ln6_fu_1349_p2 when (tmp_14_fu_1341_p3(0) = '1') else 
        var_3_fu_1335_p3;
    select_ln9_1_fu_1645_p3 <= 
        add_ln9_3_reg_2346 when (tmp_16_reg_2322(0) = '1') else 
        shl_ln9_2_fu_1638_p3;
    select_ln9_2_fu_1758_p3 <= 
        tmp_21_fu_1748_p4 when (tmp_16_reg_2322(0) = '1') else 
        tmp_22_reg_2362;
    select_ln9_fu_1551_p3 <= 
        add_ln9_1_reg_2329 when (tmp_16_reg_2322(0) = '1') else 
        sext_ln9_2_fu_1547_p1;
    sext_ln22_fu_918_p0 <= grp_layernorm_kernel_Pipeline_accum_fu_690_sum_out;
        sext_ln22_fu_918_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln22_fu_918_p0),25));

        sext_ln23_1_fu_970_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mean_fu_962_p3),36));

    sext_ln23_fu_977_p0 <= grp_layernorm_kernel_Pipeline_accum_fu_690_sq_sum_out;
        sext_ln23_fu_977_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln23_fu_977_p0),25));

        sext_ln24_1_fu_1302_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln24_3_fu_1296_p2),11));

        sext_ln24_fu_1162_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln24_1_fu_1156_p2),11));

        sext_ln6_fu_1433_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln6_1_fu_1427_p2),11));

        sext_ln9_10_fu_1577_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_23_fu_1569_p3),60));

        sext_ln9_11_fu_1595_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_24_fu_1587_p3),60));

        sext_ln9_12_fu_1612_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_25_fu_1605_p3),60));

        sext_ln9_13_fu_1628_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_26_fu_1621_p3),60));

        sext_ln9_14_fu_1695_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_27_fu_1687_p3),72));

        sext_ln9_15_fu_1722_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_28_fu_1715_p3),72));

        sext_ln9_16_fu_1738_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_29_fu_1731_p3),72));

        sext_ln9_1_fu_1480_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_17_fu_1473_p3),48));

        sext_ln9_2_fu_1547_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln9_1_fu_1540_p3),48));

        sext_ln9_3_fu_1497_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_18_fu_1490_p3),48));

        sext_ln9_4_fu_1651_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln9_1_fu_1645_p3),61));

        sext_ln9_5_fu_1514_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_19_fu_1507_p3),48));

        sext_ln9_8_fu_1784_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln9_2_reg_2367),72));

        sext_ln9_9_fu_1530_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_20_fu_1523_p3),48));

    shl_ln24_1_fu_1260_p2 <= std_logic_vector(shift_left(unsigned(zext_ln24_2_fu_1247_p1),to_integer(unsigned('0' & zext_ln24_3_fu_1256_p1(31-1 downto 0)))));
    shl_ln24_fu_1120_p2 <= std_logic_vector(shift_left(unsigned(zext_ln24_fu_1107_p1),to_integer(unsigned('0' & zext_ln24_1_fu_1116_p1(31-1 downto 0)))));
    shl_ln6_fu_1391_p2 <= std_logic_vector(shift_left(unsigned(zext_ln6_fu_1378_p1),to_integer(unsigned('0' & zext_ln6_1_fu_1387_p1(31-1 downto 0)))));
    shl_ln9_1_fu_1540_p3 <= (var_3_reg_2285 & ap_const_lv23_0);
    shl_ln9_2_fu_1638_p3 <= (select_ln9_reg_2334 & ap_const_lv12_0);
    shl_ln9_fu_1764_p3 <= (var_3_reg_2285 & ap_const_lv11_0);
    shl_ln_fu_1029_p3 <= (select_ln23_fu_1021_p3 & ap_const_lv12_0);
    sub_ln22_1_fu_956_p2 <= std_logic_vector(unsigned(ap_const_lv18_0) - unsigned(tmp_19_cast_fu_936_p4));
    sub_ln22_fu_930_p2 <= std_logic_vector(unsigned(ap_const_lv25_0) - unsigned(sext_ln22_fu_918_p1));
    sub_ln23_1_fu_989_p2 <= std_logic_vector(unsigned(ap_const_lv25_0) - unsigned(sext_ln23_fu_977_p1));
    sub_ln23_2_fu_1005_p2 <= std_logic_vector(unsigned(ap_const_lv18_0) - unsigned(tmp_20_cast_fu_995_p4));
    sub_ln24_1_fu_1156_p2 <= std_logic_vector(unsigned(ap_const_lv5_C) - unsigned(trunc_ln24_1_fu_1103_p1));
    sub_ln24_2_fu_1221_p2 <= std_logic_vector(unsigned(ap_const_lv24_0) - unsigned(var_1_reg_2251));
    sub_ln24_3_fu_1296_p2 <= std_logic_vector(unsigned(ap_const_lv5_C) - unsigned(trunc_ln24_3_fu_1243_p1));
    sub_ln24_fu_1074_p2 <= std_logic_vector(unsigned(ap_const_lv23_0) - unsigned(var_cast_fu_1056_p4));
    sub_ln6_1_fu_1427_p2 <= std_logic_vector(unsigned(ap_const_lv5_C) - unsigned(trunc_ln6_1_fu_1374_p1));
    sub_ln6_fu_1349_p2 <= std_logic_vector(unsigned(ap_const_lv24_0) - unsigned(var_3_fu_1335_p3));
    sub_ln9_1_fu_1788_p2 <= std_logic_vector(unsigned(ap_const_lv72_1800000000000) - unsigned(mul_ln9_1_reg_2389));
    sub_ln9_2_fu_1484_p2 <= std_logic_vector(unsigned(p_shl1_fu_1466_p3) - unsigned(sext_ln9_1_fu_1480_p1));
    sub_ln9_3_fu_1501_p2 <= std_logic_vector(unsigned(sub_ln9_2_fu_1484_p2) - unsigned(sext_ln9_3_fu_1497_p1));
    sub_ln9_4_fu_1581_p2 <= std_logic_vector(unsigned(p_shl2_fu_1561_p3) - unsigned(sext_ln9_10_fu_1577_p1));
    sub_ln9_5_fu_1599_p2 <= std_logic_vector(unsigned(sub_ln9_4_fu_1581_p2) - unsigned(sext_ln9_11_fu_1595_p1));
    sub_ln9_6_fu_1681_p2 <= std_logic_vector(unsigned(p_shl_fu_1665_p3) - unsigned(p_shl3_fu_1673_p3));
    sub_ln9_7_fu_1699_p2 <= std_logic_vector(unsigned(sub_ln9_6_fu_1681_p2) - unsigned(sext_ln9_14_fu_1695_p1));
    sub_ln9_fu_1655_p2 <= std_logic_vector(unsigned(ap_const_lv61_1800000000000) - unsigned(sext_ln9_4_fu_1651_p1));
    tmp_11_fu_1443_p3 <= (tmp_14_reg_2296 & add_ln6_1_fu_1437_p2);
    tmp_12_fu_1280_p3 <= shl_ln24_1_fu_1260_p2(54 downto 54);
    tmp_14_fu_1341_p3 <= var_3_fu_1335_p3(23 downto 23);
    tmp_15_fu_1411_p3 <= shl_ln6_fu_1391_p2(54 downto 54);
    tmp_17_fu_1473_p3 <= (var_3_reg_2285 & ap_const_lv22_0);
    tmp_18_fu_1490_p3 <= (var_3_reg_2285 & ap_const_lv20_0);
    tmp_19_cast_fu_936_p4 <= sub_ln22_fu_930_p2(23 downto 6);
    tmp_19_fu_1507_p3 <= (var_3_reg_2285 & ap_const_lv18_0);
    tmp_20_cast_fu_995_p4 <= sub_ln23_1_fu_989_p2(23 downto 6);
    tmp_20_fu_1523_p3 <= (var_3_reg_2285 & ap_const_lv16_0);
    tmp_21_fu_1748_p4 <= add_ln9_5_fu_1742_p2(71 downto 48);
    tmp_23_fu_1569_p3 <= (select_ln9_fu_1551_p3 & ap_const_lv11_0);
    tmp_24_fu_1587_p3 <= (select_ln9_fu_1551_p3 & ap_const_lv9_0);
    tmp_25_fu_1605_p3 <= (select_ln9_reg_2334 & ap_const_lv7_0);
    tmp_26_fu_1621_p3 <= (select_ln9_reg_2334 & ap_const_lv5_0);
    tmp_27_fu_1687_p3 <= (sub_ln9_fu_1655_p2 & ap_const_lv9_0);
    tmp_28_fu_1715_p3 <= (sub_ln9_reg_2351 & ap_const_lv7_0);
    tmp_29_fu_1731_p3 <= (sub_ln9_reg_2351 & ap_const_lv5_0);
    tmp_2_fu_1091_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln24_reg_2235),24));
    tmp_3_fu_1172_p3 <= (tmp_6_reg_2230 & add_ln24_1_fu_1166_p2);
    tmp_4_fu_1312_p3 <= (tmp_10_reg_2258 & add_ln24_3_fu_1306_p2);
    tmp_5_fu_981_p1 <= grp_layernorm_kernel_Pipeline_accum_fu_690_sq_sum_out;
    tmp_5_fu_981_p3 <= tmp_5_fu_981_p1(23 downto 23);
    tmp_6_fu_1066_p3 <= add_ln23_fu_1041_p2(35 downto 35);
    tmp_8_fu_1140_p3 <= shl_ln24_fu_1120_p2(54 downto 54);
    tmp_fu_922_p1 <= grp_layernorm_kernel_Pipeline_accum_fu_690_sum_out;
    tmp_fu_922_p3 <= tmp_fu_922_p1(23 downto 23);
    trunc_ln24_1_fu_1103_p1 <= tmp_2_fu_1091_p3(5 - 1 downto 0);
    trunc_ln24_2_fu_1239_p1 <= tmp_9_fu_1232_p3(6 - 1 downto 0);
    trunc_ln24_3_fu_1243_p1 <= tmp_9_fu_1232_p3(5 - 1 downto 0);
    trunc_ln24_fu_1099_p1 <= tmp_2_fu_1091_p3(6 - 1 downto 0);
    trunc_ln6_1_fu_1374_p1 <= tmp_7_fu_1363_p3(5 - 1 downto 0);
    trunc_ln6_fu_1370_p1 <= tmp_7_fu_1363_p3(6 - 1 downto 0);
    trunc_ln9_1_fu_1661_p1 <= sub_ln9_fu_1655_p2(59 - 1 downto 0);
    trunc_ln9_fu_1557_p1 <= select_ln9_fu_1551_p3(47 - 1 downto 0);
    var_1_fu_1206_p3 <= 
        ap_const_lv24_800 when (empty_fu_1200_p2(0) = '1') else 
        var_reg_2224;
    var_3_fu_1335_p3 <= 
        ap_const_lv24_8000 when (tmp_13_reg_2280(0) = '1') else 
        var_1_reg_2251;
    var_cast_fu_1056_p4 <= add_ln23_fu_1041_p2(34 downto 12);
    zext_ln1_fu_1011_p1 <= grp_layernorm_kernel_Pipeline_accum_fu_690_sq_sum_out;
    zext_ln1_fu_1011_p4 <= zext_ln1_fu_1011_p1(23 downto 6);
    zext_ln24_1_fu_1116_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln24_fu_1110_p2),64));
    zext_ln24_2_fu_1247_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln24_2_reg_2264),64));
    zext_ln24_3_fu_1256_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln24_2_fu_1250_p2),64));
    zext_ln24_4_fu_1136_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_1126_p4),64));
    zext_ln24_5_fu_1276_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln24_1_fu_1266_p4),64));
    zext_ln24_fu_1107_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln24_reg_2235),64));
    zext_ln6_1_fu_1387_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln6_fu_1381_p2),64));
    zext_ln6_2_fu_1407_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln6_fu_1397_p4),64));
    zext_ln6_fu_1378_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln6_reg_2301),64));
    zext_ln_fu_946_p1 <= grp_layernorm_kernel_Pipeline_accum_fu_690_sum_out;
    zext_ln_fu_946_p4 <= zext_ln_fu_946_p1(23 downto 6);
end behav;
